<?php

$title = "Apply Business Term Loan";

$this->headTitle($title);

$personal_loan = $this->loan;

?>

<div id="page-apply" class="page-title"><h1><?php echo $title ?></h1></div>

<div id="content">

  <div class="apply-cart">

      <div class="container">

          <div class="row">

              <div class="content-cart">

                  <?php

                  $loan = $this->loan(array("id" => $personal_loan['loan_id']));

                  $bank = $this->bank(array("id" => $loan->getBankId()));



                  // Image

                  $dir_logo = 'data/bank/'.$loan->getBankId().'/m_'.$bank->getLogo();

                  if(!file_exists($dir_logo)) {

                      $dir_logo = 'data/image/no-image-128.png';

                  }

                  ?>

			    <div class="filters-table-content">

                      <div class="row-header">

                          <h4 class="bank-title"><a href="#"><?php echo $loan->getLoanTitle(); ?></a></h4>

			        </div>

			        <div class="row-content">

                          <div class="col-md-3 col-xs-12">

			                <a href="#">

							    <img src="<?php echo $this->basePath($dir_logo) ?>" alt="<?php echo $loan->getLoanTitle() ?>">

							</a>

			            </div>

			            <div class="col-md-3 col-xs-4 box__rate">

							<span class="rate"><b><?php echo $personal_loan['int_rate'] ?>%</b><?php echo $this->translate("Interest Rate") ?></span>

						</div>

						<div class="col-md-3 col-xs-4 box__loan">

		                     <span class="loan"><b><?php echo $personal_loan['loan_tenure'] ?> years</b><?php echo $this->translate("Loan Tenure") ?></span>

						</div>

						<div class="col-md-3 col-xs-4 box__month">

						     <span class="month"><b>$<?php echo number_format($personal_loan['monthly_payment']); ?></b><?php echo $this->translate("Per Month") ?></span>

						</div>

					</div>

			    </div>

              </div>

          </div>

      </div>

  </div>

  <div class="action-cart">
    <div class="action-cart-container">
      <div class="row">
        <div class="col-md-4 col-xs-12">
          <img class="approved-img" src="<?php echo $this->basePath() ?>/assets/img/icon-apply-9.png" title="<?php echo $loan->getLoanTitle(); ?>" alt="<?php echo $loan->getLoanTitle(); ?>" />
        </div>
        <div class="col-md-8 col-xs-12">
          <div class="row">
            <div class="col-md-12 benefit-title">
              <h3>Benefits of  applying through MoneyCompare.sg</h3>
            </div>
          </div>

          <div class="row content-action">
            <div class="row method">
              <div class="col-md-6 col-xs-12 benefit-item">
                <div class="col-md-4 col-xs-12">
                  <img src="<?php echo $this->basePath() ?>/assets/img/icon-apply-5.png" title="<?php echo $loan->getLoanTitle(); ?>" alt="<?php echo $loan->getLoanTitle(); ?>" />
                </div>
                <div class="col-md-8 col-xs-12 benefit-content">
                  <h4>HIGHER APPROVAL RATE</h4>
                  <p>As a team of ex bankers, we are very familiar with credit criteria of individual banks with a solid track record of >60% approval rate.</p>
                </div>
              </div>

              <div class="col-md-6 col-xs-12 benefit-item">
                <div class="col-md-4 col-xs-12">
                  <img src="<?php echo $this->basePath() ?>/assets/img/icon-apply-6.png" title="<?php echo $loan->getLoanTitle(); ?>" alt="<?php echo $loan->getLoanTitle(); ?>" />
                </div>
                <div class="col-md-8 col-xs-12 benefit-content">
                  <h4>HASSLE FREE APPROACH</h4>
                  <p>Leave the application process to our specialists while you focus your resources on your core business.</p>
                </div>
              </div>
            </div>

            <div class="row method">
              <div class="col-md-6 col-xs-12 benefit-item">
                <div class="col-md-4 col-xs-12">
                  <img src="<?php echo $this->basePath() ?>/assets/img/icon-apply-7.png" title="<?php echo $loan->getLoanTitle(); ?>" alt="<?php echo $loan->getLoanTitle(); ?>" />
                </div>
                <div class="col-md-8 col-xs-12 benefit-content">
                  <h4>FASTER TURNARAOUND TIME</h4>
                  <p>Tired of waiting for unresponsive bankers revert? Your application is our priority, reduce processing time by 3-5 working days through us!</p>
                </div>
              </div>

              <div class="col-md-6 col-xs-12 benefit-item">
                <div class="col-md-4 col-xs-12 ">
                  <img src="<?php echo $this->basePath() ?>/assets/img/icon-apply-8.png" title="<?php echo $loan->getLoanTitle(); ?>" alt="<?php echo $loan->getLoanTitle(); ?>" />
                </div>
                <div class="col-md-8 col-xs-12 benefit-content">
                  <h4>RISK FREE PROCESS</h4>
                  <p>No upftont fees, no fees applicable if we’re not enable to secure financing for your company. Performance guarantee, pay only for results!</p>
                </div>
              </div>
            </div>
          </div>
        </div>
  	  </div>
      <div class="row">
        <div class="button-action">
  		    <a href="<?php echo $this->url("personal_loan", array("action" => "apply-form")) ?>" class="btn blue btn-lg"><?php echo $this->translate("Apply") ?></a>
  		  </div>
      </div>

    </div>
  </div>

		  <?php if($loan->getUrl()): ?>
        <div class="text-center"><a href="<?php echo $loan->getUrl(); ?>"><?php echo $this->translate("No thanks, I can apply by myself") ?></a></div>
      <?php endif; ?>
  </div>
  </div>
</div>

<?php

$offStyle = 12;

$offScript = 10;

$this->inlineScript()->offsetSetFile(100, $this->basePath('assets/js/custom.js'));

$this->inlineScript()->captureStart();

echo <<<JS

JS;

$this->inlineScript()->captureEnd();

?>