<?php

$title = "Apply Business Term Loan";

$this->headTitle($title);

$personal_loan = $this->loan;

?>

<div id="page-apply" class="page-title"><h1><?php echo $title ?></h1></div>

<div id="content">

  <div class="apply-cart">

      <div class="container">

          <div class="row">

              <div class="content-cart">

                  <?php

                  $loan = $this->loan(array("id" => $personal_loan['loan_id']));

                  $bank = $this->bank(array("id" => $loan->getBankId()));



                  // Image

                  $dir_logo = 'data/bank/'.$loan->getBankId().'/m_'.$bank->getLogo();

                  if(!file_exists($dir_logo)) {

                      $dir_logo = 'data/image/no-image-128.png';

                  }

                  ?>

			    <div class="filters-table-content">

                      <div class="row-header">

                          <h4 class="bank-title"><a href="#"><?php echo $loan->getLoanTitle(); ?></a></h4>

			        </div>

			        <div class="row-content">

                          <div class="col-md-3 col-xs-12">

			                <a href="#">

							    <img src="<?php echo $this->basePath($dir_logo) ?>" alt="<?php echo $loan->getLoanTitle() ?>">

							</a>

			            </div>

			            <div class="col-md-3 col-xs-4 box__rate">

							<span class="rate"><b><?php echo $personal_loan['int_rate'] ?>%</b><?php echo $this->translate("Interest Rate") ?></span>

						</div>

						<div class="col-md-3 col-xs-4 box__loan">

		                     <span class="loan"><b><?php echo $personal_loan['loan_tenure'] ?> years</b><?php echo $this->translate("Loan Tenure") ?></span>

						</div>

						<div class="col-md-3 col-xs-4 box__month">

						     <span class="month"><b>$<?php echo number_format($personal_loan['monthly_payment']); ?></b><?php echo $this->translate("Per Month") ?></span>

						</div>

					</div>

			    </div>

              </div>

          </div>

      </div>

  </div>

  <?php echo $this->partial('action_cart_benefit', array('loan' => $loan, 'controller' => 'personal_loan')); ?>

		  <?php if($loan->getUrl()): ?>
        <div class="text-center"><a href="<?php echo $loan->getUrl(); ?>"><?php echo $this->translate("No thanks, I can apply by myself") ?></a></div>
      <?php endif; ?>
  </div>
  </div>
</div>

<?php

$offStyle = 12;

$offScript = 10;

$this->inlineScript()->offsetSetFile(100, $this->basePath('assets/js/custom.js'));

$this->inlineScript()->captureStart();

echo <<<JS

JS;

$this->inlineScript()->captureEnd();

?>