<div class="action-cart">
  <div class="action-cart-container">
    <div class="row benefit-content-container">
      <div class="col-md-4 col-xs-12 approved-large-image">
        <img class="approved-img" src="<?php echo $this->basePath() ?>/assets/img/icon-apply-9.png" title="<?php echo $loan->getLoanTitle(); ?>" alt="<?php echo $loan->getLoanTitle(); ?>" />
      </div>
      <div class="col-md-8 col-xs-12">
        <div class="row">
          <div class="col-md-12 benefit-title">
            <p><?php echo $this->translate('Benefits of applying through MoneyCompare.sg'); ?></p>
          </div>
        </div>

        <div class="row">
          <div class="row method">
            <div class="col-md-6 col-xs-12 benefit-item">
              <div class="col-md-4 col-xs-2 benefit-icon">
                <img src="<?php echo $this->basePath() ?>/assets/img/icon-apply-5.png" title="<?php echo $loan->getLoanTitle(); ?>" alt="<?php echo $loan->getLoanTitle(); ?>" />
              </div>
              <div class="col-md-8 col-xs-10 benefit-content">
                <h4><?php echo $this->translate('HIGHER APPROVAL RATE'); ?></h4>
                <p><?php echo $this->translate('As a team of ex bankers, we are very familiar with credit criteria of individual banks with a solid track record of >60% approval rate.'); ?></p>
              </div>
            </div>

            <div class="col-md-6 col-xs-12 benefit-item">
              <div class="col-md-4 col-xs-2 benefit-icon">
                <img src="<?php echo $this->basePath() ?>/assets/img/icon-apply-6.png" title="<?php echo $loan->getLoanTitle(); ?>" alt="<?php echo $loan->getLoanTitle(); ?>" />
              </div>
              <div class="col-md-8 col-xs-10 benefit-content">
                <h4><?php echo $this->translate('HASSLE FREE APPROACH'); ?></h4>
                <p><?php echo $this->translate('Leave the application process to our specialists while you focus your resources on your core business.'); ?></p>
              </div>
            </div>
          </div>

          <div class="row method">
            <div class="col-md-6 col-xs-12 benefit-item">
              <div class="col-md-4 col-xs-2 benefit-icon">
                <img src="<?php echo $this->basePath() ?>/assets/img/icon-apply-7.png" title="<?php echo $loan->getLoanTitle(); ?>" alt="<?php echo $loan->getLoanTitle(); ?>" />
              </div>
              <div class="col-md-8 col-xs-10 benefit-content">
                <h4><?php echo $this->translate('FASTER TURNARAOUND TIME'); ?></h4>
                <p><?php echo $this->translate('Tired of waiting for unresponsive bankers revert? Your application is our priority, reduce processing time by 3-5 working days through us!'); ?></p>
              </div>
            </div>

            <div class="col-md-6 col-xs-12 benefit-item">
              <div class="col-md-4 col-xs-2 benefit-icon ">
                <img src="<?php echo $this->basePath() ?>/assets/img/icon-apply-8.png" title="<?php echo $loan->getLoanTitle(); ?>" alt="<?php echo $loan->getLoanTitle(); ?>" />
              </div>
              <div class="col-md-8 col-xs-10 benefit-content">
                <h4><?php echo $this->translate('RISK FREE PROCESS'); ?></h4>
                <p><?php echo $this->translate('No upftont fees, no fees applicable if we’re not enable to secure financing for your company. Performance guarantee, pay only for results!'); ?></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="button-action">
        <a href="<?php echo $this->url("personal_loan", array("action" => "apply-form")) ?>" class="btn blue btn-lg"><?php echo $this->translate("Apply") ?></a>
      </div>
    </div>

  </div>
</div>