<!-- BEGIN HEADER -->
<div class="page-header navbar navbar-fixed-top">
    <!-- BEGIN HEADER INNER -->
    <div class="page-header-inner ">
        <!-- BEGIN LOGO -->
        <div class="page-logo">
            <a href="<?php echo $this->url('admin') ?>"><img src="<?php echo $this->basePath('data/company/logoa.png') ?>" alt="logo" class="logo-default" /> </a>
            <div class="menu-toggler sidebar-toggler"><span></span></div>
        </div>
        <!-- END LOGO -->
        <!-- BEGIN RESPONSIVE MENU TOGGLER -->
        <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse"><span></span></a>
        <!-- END RESPONSIVE MENU TOGGLER -->
                
        <!-- BEGIN TOP NAVIGATION MENU -->
        <div class="top-menu">
            <ul class="nav navbar-nav pull-right">
                <!-- BEGIN USER LOGIN DROPDOWN -->
                <li class="dropdown dropdown-user">
                    <?php 
                    if ($this->auth()->getAvatar()) {
                        $user_id = $this->auth()->getId();
                        $user_avatar = $this->auth()->getAvatar();
                        if (!file_exists('data/user/'.$user_id.'/s_'.$user_avatar)) {
                            $image_avatar = $this->basePath('data/user/'.$user_id.'/'.$user_avatar);
                        } else {
                            $image_avatar = $this->basePath('data/user/'.$user_id.'/s_'.$user_avatar);
                        }
                    } else {
                        $image_avatar = $this->basePath('data/user/no-avatar-32.png');
                    }
                    ?>
                    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                        <img alt="" class="img-circle" src="<?php echo $image_avatar ?>" />
                        <span class="username username-hide-on-mobile"> <?php echo $this->auth()->getDisplayname() ?> </span>
                        <i class="fa fa-angle-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-default">
                        <li><a href="<?php echo $this->url("admin/user", array("action" => "my-profile")) ?>"><i class="icon-user"></i> <?php echo $this->translate("My Profile"); ?> </a></li>
                                <li>
                                    <a href="#">
                                        <i class="icon-calendar"></i> My Calendar </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="icon-envelope-open"></i> My Inbox
                                        <span class="badge badge-danger"> 3 </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="app_todo.html">
                                        <i class="icon-rocket"></i> My Tasks
                                        <span class="badge badge-success"> 7 </span>
                                    </a>
                                </li>
                        <li class="divider"> </li>
                        <li><a href="<?php echo $this->url("admin/user", array("action" => "change-password")) ?>"><i class="icon-lock"></i> <?php echo $this->translate("Change Password"); ?> </a></li>
                        <li><a href="<?php echo $this->url("admin/user", array("action" => "logout")) ?>"><i class="icon-key"></i> <?php echo $this->translate("Log Out"); ?> </a></li>
                    </ul>
                </li>
                <!-- END USER LOGIN DROPDOWN -->
                <!-- BEGIN QUICK SIDEBAR TOGGLER -->
                <li class="dropdown dropdown-quick-sidebar-toggler">
                    <a href="<?php echo $this->url('home') ?>" target="_blank" title="<?php echo $this->translate("View Frontpage") ?>" class="dropdown-toggle"><i class="icon-screen-desktop"></i></a>
                </li>
                <!-- END QUICK SIDEBAR TOGGLER -->
            </ul>
        </div>
        <!-- END TOP NAVIGATION MENU -->
    </div>
    <!-- END HEADER INNER -->
</div>
<!-- END HEADER -->        