<div class="form-wizard">
  <div class="title-mortgage"><?php echo $this->translate("Business Loan Eligibility Calculator"); ?></div>
  <div id="personalInfo" style="display: block;">
      <form class="form-horizontal">
          <div class="form-body">
              <div class="form-group">
                  <div class="row form-wizard-title">
                      <h3>1. <?php echo $this->translate("Company Monthly Turnover") ?>?</h3>
                      <a href="javascript:;" class="tooltip-icon popovers" data-trigger="hover" data-placement="right" data-container="body" data-content="Lorem Ipsum is also known as: Greeked text, blind text, placeholder text, dummy content, filler text, lipsum, and mock-content." data-html="true" data-original-title="<span><?php echo $this->translate("Company Monthly Turnover") ?></span>"><i class="fa fa-question-circle"></i></a>
                  </div>
                  <div class="row">
                      <div class="col-md-12">
                          <div class="input-group col-md-6">
                              <input name="monthly_turnover" type="text" id="monthly-turnover" class="form-control" onkeyup="return enter_check(event);">
                              <span class="input-group-addon">
                                  <i>$</i>
                              </span>
                          </div>
                      </div>
                  </div>
              </div>
              <div class="form-group">
                  <div class="row form-wizard-title">
                      <h3>2. <?php echo $this->translate("Monthly Commmitement") ?>?</h3>
                      <a href="javascript:;" class="tooltip-icon popovers" data-trigger="hover" data-placement="right" data-container="body" data-content="Lorem Ipsum is also known as: Greeked text, blind text, placeholder text, dummy content, filler text, lipsum, and mock-content." data-html="true" data-original-title="<span><?php echo $this->translate("Monthly Commmitement") ?></span>"><i class="fa fa-question-circle"></i></a>
                  </div>
                  <div class="row">
                      <div class="col-md-12 clearfix">
                        <label class="control-label"><?php echo $this->translate("Total monthly installment for all Hire Purchase Loan"); ?></label>
                        <div class="input-group col-md-6">
                            <input name="purchase_loan" id="purchase_loan" type="text" class="form-control nobtngrp">
                            <span class="input-group-addon">$</span>
                        </div>
                      </div>
                      <div class="col-md-12 clearfix">
                        <label class="control-label"><?php echo $this->translate("Total monthly installment for all property loan"); ?></label>
                        <div class="input-group col-md-6">
                            <input name="property_loan" id="property_loan" type="text" class="form-control nobtngrp">
                            <span class="input-group-addon">$</span>
                        </div>
                      </div>
                      <div class="col-md-12 clearfix">
                        <label class="control-label"><?php echo $this->translate("Total monthly installment for all business term loan"); ?></label>
                        <div class="input-group col-md-6">
                            <input name="business_term_loan" id="business_term_loan" type="text" class="form-control nobtngrp">
                            <span class="input-group-addon">$</span>
                        </div>
                      </div>
                      <div class="col-md-12 clearfix">
                        <label class="control-label">
                          <?php echo $this->translate("Others"); ?>
                          <a href="javascript:;" class="tooltip-icon popovers" data-trigger="hover" data-placement="right" data-container="body" data-content="Lorem Ipsum is also known as: Greeked text, blind text, placeholder text, dummy content, filler text, lipsum, and mock-content." data-html="true" data-original-title="<span><?php echo $this->translate("Others") ?></span>"><i class="fa fa-question-circle"></i></a>
                        </label>
                        <div class="input-group col-md-6">
                            <input name="others" id="others" type="text" class="form-control nobtngrp">
                            <span class="input-group-addon">$</span>
                        </div>
                      </div>
                  </div>
              </div>
              <div class="form-group">
                  <div class="row form-wizard-title">
                      <h3>3. <?php echo $this->translate("What Industry Are You In") ?>?</h3>
                  </div>
                  <div class="row">
                      <div class="col-md-12">
                          <div class="md-radio-list">
                            <?php foreach(array("Professionals", "Services", "Logistics & Transportation", "Food & Bev", "Wholesale", "Import & Export", "Trading", "Manufacturing", "Construction", "Retail") as $industry) { ?>
                                <div class="md-radio">
                                  <input type="radio" id="<?php echo strtolower(str_replace(' ', '_', $industry)); ?>_industry_property" name="industry_type" value="<?php echo $industry; ?>" class="md-radiobtn" <?php  echo ($i == 0) ? 'checked' : ''; ?>>
                                  <label for="<?php echo strtolower(str_replace(' ', '_', $industry)); ?>_industry_property">
                                      <span></span>
                                      <span class="check"></span>
                                      <span class="box"></span> <?php echo $this->translate($industry); ?>
                                  </label>
                                </div>
                             <?php } ?>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div class="form-actions">
              <div class="col-md-3 col-sm-6 col-xs-12">
                  <button type="button" id="submit-reset" class="btn grey-mint btn-lg pull-left font-white"><?php echo $this->translate('Reset'); ?></button>
              </div>
              <div class="col-md-3 col-sm-6 col-xs-12">
                  <button type="button" id="submit-prepayment" class="btn btn-lg green-custom pull-right"><?php echo $this->translate('Calculate'); ?></button>
              </div>
          </div>
      </form>
  </div>
</div>
<?php
$this->headLink()->offsetSetStylesheet(12, $this->basePath('assets/plugins/jquery-ui/jquery-ui.min.css'));
$this->inlineScript()->offsetSetFile(4, $this->basePath('assets/plugins/jquery-ui/jquery-ui.min.js'));
$this->inlineScript()->offsetSetFile(100, $this->basePath('assets/js/jquery.ui.touch-punch.min.js'));
$this->inlineScript()->offsetSetFile(101, $this->basePath('assets/js/loan-eligibility-calculator.js'));
?>