<div class="box-featured-bank">
  <div class="featured-bank lowest-interest">
    <h3 class="title-featured"><?php echo $this->translate("Filter"); ?></h3>
    <div class="box-search">
      <form>
        <div class="form-group clearfix">
          <label><?php echo $this->translate("Best for") ?>...</label>
          <select name="select_category_credit_card" class="form-control">
            <option value="all"><?php echo $this->translate("Choose your rewards") ?>...</option>
            <option value="discount"<?php if($this->credit_card_category === 'discount') echo " selected" ?>><?php echo $this->translate("Discount") ?></option>
            <option value="points"<?php if($this->credit_card_category === 'points') echo " selected" ?>><?php echo $this->translate("Points") ?></option>
            <option value="air-miles"<?php if($this->credit_card_category === 'air-miles') echo " selected" ?>><?php echo $this->translate("Air Miles") ?></option>
            <option value="cash-back"<?php if($this->credit_card_category === 'cash-back') echo " selected" ?>><?php echo $this->translate("Cash Back") ?></option>
          </select>
        </div>
        <hr />
        <div class="banks-filter">
          <label>
            <?php echo $this->translate("Banks") ?>
          </label>
          <div class="clearfix">
            <?php foreach ($this->banks as $key => $bank):
              $dir_bank_logo = 'data/bank/'.$bank->getId().'/m_'.$bank->getLogo();
              if(!file_exists($dir_bank_logo)) {
                $dir_bank_logo = '/assets/img/credit-card.png';
              }
              ?>
              <div style="height: 102px" class="col-md-6 mg-bottom-xs" data-bank-id=<?php echo $bank->getId(); ?> onclick="CreditCard.filterBank(this)" >
                <img src="<?php echo $this->basePath($dir_bank_logo); ?>" alt="<?php echo $bank->getName(); ?>" class="bank-logo">
              </div>
            <?php endforeach;?>
          </div>
        </div>
        <hr />
        <div class="card-providers-filter">
          <label>
            <?php echo $this->translate("Card providers") ?>
          </label>
            <ul class="panel__list--clean panel__list--provider">
            <?php foreach ($this->providers as $key => $provider):
              $dir_provider_logo = 'data/providers/'.$provider->getId().'/m_'.$provider->getLogo();
              if(!file_exists($dir_provider_logo)) {
                $dir_provider_logo = '/assets/img/credit-card.png';
              }
            ?>
              <li class="" onclick="CreditCard.filterBank(this)" data-provider-id="<?php echo $provider->getId(); ?>" >
                <img src="<?php echo $this->basePath($dir_provider_logo); ?>" alt="<?php echo $provider->getName(); ?>" title="<?php echo $provider->getName(); ?>">
              </li>
            <?php endforeach;?>
          </ul>
        </div>
        <hr />
        <div class="loan-filter">
          <input type="hidden" name="select_category_credit_card" value="<?php echo $this->select_category_credit_card ?>">
          <input type="hidden" name="bank_id" value="<?php echo $this->bank_id ?>" />
          <input type="hidden" name="provider_id" value="<?php echo $this->provider_id ?>" />
          <button type="button" class="btn btn-lg green-custom ladda-button" onclick="CreditCard.filter(this)" data-style="expand-left"><i class="fa fa-refresh"></i> <?php echo $this->translate("Refresh Results") ?></button>
        </div>
      </form>
    </div>
  </div>
</div>