<div id="testimonials" class="test-businesss">
    <div class="container">
        <h3 class="title-test">Satisfied customers agree!</h3>
        <div class="row">
            <div class="box-content">
				<div class="item col-xs-12">
					<div class="content-test">
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate.</p>
                        <div class="image-test" style="background: url('<?php echo $this->basePath('assets/img/user-1.jpg') ?>') no-repeat center center;">							</div>
						<span><b>Michael LH</b><i>ACB Officer</i></span>
					</div>
				</div>
				<div class="item col-xs-12">
					<div class="content-test">
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate.</p>
                        <div class="image-test" style="background: url('<?php echo $this->basePath('assets/img/user-2.jpg') ?>') no-repeat center center;"></div>
						<span><b>Michael LH</b><i>ACB Officer</i></span>
					</div>
				</div>
            </div>
        </div>
    </div>
</div>

<div id="personal-loan">
    <div class="container">
        <div class="row">
            <h3 class="title-loans">Finding the Best Personal Loan is Easy</h3>
            <span>Here are some benefits of comparing and applying for your loan through MoneySmart.sg</span>
				<div class="content-loans">
					<div class="col-sm-4 col-xs-12">
						<div class="image-loans">
							<img src="<?php echo $this->basePath('assets/img/icon-loan-1.png') ?>" alt="" title=""> 
						</div>
						<h3>Save Time</h3>
						<p>We've aggregated all the latest Personal Loan rates so you can compare them easily.</p>
					</div>
					<div class="col-sm-4 col-xs-12">
						<div class="image-loans">
							<img src="<?php echo $this->basePath('assets/img/icon-loan-2.png') ?>" alt="" title=""> 
						</div>
						<h3>Compare Easily</h3>
						<p>Find better Personal Loan rates and promotions you might have missed.</p>
					</div>
					<div class="col-sm-4 col-xs-12">
						<div class="image-loans">
							<img src="<?php echo $this->basePath('assets/img/icon-loan-3.png') ?>" alt="" title=""> 
						</div>
						<h3>Hassle Free</h3>
						<p>Apply hassle free online and get the cash you need as soon as possible. It’s easy.</p>
					</div>
				</div>
        </div>
    </div>
</div>