<div class="page-footer">
	<div class="container">
        <div class="row">
            <div class="col-md-12">&copy; 2016 <?php echo $this->setting()->company_name; ?>. All rights reserved. Use of this site constitutes acceptance of our <a href="#" target="_blank"><?php echo $this->translate("Terms of Use") ?></a> and <a href="#" target="_blank"><?php echo $this->translate("Privacy Policy") ?></a></div>
        </div>
    </div>
</div>
<div class="scroll-to-top">
    <i class="icon-arrow-up"></i>
</div>
<?php echo $this->inlineScript() ?>