<?php echo $this->partial('testimonials', array('testimonials' => $testimonials)); ?>

<div id="personal-loan">
    <div class="container">
        <div class="row">
            <h3 class="title-loans">FINDING THE BEST BUSINESS LOAN IS EASY</h3>
            <span>Here are some benefits of applying for your loan through MoneyCompare.sg</span>
				<div class="content-loans">
					<div class="col-sm-4 col-xs-12">
            <div class="col-sm-6">
              <div class="image-loans">
                <img src="<?php echo $this->basePath('assets/img/icon-subfooter-1.png') ?>" alt="" title="">
              </div>
            </div>
            <div class="col-sm-6">
              <h3>SAVING TIME</h3>
              <p>We’ve aggregated all the latest Business Loan so you can save time comparing them.</p>
            </div>
					</div>
					<div class="col-sm-4 col-xs-12">
            <div class="col-sm-6">
              <div class="image-loans">
                <img src="<?php echo $this->basePath('assets/img/icon-subfooter-2.png') ?>" alt="" title="">
              </div>
            </div>
            <div class="col-sm-6">
              <h3>EASY COMPARING</h3>
              <p>Find Business Loan rates and promotions you might have missed.</p>
            </div>
					</div>
					<div class="col-sm-4 col-xs-12">
            <div class="col-sm-6">
  						<div class="image-loans">
  							<img src="<?php echo $this->basePath('assets/img/icon-subfooter-3.png') ?>" alt="" title="">
  						</div>
            </div>
            <div class="col-sm-6">
  						<h3>HASSLE FREE</h3>
  						<p>Apply hassle free online and get the cash you need as soon as possible. It is easy</p>
            </div>
					</div>
				</div>
        </div>
    </div>
</div>