<?php
$title = $this->translate("Edit Bank Account");
$this->headTitle($title);

function buildTree(Array $data, $parent = 0) {
    $tree = array();
    foreach ($data as $d) {
        if ($d['parent'] == $parent) {
            $children = buildTree($data, $d['id']);
            // set a trivial key
            if (!empty($children)) {
                $d['_children'] = $children;
            }
            $tree[] = $d;
        }
    }
    return $tree;
}

function printTree($tree, $r = 0, $p = null, $c = null) {
    foreach ($tree as $i => $t) {
        $dash = ($t['parent'] == 0) ? '' : str_repeat('-', $r) .' ';
        if($c == $t['id']) {
            printf("\t<option value='%d' selected>%s%s</option>\n", $t['id'], $dash, $t['name']);
        } else {
            printf("\t<option value='%d'>%s%s</option>\n", $t['id'], $dash, $t['name']);
        }
        if ($t['parent'] == $p) {
            // reset $r
            $r = 0;
        }
        if (isset($t['_children'])) {
            printTree($t['_children'], ++$r, $t['parent'], $c);
        }
    }
}

$rows = array();
$categories = $this->categories(array("status" => 1, "type" => "bank_account"));                                 
if(count($categories) > 0) {
    foreach ($categories as $category) {
        $rows[] = array(
            'id' => $category->getId(),
            'name' => $category->getName(),
            'parent' => $category->getParentId(),
        );
    }
}
?>
<!-- BEGIN SIDEBAR -->
<?php echo $this->partial('backend_sidebar', array('view' => 'admin_bank_account', 'action' => 'index')); ?>
<!-- END SIDEBAR -->
<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
    <div class="page-content">
        <!-- BEGIN PAGE BAR -->
        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <a href="<?php echo $this->url('admin') ?>"><?php echo $this->translate("Dashboard") ?></a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="<?php echo $this->url('admin/admin_bank_account') ?>"><?php echo $this->translate("Bank Account") ?></a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <span><?php echo $this->translate("Edit") ?></span>
                </li>
            </ul>
        </div>
        <!-- END PAGE BAR -->
        
        <div class="row">
            <div class="col-md-12">
                <div class="portlet light bordered form-fit">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="icon-bank"></i>
                            <span class="caption-subject sbold uppercase"><?php echo $this->translate($title) ?></span>
                        </div>
                    </div>
                    <div class="portlet-body form">
                        <!-- BEGIN FORM-->
                        <form action="<?php echo $this->url("admin/admin_bank_account", array("action" => "edit", "id" => $this->loan->getId())) ?>" id="form_bank" class="form-horizontal form-bordered">
                            <div class="form-body">
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Category") ?><span class="required"> * </span></label>
                                    <div class="col-md-6">
                                        <select name="category_id" class="form-control">
                                            <option value=""><?php echo $this->translate("[select]") ?></option>
                                            <?php 
                                            $tree = buildTree($rows);
                                            printTree($tree, 0, null, $this->loan->getCategoryId());
                                            ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group hide">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Category Account") ?><span class="required"> * </span></label>
                                    <div class="col-md-6">
                                        <select name="category_account" class="form-control">
                                            <option <?php if($this->loan->getCategoryAccount()==3) echo 'selected'?> value="3">3 months</option>
                                            <option <?php if($this->loan->getCategoryAccount()==6) echo 'selected'?> value="6">6 months</option>
                                            <option <?php if($this->loan->getCategoryAccount()==9) echo 'selected'?> value="9">9 months</option>
                                            <option <?php if($this->loan->getCategoryAccount()==12) echo 'selected'?> value="12">12 months</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Bank") ?><span class="required"> * </span></label>
                                    <div class="col-md-6">
                                        <select name="bank_id" class="form-control">
                                            <option value=""><?php echo $this->translate("[select]") ?></option>
                                            <?php
                                            $banks = $this->banks(array("status" => 1));
                                            if(count($banks) > 0) {
                                                foreach ($banks as $bank) {
                                                    ?>
                                                    <option value="<?php echo $bank->getId() ?>"<?php if($bank->getId() == $this->loan->getBankId()) echo ' selected'; ?>><?php echo $bank->getName() ?></option>
                                                    <?php
                                                }
                                            }
                                            ?>
                                        </select>
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Loan title") ?></label>
                                    <div class="col-md-6">
                                        <input type="text" name="loan_title" class="form-control" value="<?php echo $this->loan->getLoanTitle() ?>" /> 
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Promotions title") ?></label>
                                    <div class="col-md-6">
                                        <textarea name="promotions" class="form-control" rows="2"><?php echo $this->loan->getPromotions() ?></textarea>
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Apply Link") ?></label>
                                    <div class="col-md-6">
                                        <input type="text" name="link" class="form-control" value="<?php echo $this->loan->getLink() ?>" />
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Interest Rate") ?> <span class="required"> * </span></label>
                                    <div class="col-md-6">
                                        <input type="text" name="int_rate" class="form-control" value="<?php echo $this->loan->getIntRate() ?>" /> 
                                    </div>
                                </div>
                                
                                <div class="form-group initial_deposit_amount">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Initial Deposit Amount") ?></label>
                                    <div class="col-md-6">
                                        <input type="text" name="initial_deposit_amount" class="form-control" value="<?php echo $this->loan->getInitialDepositAmount() ?>" required/> 
                                    </div>
                                </div>
                                
                                <div class="form-group minimum_balance">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Minimum Balance") ?></label>
                                    <div class="col-md-6">
                                        <input type="text" name="minimum_balance" class="form-control" value="<?php echo $this->loan->getMinimumBalance() ?>" /> 
                                    </div>
                                </div>
                                
                                <div class="form-group tenor hide">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Tenor(Fixed Deposit)") ?></label>
                                    <div class="col-md-6">
                                        <input type="text" name="tenor" class="form-control" value="<?php echo $this->loan->getTenor() ?>" /> 
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Cheque Book Fees") ?></label>
                                    <div class="col-md-6">
                                        <input type="text" name="cheque_book_fees" class="form-control" value="<?php echo $this->loan->getChequeBookFees() ?>" /> 
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Internet Banking Fees") ?></label>
                                    <div class="col-md-6">
                                        <input type="text" name="internet_banking_fees" class="form-control" value="<?php echo $this->loan->getInternetBankingFees() ?>" /> 
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Annual Fee") ?></label>
                                    <div class="col-md-6">
                                        <input type="text" name="annual_fee" class="form-control" value="<?php echo $this->loan->getAnnualFee() ?>" /> 
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Service Fee") ?></label>
                                    <div class="col-md-6">
                                        <input type="text" name="service_fee" class="form-control" value="<?php echo $this->loan->getServiceFee() ?>" /> 
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Highlight") ?></label>
                                    <div class="col-md-6">
                                        <!-- <input type="text" name="highlight" class="form-control editor" value="<?php echo $this->loan->getHighlight() ?>" />  -->
                                        <textarea class="form-control editor"><?php echo $this->loan->getHighlight() ?></textarea>
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Citizenship") ?></label>
                                    <div class="col-md-6">
                                        <input type="text" name="citizenship" class="form-control" value="<?php echo $this->loan->getCitizenship() ?>" /> 
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Age") ?></label>
                                    <div class="col-md-6">
                                        <input type="text" name="age" class="form-control" value="<?php echo $this->loan->getAge() ?>" /> 
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Status") ?></label>
                                    <div class="col-md-6">
                                        <select class="form-control" name="status">
                                            <option value="1"<?php if($this->loan->getStatus() == 1) echo ' selected="selected"'; ?>><?php echo $this->translate("Active") ?></option>
                                            <option value="0"<?php if($this->loan->getStatus() == 0) echo ' selected="selected"'; ?>><?php echo $this->translate("Deactive") ?></option>
                                        </select>
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Interest Rates") ?></label>
                                    <div class="col-md-9">
                                        <div class="form-group mt-repeater">
                                            <div data-repeater-list="interest-rate" style="border-left: 0;">
                                                <?php
                                                if($this->loan->getInterestRate()) {
                                                    $interest_rate = \Zend\Json\Json::decode($this->loan->getInterestRate());
                                                    if(count($interest_rate) > 0) {
                                                        foreach ($interest_rate as $key => $value) {
                                                            ?>
                                                            <div data-repeater-item class="mt-repeater-item">
                                                                <div class="row mt-repeater-row">
                                                                    <div class="col-md-8">
                                                                        <label class="control-label"><?php echo $this->translate("Tier(for Savings Account) / Months(for Fixed Deposit)") ?></label>
                                                                        <div class="col-md-12 input-group">
                                                                            <input type="number" min="0" name="tier" class="form-control" value="<?php echo $value->tier ?>" />
                                                                            <span class="input-group-addon"><?php echo $this->translate("Month") ?></span>
                                                                        </div> 
                                                                    </div>
                                                                    <div class="col-md-4">
                                                                        <label class="control-label"><?php echo $this->translate("Percentage") ?></label>
                                                                        <div class="col-md-12 input-group">
                                                                            <input type="number" min="0" name="percentage" class="form-control" value="<?php echo $value->percentage ?>" />
                                                                            <span class="input-group-addon"><?php echo $this->translate("%") ?></span>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                                <div class="row mt-repeater-row">
                                                                    <div class="col-md-12" style="padding-top: 20px;">
                                                                        <a href="javascript:;" data-repeater-delete class="btn btn-danger mt-repeater-delete">
                                                                            <i class="fa fa-close"></i> <?php echo $this->translate("Remove Interest Rate row") ?></a>
                                                                        </a>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <?php    
                                                        }
                                                    }
                                                } else {
                                                    ?>
                                                    <div data-repeater-item class="mt-repeater-item">
                                                        <div class="row mt-repeater-row">
                                                            <div class="col-md-8">
                                                                <label class="control-label"><?php echo $this->translate("Tier(for Savings Account) / Months(for Fixed Deposit)") ?></label>
                                                                <div class="col-md-12 input-group">
                                                                    <input type="text" name="tier" class="form-control" />
                                                                    <span class="input-group-addon"><?php echo $this->translate("Month") ?></span>
                                                                </div> 
                                                            </div>
                                                            <div class="col-md-4">
                                                                <label class="control-label"><?php echo $this->translate("Percentage") ?></label>
                                                                <div class="col-md-12 input-group">
                                                                    <input type="text" name="percentage" class="form-control" />
                                                                    <span class="input-group-addon"><?php echo $this->translate("%") ?></span>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="row mt-repeater-row">
                                                            <div class="col-md-12" style="padding-top: 20px;">
                                                                <a href="javascript:;" data-repeater-delete class="btn btn-danger mt-repeater-delete">
                                                                    <i class="fa fa-close"></i> <?php echo $this->translate("Remove Interest Rate row") ?></a>
                                                                </a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                <?php } ?>
                                            </div>
                                            <div style="border-left: 0;">
                                                <a href="javascript:;" data-repeater-create class="btn btn-info mt-repeater-add">
                                                    <i class="fa fa-plus"></i> <?php echo $this->translate("Add Interest Rate") ?></a>
                                            </div>
                                        </div>        
                                    </div>
                                </div>
                                
                            </div>
                            <div class="form-actions">
                                <div class="row">
                                    <div class="col-md-offset-3 col-md-9">
                                        <button type="submit" class="btn red-thunderbird"><i class="fa fa-check"></i> <?php echo $this->translate("Submit") ?></button>
                                        <button type="button" class="btn btn-outline" onclick="cancel('admin/bank-account')"><?php echo $this->translate("Cancel") ?></button>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <!-- END FORM-->
                    </div>
                </div>
            </div>
        </div>
    </div>            
</div>
<!-- END CONTENT -->
<?php
$offStyle = 12;
$offScript = 10;
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/jquery-repeater/jquery.repeater.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/jquery-validation/js/jquery.validate.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/jquery-validation/js/additional-methods.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/tinymce/js/tinymce/tinymce.min.js'));
$this->inlineScript()->offsetSetFile(100, $this->basePath('assets/js/custom_functions.js'));
$this->inlineScript()->captureStart();
echo <<<JS
var category_name = $("select[name=category_id] option:selected").text();
if(category_name === 'Fixed Deposit') {
    $('.tenor').removeClass('hide');
    $('input[name=tenor]').attr('required',true);
}
$('select[name=category_id]').on("change", function() {
    var category_name = $("select[name=category_id] option:selected").text();    
    if(category_name === 'Fixed Deposit') {
        $('.tenor').removeClass('hide');
        $('input[name=tenor]').attr('required',true);
        $('.initial_deposit_amount label').text('Fixed Deposit Amount');
        $('.minimum_balance label').text('Minimum Deposit');
    } else {
        $('.tenor').addClass('hide');
        $('input[name=tenor]').attr('required',false);
        $('.initial_deposit_amount label').text('Initial Deposit Amount');
        $('.minimum_balance label').text('Minimum Balance');
    }
});
$("select[name=category_id]").trigger("change");

tinymce.init({
    selector: '.editor',
    height: 300,
    plugins: [
        'advlist autolink lists link image charmap print preview anchor',
        'searchreplace visualblocks code fullscreen',
        'insertdatetime media table contextmenu paste code'
    ],
    toolbar: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
    content_css: full_url+'/assets/css/codepen.min.css',
    setup: function (editor) {
        editor.on('change', function () {
            editor.save();
        });
    }
});

$('.mt-repeater').each(function(){
    $(this).repeater({
        show: function () {
       	    $(this).slideDown();
        },
        hide: function (deleteElement) {
            if(confirm('Are you sure you want to delete this element?')) {
                $(this).slideUp(deleteElement);
            }
        },
        ready: function (setIndexes) {
            
        }
    });
});

var form = $('#form_bank');
form.validate({
    errorElement: 'span', //default input error message container
    errorClass: 'help-block', // default input error message class
    focusInvalid: false, // do not focus the last invalid input
    ignore: "",
    rules: {
        bank_id: {
            required: true
        },
        loan_title: {
            required: true
        },
        int_rate: {
            required: true
        },
        link: {
            required: false,
            url: true
        }
    },
    
    highlight: function(element) { // hightlight error inputs
        $(element)
            .closest('.form-group').addClass('has-error'); // set error class to the control group
    },

    success: function(label) {
        label.closest('.form-group').removeClass('has-error');
        label.remove();
    },

    errorPlacement: function(error, element) {
        error.insertAfter(element);
    },

    submitHandler: function (form) {
        // setup some local variables
        var form = $(form);
        
        // let's select and cache all the fields
        var inputs = form.find("input, select, button, textarea");
        
        // serialize the data in the form
        var serializedData = form.serialize();
    
        // let's disable the inputs for the duration of the ajax request
        inputs.prop("disabled", true);
        
        // fire off the request to /form.php

        request = $.ajax({
            url: form.attr("action"),
            type: "post",
            data: serializedData
        });
        
        // Clear Message
        $('#form_bank .form-group').removeClass('has-error');
        $('#form_bank .help-block, #form_bank .alert').remove();
        
        // callback handler that will be called on success
        request.done(function (response, textStatus, jqXHR) {
            var result = $.parseJSON(response);
            if(result.error) {
                toastr.error("Something error. Please check");
            } else {
                if(result.success) {
                    toastr.success(result.msg);
                    setTimeout(function(){ window.location.href = full_url+'/admin/bank-account'; }, 1500);
                } else {
                    toastr.warning(result.msg);
                }
            }
        });
        
        // callback handler that will be called on failure
        request.fail(function (jqXHR, textStatus, errorThrown) {
            // log the error to the console
            toastr.error("The following error occured: " + textStatus, errorThrown);
        });
        
        // callback handler that will be called regardless
        // if the request failed or succeeded
        request.always(function () {
            // reenable the inputs
            inputs.prop("disabled", false);
        });
    }
});
JS;
$this->inlineScript()->captureEnd();
?>