<?php
$title = $this->translate("Edit Slider");
$this->headTitle($title);
?>
<!-- BEGIN SIDEBAR -->
<?php echo $this->partial('backend_sidebar', array('view' => 'slider', 'action' => 'slider')); ?>
<!-- END SIDEBAR -->
<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
    <div class="page-content">
        <!-- BEGIN PAGE BAR -->
        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <a href="<?php echo $this->url('admin') ?>"><?php echo $this->translate("Dashboard") ?></a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="<?php echo $this->url('admin/slider') ?>"><?php echo $this->translate("Sliders") ?></a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <span><?php echo $this->translate("Edit Slider") ?></span>
                </li>
            </ul>
        </div>
        <!-- END PAGE BAR -->
        <div class="row">
            <div class="col-md-12">
                <div class="portlet light bordered form-fit">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="icon-picture"></i>
                            <span class="caption-subject sbold uppercase"><?php echo $this->translate($title) ?></span>
                        </div>
                    </div>
                    <div class="portlet-body form">
                        <!-- BEGIN FORM-->
                        <form action="<?php echo $this->url("admin/slider", array('action' => "edit", "id" => $this->post->getId())) ?>" id="form_post" class="form-horizontal form-bordered">
                            <div class="form-body">
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Name") ?><span class="required"> * </span></label>
                                    <div class="col-md-6">
                                        <input type="text" name="name" data-required="1" class="form-control" value="<?php echo $this->post->getName() ?>" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Location") ?></label>
                                    <div class="col-md-6">
                                        <select class="form-control" name="type">
                                            <option value="0" <?php echo $this->post->getType() == 0 ? 'selected' : '' ?> ><?php echo $this->translate("Home Page") ?></option>
                                            <option value="1" <?php echo $this->post->getType() == 1 ? 'selected' : '' ?>><?php echo $this->translate("Credit Card") ?></option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Image") ?></label>
                                    <div class="col-md-6">
                                        <div class="fileinput fileinput-new" data-provides="fileinput">
                                            <div class="input-group">
                                                <div class="form-control uneditable-input input-fixed" data-trigger="fileinput">
                                                    <i class="fa fa-camera fileinput-exists"></i>&nbsp;
                                                    <span class="fileinput-filename"> </span>
                                                </div>
                                                <span class="input-group-addon btn default btn-file">
                                                    <span class="fileinput-new"> <?php echo $this->translate("Select file") ?> </span>
                                                    <span class="fileinput-exists"> <?php echo $this->translate("Change") ?> </span>
                                                    <input type="file" name="photoupload" id="photoupload" />
                                                    <input type="hidden" name="url" id="featured_image" value="<?php echo $this->post->getUrl() ?>" />
                                                </span>
                                                <a href="javascript:;" class="input-group-addon btn red fileinput-exists" data-dismiss="fileinput"> <?php echo $this->translate("Remove") ?> </a>
                                            </div>
                                        </div>
                                        <?php
                                        if ($this->post->getUrl()) {
                                            $post_image = $this->post->getUrl();
                                            if (!file_exists('data/image/'.$post_image)) {
                                                $image_src = 'data/image/'.$post_image;
                                            } else {
                                                $image_src = 'data/image/'.$post_image;
                                            }
                                        } else {
                                            $image_src = 'data/image/no-image-128.png';
                                        }
                                        ?>
                                        <img id="photo" alt="featured image" src="<?php echo $this->basePath($image_src) ?>" width="100%" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Link") ?><span class="required"> * </span></label>
                                    <div class="col-md-6">
                                        <input type="text" name="link" data-required="1" class="form-control" value="<?php echo $this->post->getLink() ?>" />
                                    </div>
                                </div>
                            </div>
                            <div class="form-actions">
                                <div class="row">
                                    <div class="col-md-offset-3 col-md-9">
                                        <button type="submit" class="btn red-thunderbird"><i class="fa fa-check"></i> <?php echo $this->translate("Submit") ?></button>
                                        <button type="button" class="btn btn-outline" onclick="cancel('admin/slider')"> <?php echo $this->translate("Cancel") ?></button>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <!-- END FORM-->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END CONTENT -->
<?php
$offStyle = 12;
$offScript = 12;
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/bootstrap-fileinput/bootstrap-fileinput.css'));
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css'));
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/sweetalert2/sweetalert2.css'));
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/dropzone/basic.min.css'));
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/dropzone/dropzone.min.css'));
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/css/simplePagination.css'));
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/mlib/css/mlib.css'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/bootstrap-fileinput/bootstrap-fileinput.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/tinymce/js/tinymce/tinymce.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/dropzone/dropzone.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/js/jquery.simplePagination.js'));
$this->inlineScript()->offsetSetFile(30, $this->basePath('assets/plugins/jquery-validation/js/jquery.validate.min.js'));
$this->inlineScript()->offsetSetFile(31, $this->basePath('assets/plugins/jquery-validation/js/additional-methods.min.js'));
$this->inlineScript()->offsetSetFile(32, $this->basePath('assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js'));
$this->inlineScript()->offsetSetFile(33, $this->basePath('assets/plugins/mlib/js/mlib.js'));
$this->inlineScript()->offsetSetFile(34, $this->basePath('assets/plugins/sweetalert2/sweetalert2.min.js'));
$this->inlineScript()->offsetSetFile(100, $this->basePath('assets/js/custom_functions.js'));
$this->inlineScript()->captureStart();
echo <<<JS
$('#photoupload').on("change", function(){
    var form = document.getElementById('form_post');
    var fileInput = document.getElementById('photoupload');
    var file = fileInput.files[0];
    var formData = new FormData();
    formData.append('file', file);
    var xhr = new XMLHttpRequest();
    xhr.onreadystatechange = function() {
        if (xhr.readyState == 4) {
            var result = $.parseJSON(xhr.responseText);
            if(result.success === true) {
                toastr.success("Photo uploaded.");
                $('#photo').attr("src", full_url + result.src);
                $('#featured_image').val(result.name);
            } else {
                toastr.warning(result.msg);
            }
        }
    }
    // Add any event handlers here...
    xhr.open('POST', full_url + "/admin/slider/change-image", true);
    xhr.send(formData);
});

var form = $('#form_post');
form.validate({
    errorElement: 'span', //default input error message container
    errorClass: 'help-block', // default input error message class
    focusInvalid: false, // do not focus the last invalid input
    ignore: "",
    rules: {
        post_title: {
            required: true
        },
        seo: {
            required: true
        }
    },

    highlight: function(element) { // hightlight error inputs
        $(element)
            .closest('.form-group').addClass('has-error'); // set error class to the control group
    },

    success: function(label) {
        label.closest('.form-group').removeClass('has-error');
        label.remove();
    },

    errorPlacement: function(error, element) {
        error.insertAfter(element);
    },

    submitHandler: function (form) {
        // setup some local variables
        var form = $(form);

        // let's select and cache all the fields
        var inputs = form.find("input, select, button, textarea");

        // serialize the data in the form
        var serializedData = form.serialize();

        // let's disable the inputs for the duration of the ajax request
        inputs.prop("disabled", true);

        // fire off the request to /form.php

        request = $.ajax({
            url: form.attr("action"),
            type: "post",
            data: serializedData
        });

        // Clear Message
        $('#form_post .form-group').removeClass('has-error');
        $('#form_post .help-block, #form_post .alert').remove();

        // callback handler that will be called on success
        request.done(function (response, textStatus, jqXHR) {
            var result = $.parseJSON(response);
            if(result.error) {
                toastr.error("Something error. Please check.");
                if(result.error.seo){
                    $('#form_post input[name=seo]').parent().addClass('has-error');
                    $('#form_post input[name=seo]').after('<span id="seo-error" class="help-block">' + result.error.seo + '</span>');
                }
            } else {
                if(result.success) {
                    toastr.success(result.msg);
                    setTimeout(function(){ window.location.href = full_url+'/admin/slider'; }, 1500);
                } else {
                    toastr.warning(result.msg);
                }
            }
        });

        // callback handler that will be called on failure
        request.fail(function (jqXHR, textStatus, errorThrown) {
            // log the error to the console
            toastr.error("The following error occured: " + textStatus, errorThrown);
        });

        // callback handler that will be called regardless
        // if the request failed or succeeded
        request.always(function () {
            // reenable the inputs
            inputs.prop("disabled", false);
        });
    }
});
JS;
$this->inlineScript()->captureEnd();
?>