<?php
$title = $this->translate("Sliders Management");
$this->headTitle($title);
?>
<!-- BEGIN SIDEBAR -->
<?php echo $this->partial('backend_sidebar', array('view' => 'slider', 'action' => 'slider')); ?>
<!-- END SIDEBAR -->
<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
    <div class="page-content">
        <!-- BEGIN PAGE BAR -->
        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <a href="<?php echo $this->url('admin') ?>"><?php echo $this->translate("Dashboard") ?></a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <span><?php echo $this->translate("Sliders") ?></span>
                </li>
            </ul>
        </div>
        <!-- END PAGE BAR -->

        <div class="row">
            <div class="col-md-12">
                <div class="portlet light portlet-fit portlet-datatable bordered">
                    <div class="portlet-title">
                        <div class="caption font-dark">
                            <i class="icon-picture font-dark"></i>
                            <span class="caption-subject bold uppercase"> <?php echo $title ?></span>
                        </div>
                        <div class="actions">
                            <div class="btn-group btn-group-devided" data-toggle="buttons">
                                <a href="javascript:;" onclick="window.location.href='<?php echo $this->url('admin/slider', array('action' => 'add')) ?>'" class="btn btn-transparent green btn-outline btn-circle btn-sm active"> <?php echo $this->translate("Add New") ?>
                                    <i class="fa fa-plus"></i>
                                </a>
                                <a href="javascript:;" onclick="window.history.back()" class="btn btn-transparent grey-salsa btn-outline btn-circle btn-sm"> <?php echo $this->translate("Back") ?>
                                    <i class="fa fa-history"></i>
                                </a>
                            </div>
                            <div class="btn-group">
                                <a class="btn red btn-outline btn-circle" href="javascript:;" data-toggle="dropdown">
                                    <i class="fa fa-share"></i>
                                    <span class="hidden-xs"> <?php echo $this->translate("Tools") ?> </span>
                                    <i class="fa fa-angle-down"></i>
                                </a>
                                <ul class="dropdown-menu pull-right" id="table_slider_tools">
                                    <li>
                                        <a href="javascript:;" data-action="0" class="tool-action">
                                            <i class="icon-wrench"></i> <?php echo $this->translate("Edit") ?></a>
                                    </li>
                                    <li>
                                        <a href="javascript:;" data-action="1" class="tool-action">
                                            <i class="icon-check"></i> <?php echo $this->translate("Active") ?></a>
                                    </li>
                                    <li>
                                        <a href="javascript:;" data-action="2" class="tool-action">
                                            <i class="icon-close"></i> <?php echo $this->translate("Deactive") ?></a>
                                    </li>
                                    <li>
                                        <a href="javascript:;" data-action="3" class="tool-action">
                                            <i class="icon-trash"></i> <?php echo $this->translate("Trash") ?></a>
                                    </li>
                                    <li class="divider"> </li>
                                    <li>
                                        <a href="javascript:;" data-action="4" class="tool-action">
                                            <i class="icon-refresh"></i> <?php echo $this->translate("Reload") ?></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <table class="table table-striped table-bordered table-hover table-checkable" id="table_slider">
                            <thead>
                                <tr>
                                    <th>
                                        <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                            <input type="checkbox" class="group-checkable" data-set="#table_slider .checkboxes" />
                                            <span></span>
                                        </label>
                                    </th>
                                    <th> <?php echo $this->translate("Name") ?> </th>
                                    <th> <?php echo $this->translate("Image") ?> </th>
                                    <th> <?php echo $this->translate("Date") ?> </th>
                                    <th> <?php echo $this->translate("Location") ?></th>
                                    <th> <?php echo $this->translate("Status") ?> </th>
                                    <th> <?php echo $this->translate("Actions") ?> </th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php if(count($this->sliders) > 0): ?>
                                <?php foreach ($this->sliders as $key => $slider): ?>
                                <tr class="odd gradeX">
                                    <td>
                                        <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                            <input type="checkbox" class="checkboxes" value="<?php echo $slider->getId() ?>" />
                                            <span></span>
                                        </label>
                                    </td>
                                    <td><a href="<?php echo $this->url("admin/slider", array("action" => "edit", "id" => $slider->getId())) ?>">
                                        <?php echo $slider->getName()?></a></td>
                                    <td>
                                        <img height="50px" src="<?php echo $this->basePath('data/image/'.$slider->getUrl()) ?>"/>
                                    </td>
                                    <td><?php echo date("d-m-Y", strtotime($slider->getDateAdded())); ?></td>
                                    <td>
                                        <?php
                                            switch ($slider->getType()){
                                                case 0;
                                                    echo $this->translate("Home Page");
                                                break;

                                                case 1;
                                                    echo $this->translate("Credit Card");
                                                break;
                                            }
                                        ?>
                                    </td>
                                    <td>
                                    <?php
                                    switch ($slider->getStatus()){
                                        case 1;
                                            echo '<span class="label label-sm label-success"> '.$this->translate("Active").' </span>';
                                        break;

                                        case 2;
                                            echo '<span class="label label-sm label-info"> '.$this->translate("Pending").' </span>';
                                        break;

                                        case 3;
                                            echo '<span class="label label-sm label-warning"> '.$this->translate("Suspended").' </span>';
                                        break;

                                        default:
                                            echo '<span class="label label-sm label-danger"> '.$this->translate("Deactive").' </span>';
                                        break;
                                    }
                                    ?>
                                    </td>
                                    <td><a class="btn red-thunderbird btn-xs" href="<?php echo $this->url("admin/slider", array("action" => "edit", "id" => $slider->getId())) ?>"><i class="fa fa-pencil"></i> <?php echo $this->translate("Edit") ?></a></td>
                                </tr>
                                <?php endforeach;?>
                                <?php endif;?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END CONTENT -->
<?php
$offStyle = 12;
$offScript = 10;
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/datatables/datatables.min.css'));
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css'));
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/js/datatable.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/datatables/datatables.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js'));
$this->inlineScript()->offsetSetFile(100, $this->basePath('assets/js/custom_functions.js'));
$this->inlineScript()->captureStart();
echo <<<JS
jQuery.extend( jQuery.fn.dataTableExt.oSort, {
    "date-sg-pre": function ( a ) {
        var sgDatea = a.split('-');
        return (sgDatea[2] + sgDatea[1] + sgDatea[0] ) * 1;
    },

    "date-sg-asc": function ( a, b ) {
        return ((a < b) ? -1 : ((a > b) ? 1 : 0));
    },

    "date-sg-desc": function ( a, b ) {
        return ((a < b) ? 1 : ((a > b) ? -1 : 0));
    }
});

jQuery(document).ready(function() {
    var table = $('#table_slider');
    table.dataTable({
        // Internationalisation. For more info refer to http://datatables.net/manual/i18n
        "language": {
            "aria": {
                "sortAscending": ": activate to sort column ascending",
                "sortDescending": ": activate to sort column descending"
            },
            "emptyTable": "No data available in table",
            "info": "Showing _START_ to _END_ of _TOTAL_ records",
            "infoEmpty": "No records found",
            "infoFiltered": "(filtered1 from _MAX_ total records)",
            "lengthMenu": "Show _MENU_",
            "search": "Search:",
            "zeroRecords": "No matching records found",
            "paginate": {
                "previous":"Prev",
                "next": "Next",
                "last": "Last",
                "first": "First"
            }
        },

        buttons: [
            {
                text: 'Edit',
                className: 'btn default',
                action: function ( e, dt, node, config ) {
                    var selectedIds = [];
                    $("input[class=checkboxes]:checked").each(function() {
                        selectedIds.push($(this).val());
                    });
                    if(selectedIds.length > 0) {
                        if(selectedIds.length == 1) {
                            toastr.success("Loading...");
                            setTimeout(function(){ window.location.href = full_url + "/admin/slider/edit/" + selectedIds[0]; }, 500);
                        } else {
                            toastr.warning("You can't select multi rows.");
                        }
                    } else {
                        toastr.warning("No row selected in table.");
                    }
                }
            },
            {
                text: 'Active',
                className: 'btn default',
                action: function ( e, dt, node, config ) {
                    var selectedIds = [];
                    $("input[class=checkboxes]:checked").each(function() {
                        selectedIds.push($(this).val());
                    });
                    if(selectedIds.length > 0) {
                        $.ajax({
                            type: "POST",
                            url: full_url+"/admin/slider/set-status",
                            data: {ids: selectedIds, action: 'active'},
                            dataType: 'json',
                            beforeSend: function() {
                                App.blockUI({boxed: true});
                            },
                            success: function(itemJson) {
                                App.unblockUI();
                                if(itemJson['success']) {
                                    toastr.success(itemJson.msg);
                                    setTimeout(function(){ window.location.reload(); }, 1500);
                                } else {
                                    toastr.error(itemJson.msg);
                                }
                            },
                            error : function(xhr, status){
                                console.log(status);
                            },
                        });
                    } else {
                        toastr.warning("No row checked in table.");
                    }
                }
            },
            {
                text: 'Deactive',
                className: 'btn default',
                action: function ( e, dt, node, config ) {
                    var selectedIds = [];
                    $("input[class=checkboxes]:checked").each(function() {
                        selectedIds.push($(this).val());
                    });
                    if(selectedIds.length > 0) {
                        $.ajax({
                            type: "POST",
                            url: full_url+"/admin/slider/set-status",
                            data: {ids: selectedIds, action: 'deactive'},
                            dataType: 'json',
                            beforeSend: function() {
                                App.blockUI({boxed: true});
                            },
                            success: function(itemJson) {
                                App.unblockUI();
                                if(itemJson['success']) {
                                    toastr.success(itemJson.msg);
                                    setTimeout(function(){ window.location.reload(); }, 1500);
                                } else {
                                    toastr.error(itemJson.msg);
                                }
                            },
                            error : function(xhr, status){
                                console.log(status);
                            },
                        });
                    } else {
                        toastr.warning("No row checked in table.");
                    }
                }
            },
            {
                text: 'Trash',
                className: 'btn default',
                action: function ( e, dt, node, config ) {
                    var selectedIds = [];
                    $("input[class=checkboxes]:checked").each(function() {
                        selectedIds.push($(this).val());
                    });
                    if(selectedIds.length > 0) {
                        $.ajax({
                            type: "POST",
                            url: full_url+"/admin/slider/set-status",
                            data: {ids: selectedIds, action: 'trash'},
                            dataType: 'json',
                            beforeSend: function() {
                                App.blockUI({boxed: true});
                            },
                            success: function(itemJson) {
                                App.unblockUI();
                                if(itemJson['success']) {
                                    toastr.success(itemJson.msg);
                                    setTimeout(function(){ window.location.reload(); }, 1500);
                                } else {
                                    toastr.error(itemJson.msg);
                                }
                            },
                            error : function(xhr, status){
                                console.log(status);
                            },
                        });
                    } else {
                        toastr.warning("No row checked in table.");
                    }
                }
            },
            {
                text: 'Reload',
                className: 'btn default',
                action: function ( e, dt, node, config ) {
                    window.location.reload();
                }
            }
        ],

        // setup responsive extension: http://datatables.net/extensions/responsive/
        responsive: true,

        "columnDefs": [ {
            "targets": 0,
            "orderable": false,
            "searchable": false
        }],

        "lengthMenu": [
            [25, 50, 100, -1],
            [25, 50, 100, "All"] // change per slider values here
        ],
        // set the initial value
        "sliderLength": 25,
        "pagingType": "bootstrap_full_number",
        "columnDefs": [
            {"orderable": false,"targets": [0,5]},
            {"type": "date-sg", "targets": 3 }
        ],
        "order": [
            [3, "desc"]
        ] // set first column as a default sort by asc
    });

    var tableWrapper = jQuery('#table_slider_wrapper');
    table.find('.group-checkable').change(function () {
        var set = jQuery(this).attr("data-set");
        var checked = jQuery(this).is(":checked");
        jQuery(set).each(function () {
            if (checked) {
                $(this).prop("checked", true);
                $(this).parents('tr').addClass("active");
            } else {
                $(this).prop("checked", false);
                $(this).parents('tr').removeClass("active");
            }
        });
    });

    table.on('change', 'tbody tr .checkboxes', function () {
        $(this).parents('tr').toggleClass("active");
    });

    // handle datatable custom tools
    $('#table_slider_tools > li > a.tool-action').on('click', function() {
        var action = $(this).attr('data-action');
        table.DataTable().button(action).trigger();
    });
});
JS;
$this->inlineScript()->captureEnd();
?>