<?php
$title = "Latest News";
$this->headTitle($title);
?>
<?php if(count($this->featured_posts) > 0): ?>
<div class="blog-featured">
    <div class="container">
        <?php
        $featured = array();
        foreach ($this->featured_posts as $post) {
            $featured_image_src = 'data/image/'.$post->getFeaturedImage();
            if(file_exists($featured_image_src)) {
                $image_src = $featured_image_src;
            } else {
                $image_src = 'data/image/no-image-256.png';
            }
            $featured[] = array(
                'title' => $post->getPostTitle(),
                'link'  => $this->url("blog", array("action" => "view", "id" => $post->getId(), "seo" => $post->getSeo())),
                'image' => $image_src,
            );
        }
        ?>
        <div class="row">
            <div class="col-md-12">
                <div class="left">
                    <div class="image-holder">
                        <a href="<?php echo $featured[0]['link']; ?>">
                            <img src="<?php echo $this->basePath($featured[0]['image']) ?>" />
                            <div class="caption"><?php echo $featured[0]['title']; ?></div>
                        </a>
                    </div>
                </div>
                <div class="right">
                    <div class="image-holder" style="margin-bottom: 21px;">
                        <a href="<?php echo $featured[1]['link']; ?>">
                            <img src="<?php echo $this->basePath($featured[1]['image']) ?>" />
                            <div class="caption"><?php echo $featured[1]['title']; ?></div>
                        </a>
                    </div>
                    <div class="image-holder">
                        <a href="<?php echo $featured[2]['link']; ?>">
                            <img src="<?php echo $this->basePath($featured[2]['image']) ?>" />
                            <div class="caption"><?php echo $featured[2]['title']; ?></div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
<div class="container">
    <div class="page-content-inner">
        <div class="blog-page blog-content">
            <div class="row">
                <div class="col-md-8">
                    <div class="blog-single-content blog-container">
                        <h1><?php echo $title ?></h1>
                        <?php 
                        if(count($this->posts) > 0) {
                            foreach ($this->posts as $post) {
                                $featured_image_src = 'data/image/l_'.$post->getFeaturedImage();
                                if(file_exists($featured_image_src)) {
                                    $image_thumb_src = $featured_image_src;
                                } else {
                                    $image_thumb_src = 'data/image/no-image-256.png';
                                }
                                ?>
                                <div class="row blog">
                                    <div class="col-md-3 col-sm-4">
                                        <div class="blog-img-thumb">
                                            <a href="<?php echo $this->url("blog", array("action" => "view", "id" => $post->getId(), "seo" => $post->getSeo())) ?>"><img class="img-responsive" src="<?php echo $this->basePath($image_thumb_src) ?>" /></a>
                                        </div>
                                    </div>
                                    <div class="col-md-7 col-sm-8">
                                        <div class="blog-post-content">
                                            <h2 class="blog-title blog-post-title">
                                                <a href="<?php echo $this->url("blog", array("action" => "view", "id" => $post->getId(), "seo" => $post->getSeo())) ?>"><?php echo $post->getPostTitle() ?></a>
                                            </h2>
                                            <?php if($post->getPostExcerpt()): ?>
                                            <?php
                                            $introtext = $post->getPostExcerpt();
                                            if(strlen($introtext) > 100) {
                                                // truncate string
                                                $stringCut = substr($introtext, 0, 100);
                                                
                                                // make sure it ends in a word so assassinate doesn't become ass...
                                                $introtext = substr($stringCut, 0, strrpos($stringCut, ' ')).'... ';
                                                
                                                // read more
                                                $introtext .= '<a href="'.$this->url("blog", array("action" => "view", "id" => $post->getId(), "seo" => $post->getSeo())).'">'.$this->translate("Continue Reading").'</a>';
                                            }
                                            ?>
                                            <div class="excerpt hidden-xs">
                                                <p class="blog-post-desc"><?php echo $introtext; ?></p>
                                            </div>
                                            <?php endif;?>
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <ul class="blog-post-info">
                                            <li>
                                                <i class="icon-calendar"></i> <?php echo date("M d, Y", strtotime($post->getPostDate())) ?>
                                            </li>
                                            <?php if($post->getCategoryId() > 0): ?>
                                            <li>
                                                <i class="icon-tag"></i> <?php echo $this->category(array("id" => $post->getCategoryId()))->getName() ?>
                                            </li>
                                            <?php endif; ?>
                                        </ul>
                                    </div>
                                </div>
                                <?php
                                }
                                ?>
                            <div class="row">
                                <div class="col-md-12"><?php echo $this->pagination; ?></div>
                            </div>
                            <?php
                            }
                            ?>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="blog-single-sidebar blog-container">
                        <div class="blog-single-sidebar-popular widget">
                            <h3><img src="<?php echo $this->basePath("assets/img/icons/popular.png") ?>" /><?php echo $this->translate("Popular Post This Week") ?></h3>
                            <ul>
                            <?php
                            foreach ($this->populars as $post) {
                                ?>
                                <li>
                                    <a href="<?php echo $this->url("blog", array("action" => "view", "id" => $post->getId(), "seo" => $post->getSeo())) ?>"><?php echo $post->getPostTitle() ?></a>
                                    <div class="hits"><i class="icon-eye"></i> <?php echo number_format($post->getHits()); ?></div>
                                </li>
                                <?php
                            }
                            ?>
                            </ul>
                        </div>
                        
                        <div class="blog-single-sidebar-products widget hide">
                                                <div class="row">
                                                    <div class="col-md-12"><h3><?php echo $this->translate("Find the Best Loans, Insurance & Credit Cards") ?></h3></div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-md-12"><label><?php echo $this->translate("What are you looking for?") ?></label></div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-md-12">
                                                        <select class="form-control" name="products">
                                                            <option value="<?php echo $this->url("personal_loan") ?>"><?php echo $this->translate("Business Term Loan") ?></option>
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-md-12">
                                                        <a href="javascript:;" class="btn dark btn-block" onclick="redirect(this)"><?php echo $this->translate("Get Started") ?> <i class="fa fa-angle-right"></i></a>
                                                    </div>
                                                </div>
                        </div>
                        <div class="blog-single-sidebar-newsletter widget">
                            <div class="row">
                                <div class="col-md-12"><h3><?php echo $this->translate("Get Our Weekly Newsletter") ?></h3></div>
                            </div>
                            <div class="row">
                                <div class="col-md-12"><h4><?php echo $this->translate("We value your privacy. We never share your email with 3rd parties. Unsubscribe at any time.") ?></h4></div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <input type="text" name="email_newsletter" class="form-control" />
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <a href="javascript:;" class="btn dark btn-block" onclick="email_newsletter(this)"><?php echo $this->translate("Subscribe") ?> <i class="fa fa-send"></i></a>
                                </div>
                            </div>
                        </div> 
                        <?php if(count($this->infographics) > 0): ?>
                        <div class="blog-single-sidebar-infographic widget">
                            <h3><img src="<?php echo $this->basePath("assets/img/icons/infographic.png") ?>" /><?php echo $this->translate("Infographic") ?></h3>
                             <div class="carousel">
                                <?php
                                foreach ($this->infographics as $key => $infographic) {
                                    if($infographic->getImage()) {
                                        $image = $this->basePath("data/image/".$infographic->getImage());
                                        ?>
                                        <div class="item<?php if($key == 0) echo ' active'; ?>">
                                            <a href="<?php echo $this->url("blog", array("action" => "download-attachment", "id" => $infographic->getId())) ?>" target="_blank"><img src="<?php echo $image ?>" /></a>
                                            <div class="carousel-caption">
                                                <?php echo $infographic->getTitle(); ?>
                                            </div>
                                        </div>
                                        <?php
                                    }
                                }
                                ?>
                                </div>
                        </div>
                        <?php endif; ?>     
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php
$offStyle = 12;
$offScript = 10;
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/css/blog.css'));
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/owl-carousel/owl.carousel.css'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/owl-carousel/owl.carousel.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, '//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5301c95928ec6521');
$this->inlineScript()->offsetSetFile(100, $this->basePath('assets/js/custom.js')); 
$this->inlineScript()->captureStart();
echo <<<JS
//$('.carousel').carousel();

$('.carousel').owlCarousel({
	items: 1,
	autoPlay: 5000,
	navigation: true,
	navigationText: ['<i class="fa fa-chevron-left"></i>', '<i class="fa fa-chevron-right"></i>'],
	pagination: true
});

function redirect(button) {
    var route = $('select[name=products]').val();
    window.location.href = full_url + '/' + route;
}

function email_newsletter(button) {
    toastr.info("Comming soon");
}
JS;
$this->inlineScript()->captureEnd();
?>