<?php
$title = $post->getPostTitle();
$this->headTitle($title);
?>
<div class="page-title">
    <?php
    if(file_exists('assets/img/bg-'.$post->getSeo().'.png')) {
        $bg_src = 'assets/img/bg-'.$post->getSeo().'.png';
    } else {
        $bg_src = 'assets/img/bg-about-us.png';
    }
    ?>
    <div class="image-title"><img src="<?php echo $this->basePath($bg_src) ?>" class="img-responsive"></div>
    <div class="container">
        <h2><?php echo $title ?></h2>
    </div>
</div>
<?php
if($post->getFeaturedImage()) {
    $class1 = "col-md-7";
    $class2 = "col-md-5";
} else {
    $class1 = "col-md-12";
    $class2 = "col-md-12";
}
?>
<div class="container">
    <div class="page-content-inner">
        <div class="blog-page blog-content">
            <div class="row">
                <div class="<?php echo $class1 ?>">
                    <div class="blog-single-content blog-container">
                        <?php echo $post->getPostContent() ?>
                    </div>
                </div>
                <div class="<?php echo $class2 ?>">
                    <?php if($post->getFeaturedImage()): ?>
                    <img src="<?php echo $this->basePath('data/image/'.$post->getFeaturedImage()) ?>" class="img-responsive img-centre" />
                    <?php endif; ?>
                    <ul class="stay-connected">
                        <li><?php echo $this->translate("Stay Connected:") ?></li>
                        <?php if($this->setting()->facebook_link): ?>
                        <li class="facebook"><a href="<?php echo $this->setting()->facebook_link; ?>"><i class="fa fa-facebook"></i></a></li>
                        <?php endif; ?>
                        <?php if($this->setting()->twitter_link): ?>
                        <li class="twitter"><a href="<?php echo $this->setting()->twitter_link; ?>"><i class="fa fa-twitter"></i></a></li>
                        <?php endif; ?>
                        <?php if($this->setting()->linkedin_link): ?>
                        <li class="linkedin"><a href="<?php echo $this->setting()->linkedin_link; ?>"><i class="fa fa-linkedin"></i></a></li>
                        <?php endif; ?>
                        <?php if($this->setting()->instagram_link): ?>
                        <li class="instagram"><a href="<?php echo $this->setting()->instagram_link; ?>"><i class="fa fa-instagram"></i></a></li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="brand">
                        <?php
                        $product_image = \Zend\Json\Json::decode($widget_1->getContent());
                        if(count($product_image) > 0) {
                            foreach ($product_image as $image) {
                                ?>
                                <div class="item"><img src="<?php echo $this->basePath('data/brand/'.$image) ?>" /></div>
                                <?php
                            }
                        }
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="about-middle">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h3><?php echo $this->translate("Make Better Financial Decisions"); ?></h3>
                <p>Subscribe to our free weekly newsletter for tips on how to save money in the world's most expensive city</p>
                <div class="subscribe-form">
                    <form action="<?php echo $this->url("frontend_user", array("action" => "add-subscribe")) ?>" method="POST" id="form_subscribe">
                        <div class="form-group" style="margin-bottom: 50px;">
                            <div class="input-group">
                                <input type="text" name="subscribe_email" placeholder="<?php echo $this->translate("Your Email Address") ?>" class="form-control">
                                <span class="input-group-btn">
                                    <button class="btn btn-subscribe" type="submit"><?php echo $this->translate("Subscribe") ?></button>
                                </span>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="md-checkbox-list">
                                <div class="md-checkbox">
                                    <input type="checkbox" name="agree" id="checkbox1" class="md-check" value="1">
                                    <label for="checkbox1">
                                        <span></span>
                                        <span class="check"></span>
                                        <span class="box"></span> I agree to the terms and conditions and agree to receive email communications from Moneycompare.com.sg according to the privacy policy.
                                    </label>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-md-4">
                <img src="<?php echo $this->basePath("data/image/icon-about-us-middle.png") ?>" class="img-responsive" />
            </div>
        </div>
    </div>
</div>
<div class="about-bottom">
    <div class="container">
        <h2><?php echo $this->translate("Latest News") ?></h2>
		<div class="news-content">
				<?php
                if(count($this->posts) > 0) {
                    foreach ($this->posts as $post) {
                        ?>
                        <div class="item">
        					<div class="item-news">
        						<div class="image">
        							<a href="<?php echo $this->url("blog", array("action" => "view", "id" => $post->getId(), "seo" => $post->getSeo())) ?>"><img src="<?php echo $this->basePath('assets/img/news-1.jpg') ?>" title="" alt=""></a>
        						</div>

        						<div class="caption">
        							<h4><?php echo $post->getPostTitle() ?></h4>
        							<span class="date-news"><i class="fa fa-calendar"></i> May 22, 2016</span>
        							<?php
                                            $introtext = $post->getPostExcerpt();
                                            if(strlen($introtext) > 150) {
                                                // truncate string
                                                $stringCut = substr($introtext, 0, 150);

                                                // make sure it ends in a word so assassinate doesn't become ass...
                                                $introtext = substr($stringCut, 0, strrpos($stringCut, ' ')).'... ';
                                            }
                                            ?>
                                    <p><?php echo $introtext; ?></p>
        						</div>
        						<a href="<?php echo $this->url("blog", array("action" => "view", "id" => $post->getId(), "seo" => $post->getSeo())) ?>" class="uppercase"><?php echo $this->translate("Continue Reading") ?>...</a>
        					</div>
        				</div>
                        <?php
                    }
                }
                ?>
			</div>
        <div class="text-center"><a href="<?php echo $this->url("blog") ?>" class="btn btn-secondary"><?php echo $this->translate("View All News") ?></a></div>
    </div>
</div>
<?php
$offStyle = 12;
$offScript = 10;
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/owl-carousel/owl.carousel.css'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/owl-carousel/owl.carousel.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/jquery-validation/js/jquery.validate.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/jquery-validation/js/additional-methods.min.js'));
$this->inlineScript()->offsetSetFile(100, $this->basePath('assets/js/custom.js'));
$this->inlineScript()->offsetSetFile(101, $this->basePath('assets/js/news-article-slider.js'));
$this->inlineScript()->captureStart();
echo <<<JS
var form_subscribe = $('#form_subscribe');
form_subscribe.validate({
errorElement: 'span', //default input error message container
errorClass: 'help-block', // default input error message class
focusInvalid: false, // do not focus the last invalid input
ignore: "",
rules: {
  subscribe_email: {
    required: true,
    email: true
  }
},

highlight: function(element) { // hightlight error inputs
  $(element)
        .closest('.form-group').addClass('has-error'); // set error class to the control group
      },

      success: function(label) {
        label.closest('.form-group').removeClass('has-error');
        label.remove();
      },

      errorPlacement: function(error, element) {
    //error.insertAfter(element);
  },

  submitHandler: function (form) {
    // setup some local variables
    var form = $(form);

    // let's select and cache all the fields
    var inputs = form.find("input, select, button, textarea");

    // serialize the data in the form
    var serializedData = form.serialize();

    // let's disable the inputs for the duration of the ajax request
    inputs.prop("disabled", true);

    // fire off the request to /form.php

    request = $.ajax({
      url: form.attr("action"),
      type: "post",
      data: serializedData
    });

    // Clear Message
    $('#form_subscribe .form-group').removeClass('has-error');
    $('#form_subscribe .help-block, #form_subscribe .alert').remove();

    // callback handler that will be called on success
    request.done(function (response, textStatus, jqXHR) {
      var result = $.parseJSON(response);
      if(result.success) {
        toastr.success(result.msg);
        form_subscribe.trigger("reset");
      } else {
        toastr.warning(result.msg);
      }
    });

    // callback handler that will be called on failure
    request.fail(function (jqXHR, textStatus, errorThrown) {
        // log the error to the console
        toastr.error("The following error occured: " + textStatus, errorThrown);
      });

    // callback handler that will be called regardless
    // if the request failed or succeeded
    request.always(function () {
        // reenable the inputs
        inputs.prop("disabled", false);
      });
  }
});
JS;
$this->inlineScript()->captureEnd();
?>