<?php
$title = "Business Loan Calculator";
$this->headTitle($title);
?>
<div id="page-title"><h2><?php echo $title ?></h2></div>
<div class="container">
    <div class="page-content-inner">
        <div class="blog-page blog-content">
            <div class="row">
                <div class="col-md-12">
                    <div class="blog-single-content blog-container page-calculator">
                        <?php echo $this->partial('business_loan_calculator'); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
