<?php
$title = "Page Not Found";
$this->headTitle($title);
?>
<div class="container">
    <div class="page-content-inner">
        <div class="blog-page blog-content">
            <div class="row">
                <div class="col-md-12">
                    <div class="blog-single-content blog-container">
                        <img src="<?php echo $this->basePath("assets/img/".$this->value.".gif") ?>" class="img-responsive" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
