<?php
$title = "FAQ for Residential Loan";
$this->headTitle($title);
?>
<div id="page-title"><h2><?php echo $title ?></h2></div>
<div class="container">
    <div class="page-content-inner">
        <div class="blog-page blog-content">
            <div class="row">
                <div class="col-md-12">
                    <div class="blog-single-content blog-container">
                        <div class="content-faq">
                                <?php 
                                $_faq = \Zend\Json\Json::decode($this->faq->getQuestion());
                                if(count($_faq) > 0) {
                                    $k = 1;
                                    foreach ($_faq as $key => $value) {
                                        ?>
                                        <div class="faq-panel">
                                          <div role="tab" id="heading1">
                                            <h4 class="faq-panel-header"><a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse<?php echo $k?>" aria-expanded="true" aria-controls="collapse1"> <i class="fa fa-caret-down" aria-hidden="true"></i> <i class="fa fa-caret-up" aria-hidden="true"></i> <span><?php echo $value->question ?></span> </a></h4>
                                          </div>
                                          <div id="collapse<?php echo $k?>" class="collapse" role="tabpanel" aria-labelledby="heading1">
                                            <div class="faq-panel-body">
                                              <?php echo $value->answer ?>
                                            </div>
                                          </div>
                                        </div>
                                        <?php 
                                        $k++;   
                                    }
                                }
                                ?>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

