<?php 
$title = $this->category->getName();
$this->headTitle($title);
$_text_completed = $this->translate("When do you intend to select your unit / make an offer");
$_text_under_construction = $this->translate("Do you qualify for a Home Loan based on the Home Loan Eligibility (HLE) Letter from HDB");
?>
<div class="title-property">
    <div class="container">
        <h2><?php echo $title ?></h2>
        <div class="portlet-head">
            <div class="row">
                <div class="col-md-12">
                    <div class="stepproperty">
                        <div class="stepproperty-row">
                            <div class="stepproperty-step<?php if($this->step == 1 || $this->step == 2 || $this->step == 3 || $this->step == 4) echo ' active'; ?>">
                                <div class="stepproperty-circle">01</div>
                                <p><?php echo $this->translate("Property Information") ?></p>
                            </div>
                            
                            <div class="line-stepproperty line-stepproperty1"></div>
                            <div class="stepproperty-step<?php if($this->step == 2 || $this->step == 3 || $this->step == 4) echo ' active'; ?>">
                                <div class="stepproperty-circle">02</div>
                                <p><?php echo $this->translate("Compare Loan") ?></p>
                            </div>
                            
                            <div class="line-stepproperty line-stepproperty2"></div>
                            <div class="stepproperty-step<?php if($this->step == 4) echo ' active'; ?>">
                                <div class="stepproperty-circle">03</div>
                                <p><?php echo $this->translate("Loan Application") ?></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>   
    </div>
</div>
<div class="container">
    <div class="page-content-inner">
        <div class="row">
            <div class="col-md-12">
                <div class="portlet light portlet-fit portlet-form no-shadow">
                    <div class="portlet-body form property-loan">
                        <?php 
                        $step = $this->step ? $this->step : 1;
                        ?>
                        <input type="hidden" name="seo" value="<?php echo $this->seo; ?>" />
                        <?php echo $this->partial('property_loan_step_'.$step); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php if($this->step == 0): ?>
<div id="popup">
	<div class="where-you-go">
		<a href="javascript:;" class="popup_close"><i class="fa fa-close"></i></a>
        <p><?php echo $this->translate("Do you like to use our <strong>All Mortgage Assistant</strong> for a more precise rates comparison ?") ?></p>
        <div class="actions">
            <a href="javascript:;" onclick="yes()" class="btn btn-yes"><?php echo $this->translate("Yes"); ?></a>
            <a href="javascript:;" onclick="no()" class="btn btn-no"><?php echo $this->translate("No"); ?></a>
        </div>
    </div>	
</div>
<?php endif; ?>

<?php if($this->step == 3): ?>
<section class="selectlist"> 
    <div class="container" id="selected-holder">
        <div class="row compare-row" style="display: none;">
            <div class="col-md-4">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="shortlist-info-container">
                            <div class="shortlist-info" id="select-title"><span>0</span> <?php echo $this->translate("Shortlisted Home Loan") ?></div>
                            <p><?php echo $this->translate("Select up to 3 banks for comparison") ?></p>
                            <p><?php echo $this->translate("Next Step - Find out more about this Home Loan Package and how to apply from a MoneyCompare Mortgage Specialist") ?></p>
                            <a class="clear-shortlist" href="javascript:;" onclick="Loan.clear_select(this)"><i class="fa fa-times-circle"></i> <?php echo $this->translate("Clear Shortlist") ?></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6" id="select-holder"></div>
            <div class="col-md-2">
                <div class="row">
                    <a class="btn blue btn-lg text-uppercase fancybox-button" href="#compare" onclick="Loan.popup()"><?php echo $this->translate("Compare Now") ?></a>
                </div>
            </div>
        </div>
        <div class="compare-arrow"><a href="javascript:;" onclick="Loan.shortlist2(this)"><i class="fa fa-angle-double-down"></i></a></div>
    </div>
</section>
<?php endif;?>
<?php
$notify = \Zend\Json\Json::decode($this->setting()->notify);
if(count($notify) > 0) {
    echo '<script type="text/javascript">';
    $time_out = 2500;
    foreach ($notify as $value) {
        echo 'setTimeout(function(){
                $.bootstrapGrowl("'.$value.'", {
                    ele: "body",
                    type: "info",
                    offset: {
                        from: "bottom",
                        amount: 20
                    },
                    align: "right",
                    width: 250,
                    delay: 10000,
                    allow_dismiss: true,
                    stackup_spacing: 10
                });
            }, '.$time_out.');';
        $time_out = $time_out + 500;
    }
    echo '</script>';
}

$offStyle = 12;
$offScript = 10;
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/bootstrap-growl/jquery.bootstrap-growl.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/jquery-validation/js/jquery.validate.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/jquery-validation/js/additional-methods.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/js/jquery.popupoverlay.js'));
$this->inlineScript()->captureStart();
if($this->step == 0) {
echo <<<JS
$(document).ready(function() {
    $('#popup').popup({
        autoopen : true,
        scrolllock: true,
        escape: false,
        blur: false
    });
});

function yes() {
    var seo = $("input[name=seo]").val();
    $.ajax({
        type: "POST",
        url: full_url + "/loan-application/select-yes",
        data: {seo: seo},
        dataType: 'json',
        success: function(itemJson) {
            if(itemJson.redirect) window.location.href = itemJson.redirect; 
        },
        error : function(xhr, status){
            console.log(status);
        },
    });
}

function no() {
    var seo = $("input[name=seo]").val();
    $.ajax({
        type: "POST",
        url: full_url + "/loan-application/select-no",
        data: {seo: seo},
        dataType: 'json',
        success: function(itemJson) {
            if(itemJson.redirect) window.location.href = itemJson.redirect; 
        },
        error : function(xhr, status){
            console.log(status);
        },
    });
}
JS;
} 
$this->inlineScript()->captureEnd();

?>