<?php
$title = "Successful Home Loan";
$this->headTitle($title);
?>
<div id="page-title">
    <h2><?php echo $title; ?></h2>
</div>

<div id="content">
    <div class="container">
    <div class="row">
      <div class="thanks-apply">
        <img src="<?php echo $this->basePath('assets/img/thank.png');?>" title="" alt="" />
        <h3><?php echo $this->translate("Thanks you for your application") ?></h3>
        <p><?php echo $this->translate("Our team will contact within 24 hours to help you go through all the procedure") ?></p>
      </div>
    </div>
    </div>
</div>
