<?php
	$features=json_decode($this->loan->getFeautures(),true);
?>
<body>
        <div id="header" class="container-fluid">
            <nav class="navbar navbar-default">
                <div class="container">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="user/auth">
                            <img width="63%" src="/data/company/logo.png" alt="logo" class="logo-default">
                        </a>
                    </div>
                     <ul id="signup" class="nav navbar-nav">
                        <li>
                            <a href="#" class="btn btn-warning"><span class="glyphicon glyphicon-user"></span> Sign Up</a>
                        </li>
                    </ul>
                </div>
            </nav>
            <div id="banner" class="col-md-7">
                <img width="100%" src="/assets/img/design/banner.png">
            </div>
            <div class="container title">
                <h1>Get The Best Deals</h1>
                <p>On Your Corporate Financing Needs<p>
                <hr>
            </div>
            <div class="container post">
                <div class="icon-group">
                    <i class="icon_render"></i>
                    <div>Rent</div>
                </div>
                <div class="icon-group">
                    <i class="icon_slaries"></i>
                    <div>Slaries</div>
                </div>
                <div class="icon-group">
                    <i class="icon_tax"></i>
                    <div>Tax</div>
                </div>
                <div class="icon-group">
                    <i class="icon_invoices"></i>
                    <div>Invoices</div>
                </div>
                <div class="icon-group">
                    <i class="icon_vendor"></i>
                    <div>Vendor</div>
                </div>
                <div class="icon-group last">
                    <i class="icon_supplies"></i>
                    <div>Suppliers</div>
                </div>
                <button id="show_button" class="btn btn-warning">
                Click Here To Find Out More &nbsp<span class="button-cricle">+</span>
                </button>
            </div>
            <div class="container">
                <button id="hide_button" class="btn btn-warning center-block">Click Here To Find Out More &nbsp<span class="button-cricle">+</span></button>
            </div>
        </div>
        <div id="content-card" class="container-fluid">
            <div class="row">
                <div class="col-md-5 col-sm-5 col-xs-12 col-md-offset-1">
                    <hr>
                    <h1>Keep your cash for up to <span>90-days</span> paying zero interest</h1>
                    <p>
                        Forget the delays and aggravations that come with traditional small business financing options like having instant access to an interest free small bussiness loan
                    </p>
                    <button class="btn btn-danger">
                Corporated cadit CARDS with this feature now! &nbsp<span class="card-button-cricle">+</span>
                </button>
                </div>
                <div id="card-banner" class="col-md-6 col-sm-6 col-xs-12">
                    <img width="100%" src="/assets/img/design/card_banner.png">
                </div>
            </div>
        </div>
        <div id="features" class="container-fluid">
            <div class="container">
                <div class="row">
                    <h1 class="center-block">Feautures and Security</h1>
                </div>
            </div>
            <div class="container">
                <div class="col-md-4 col-sm-6 features-group">
                    <i class="access"></i>
                    <div class="features-title">
                        <h4><?php echo $features[1]['feauture_title_1']?></h4>
                        <div><?php echo $features[1]['feauture_content_1']?></div>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 features-group">
                    <i class="flexible"></i>
                    <div class="features-title">
                        <h4><?php echo $features[2]['feauture_title_2']?></h4>
                        <div><?php echo $features[2]['feauture_content_2']?></div>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 features-group">
                    <i class="early"></i>
                    <div class="features-title">
                        <h4><?php echo $features[3]['feauture_title_3']?></h4>
                        <div><?php echo $features[3]['feauture_content_3']?></div>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 features-group">
                    <i class="earn"></i>
                    <div class="features-title">
                        <h4><?php echo $features[4]['feauture_title_4']?></h4>
                        <div><?php echo $features[4]['feauture_content_4']?></div>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 features-group">
                    <i class="tax1"></i>
                    <div class="features-title">
                        <h4><?php echo $features[5]['feauture_title_5']?></h4>
                        <div><?php echo $features[5]['feauture_content_5']?></div>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 features-group">
                    <i class="improve"></i>
                    <div class="features-title">
                        <h4><?php echo $features[6]['feauture_title_6']?></h4>
                        <div><?php echo $features[6]['feauture_content_6']?></div>
                    </div>
                </div>
            </div>
        </div>
        <div id="works">
            <div class="container">
                <div class="row">
                    <h1 class="center-block">How it Works</h1>
                </div>
            </div>
            <div class="container" style="margin-top: 6%">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1">
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-md-2 works-group">
                                    <i class="works1"></i>
                                    <div class="works-title">
                                        <span>1</span>
                                    </div>
                                    <div class="works-content">loren Ipsum is simple dummy text of the has been the industry's standard</div>
                                </div>
                                <div class="col-md-1"><hr></div>
                                <div class="col-md-2 works-group">
                                    <i class="works2"></i>
                                    <div class="works-title work-title-sub">
                                        <span>2</span>
                                    </div>
                                    <div class="works-content">loren Ipsum is simple dummy text of the has been the industry's standard</div>
                                </div>
                                <div class="col-md-1"><hr></div>
                                <div class="col-md-2 works-group">
                                    <i class="works3"></i>
                                    <div class="works-title work-title-sub">
                                        <span>3</span>
                                    </div>
                                    <div class="works-content">loren Ipsum is simple dummy text of the has been the industry's standard</div>
                                </div>
                                <div class="col-md-1"><hr></div>
                                <div class="col-md-2 works-group work-title-sub">
                                    <i class="works4"></i>
                                    <div class="works-title">
                                        <span>4</span>
                                    </div>
                                    <div class="works-content">loren Ipsum is simple dummy text of the has been the industry's standard</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="note" class="container-fluid">
            <img width="100%" src="/assets/img/design/Testimonials.png">
            <div>
                <div class="note-content"><?php echo $this->loan->getTestimonialsTitle()?></div>
                <p><?php echo $this->loan->getTestimonialsSign()?></p>
            </div>
        </div>
        <footer class="container-fluid">
            <div class="row">
                <div class="title-footer col-md-12">
                    <div>Make Your First Payment Today
                        <button id="button-title" class="btn btn-warning">
                        Get Started &nbsp;<span class="footer-button-cricle">+</span>
                        </button>
                    </div>
                </div>
            </div>
            <div id="form_payment" class="row">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <form id="question_form" action="<?php echo $this->url("page", array("action" => "post-question")) ?>" class="form-horizontal" id="question_form">
                            <div class="col-md-6">
                                <input type="text" name="name" class="text-input" placeholder="Name">
                                <input type="email" name="email" class="text-input" placeholder="Email">
                                <input type="text" name="phone" class="text-input" placeholder="Phone">
                            </div>
                            <div class="col-md-6">
                                <textarea name="message" class="text-input" style="padding-bottom: 17%;" placeholder="Message"></textarea>
                                <button type="Submit" class="btn btn-danger btn-block button-payment">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-md-12"><hr></div>
            <div id="contact-icon" class="col-md-12">
                <div class="group-contact-icon">
                    <i class="fa fa-facebook" aria-hidden="true"></i>
                </div>
                <div class="group-contact-icon">
                    <i class="fa fa-twitter" aria-hidden="true"></i>
                </div>
                <div class="group-contact-icon">
                    <i class="fa fa-linkedin" aria-hidden="true"></i>
                </div>
                <div class="group-contact-icon">
                    <i class="fa fa-google-plus" aria-hidden="true"></i>
                </div>
            </div>
            <div class="col-md-12" style="text-align: center;">
                <p>copyright 2018 MoneyCompare.SG Pte. Ltd. All rights reserved</p> 
            </div>
        </footer>
        <script type="text/javascript" src="/assets/js/respond.min.js"></script>
        <script type="text/javascript" src="/assets/js/excanvas.min.js"></script>
        <script type="text/javascript" src="/assets/js/jquery.min.js"></script>
        <script type="text/javascript" src="/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="/assets/js/js.cookie.min.js"></script>
        <script type="text/javascript" src="/assets/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js"></script>
        <script type="text/javascript" src="/assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js"></script>
        <script type="text/javascript" src="/assets/js/jquery.blockui.min.js"></script>
        <script type="text/javascript" src="/assets/plugins/jquery-validation/js/jquery.validate.min.js"></script>
        <script type="text/javascript" src="/assets/plugins/jquery-validation/js/additional-methods.min.js"></script>
        <script type="text/javascript" src="/assets/js/user_login.js"></script>
        <script type="text/javascript" src="/assets/js/user_register.js"></script>
        <script type="text/javascript" src="/assets/plugins/owl-carousel/owl.carousel.min.js"></script>
        <script type="text/javascript" src="/assets/plugins/fancybox/source/jquery.fancybox.pack.js"></script>
        <script type="text/javascript" src="/assets/plugins/bootstrap-toastr/toastr.min.js"></script>
        <script type="text/javascript" src="/assets/plugins/icheck/icheck.min.js"></script>
        <script type="text/javascript" src="/assets/plugins/select2/js/select2.full.min.js"></script>
        <script type="text/javascript" src="/assets/plugins/ladda/spin.min.js"></script>
        <script type="text/javascript" src="/assets/plugins/ladda/ladda.min.js"></script>
        <script type="text/javascript" src="/assets/js/app.js"></script>
        <script type="text/javascript" src="/assets/js/layout3.min.js"></script>
        <script type="text/javascript" src="/assets/js/custom4.js"></script>

        <script type="text/javascript">
            var form = $("#question_form");
            form.validate({
                errorElement: "span",
                errorClass: "help-block",
                focusInvalid: false,
                ignore: "",
                rules: {
                    name: {
                        required: true
                    },
                    email: {
                        required: true,
                        email: true
                    },
                    phone: {
                        required: true,
                        number: true
                    },
                    message: {
                        required: true
                    }
                },

                highlight: function(element) {
                    $(element).closest(".form-group").addClass("has-error");
                },

                success: function(label) {
                    label.closest(".form-group").removeClass("has-error");
                    label.remove();
                },

                errorPlacement: function(error, element) {
                    error.insertAfter(element);
                },

                submitHandler: function (form) {
                    var form = $(form);

                    var inputs = form.find("input, select, button, textarea");

                    var serializedData = form.serialize();

                    inputs.prop("disabled", true);
                    request = $.ajax({
                        url: form.attr("action"),
                        type: "post",
                        data: serializedData
                    });

                    $("#question_form .form-group").removeClass("has-error");
                    $("#question_form .help-block, #question_form .alert").remove();

                    request.done(function (response, textStatus, jqXHR) {
                        var result = $.parseJSON(response);
                        if(result.error) {
                            toastr.error("Something error. Please check");
                        } else {
                            if(result.success) {
                                toastr.success(result.msg);
                            } else {
                                toastr.warning(result.msg);
                            }
                        }
                    });

                    request.fail(function (jqXHR, textStatus, errorThrown) {
                        toastr.error("The following error occured: " + textStatus, errorThrown);
                    });

                    request.always(function () {
                        inputs.prop("disabled", false);
                    });
                }
            });
        </script>
</body>