<?php
$title = $this->translate("Home Loan Management");
$this->headTitle($title);
?>
<!-- BEGIN SIDEBAR -->
<?php echo $this->partial('backend_sidebar', array('view' => 'property_loan', 'action' => 'home_loan')); ?>
<!-- END SIDEBAR -->
<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
    <div class="page-content">
        <!-- BEGIN PAGE BAR -->
        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <a href="<?php echo $this->url('admin') ?>"><?php echo $this->translate("Dashboard") ?></a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="<?php echo $this->url('admin/property_loan') ?>"><?php echo $this->translate("Property Loan") ?></a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <span><?php echo $this->translate("Home Loan") ?></span>
                </li>
            </ul>
        </div>
        <!-- END PAGE BAR -->
        
        <div class="row">
            <div class="col-md-12">
                <div class="portlet light portlet-fit portlet-datatable bordered">
                    <div class="portlet-title">
                        <div class="caption font-dark">
                            <i class="icon-share-alt font-dark"></i>
                            <span class="caption-subject bold uppercase"> <?php echo $title ?></span>
                        </div>
                        <div class="actions">
                            <div class="btn-group btn-group-devided" data-toggle="buttons">
                                <a href="javascript:;" onclick="window.history.back()" class="btn btn-transparent grey-salsa btn-outline btn-circle btn-sm"> <?php echo $this->translate("Back") ?>
                                    <i class="fa fa-history"></i>
                                </a>
                            </div>
                            <div class="btn-group">
                                <a class="btn red btn-outline btn-circle" href="javascript:;" data-toggle="dropdown">
                                    <i class="fa fa-share"></i>
                                    <span class="hidden-xs"> <?php echo $this->translate("Tools") ?> </span>
                                    <i class="fa fa-angle-down"></i>
                                </a>
                                <ul class="dropdown-menu pull-right" id="table_page_tools">
                                    <li>
                                        <a href="javascript:;" data-action="0" class="tool-action">
                                            <i class="icon-check"></i> <?php echo $this->translate("Approved") ?></a>
                                    </li>
                                    <li>
                                        <a href="javascript:;" data-action="1" class="tool-action">
                                            <i class="icon-close"></i> <?php echo $this->translate("Cancelled") ?></a>
                                    </li>
                                    <li>
                                        <a href="javascript:;" data-action="2" class="tool-action">
                                            <i class="icon-ban"></i> <?php echo $this->translate("Rejected") ?></a>
                                    </li>
                                    <li class="divider"> </li>
                                    <li>
                                        <a href="javascript:;" data-action="3" class="tool-action">
                                            <i class="icon-refresh"></i> <?php echo $this->translate("Reload") ?></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <table class="table table-striped table-bordered table-hover table-checkable" id="table_page">
                            <thead>
                                <tr>
                                    <th>
                                        <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                            <input type="checkbox" class="group-checkable" data-set="#table_page .checkboxes" />
                                            <span></span>
                                        </label>
                                    </th>
                                    <th> <?php echo $this->translate("User") ?> </th>
                                    <th> <?php echo $this->translate("Loan Amount") ?> </th>
                                    <th> <?php echo $this->translate("Loan Tenure") ?> </th>
                                    <th> <?php echo $this->translate("Date Creation") ?> </th>
                                    <th> <?php echo $this->translate("Actions") ?> </th>
                                    <th> <?php echo $this->translate("Status") ?> </th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php if(count($this->loans) > 0): ?>
                                <?php foreach ($this->loans as $loan): ?>
                                <tr class="odd gradeX">
                                    <td>
                                        <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                            <input type="checkbox" class="checkboxes" value="<?php echo $loan->getId() ?>" />
                                            <span></span>
                                        </label>
                                    </td>
                                    <td><a href="<?php echo $this->url("admin/user", array("action" => "edit", "id" => $loan->getUserId())) ?>"> <?php echo $this->user(array("id" => $loan->getUserId()))->getDisplayName() ?></a></td>
                                    <td><?php echo number_format($loan->getLoanAmount()) ?></td>
                                    <td><?php echo $loan->getLoanTenure() ?></td>
                                    <td><?php echo date("d-m-Y H:i A", strtotime($loan->getDateAdded())); ?></td>
                                    <td>
                                        <a href="<?php echo $this->url("admin/property_loan", array("action" => "individual", "id" => $loan->getId())) ?>" class="btn blue btn-xs"><i class="fa fa-search"></i> <?php echo $this->translate("Individual") ?></a>
                                        <?php if($loan->getStatus() != 1): ?>
                                        <div class="btn-group">
                                            <button class="btn btn-xs dark dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false"> <?php echo $this->translate("Actions") ?>
                                                <i class="fa fa-angle-down"></i>
                                            </button>
                                            <ul class="dropdown-menu" role="menu">
                                                <li>
                                                    <a href="javascript:;" data-id="<?php echo $loan->getId() ?>" onclick="set_status(this, 1)">
                                                        <i class="icon-check"></i> <?php echo $this->translate("Approved") ?> </a>
                                                </li>
                                                <li>
                                                    <a href="javascript:;" data-id="<?php echo $loan->getId() ?>" onclick="set_status(this, 2)">
                                                        <i class="icon-close"></i> <?php echo $this->translate("Cancelled") ?> </a>
                                                </li>
                                                <li>
                                                    <a href="javascript:;" data-id="<?php echo $loan->getId() ?>" onclick="set_status(this, 3)">
                                                        <i class="icon-ban"></i> <?php echo $this->translate("Rejected") ?> </a>
                                                </li>
                                            </ul>
                                        </div>
                                        <?php endif; ?>
                                    </td>
                                    <td><?php echo $this->status($loan); ?></td>
                                </tr>
                                <?php endforeach;?>
                                <?php endif;?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>            
</div>
<!-- END CONTENT -->
<?php
$offStyle = 12;
$offScript = 10;
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/datatables/datatables.min.css'));
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css'));
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/js/datatable.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/datatables/datatables.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js'));
$this->inlineScript()->offsetSetFile(100, $this->basePath('assets/js/custom_functions.js'));
$this->inlineScript()->captureStart();
echo <<<JS
// handle set status
function set_status(button, status) {
    var id = $(button).data("id");
    var ids = [id];
    switch(status) {
        case 1:
            action = "approved";
        break;
        
        case 2:
            action = "cancelled";
        break;
        
        case 3:
            action = "rejected";
        break;
        
        default:
            action = "pending";
    }
    $.ajax({
        type: "POST",
        url: full_url+"/admin/home-loan/set-status",
        data: {ids: ids, action: action},
        dataType: 'json',
        beforeSend: function() {
            App.blockUI({boxed: true});
        },
        success: function(itemJson) {
            App.unblockUI();      
            if(itemJson['success']) {
                toastr.success(itemJson.msg);
                setTimeout(function(){ window.location.reload(); }, 1500);
            } else {
                toastr.error(itemJson.msg);
            }
        },
        error : function(xhr, status){
            console.log(status);
        },
    });         
}

jQuery.extend( jQuery.fn.dataTableExt.oSort, {
    "date-sg-pre": function ( a ) {
        var sgDatea = a.split('-');
        var sgDateb = sgDatea[2].split(' ');
        var sgDatec = sgDateb[1].split(':');
        return (sgDateb[0] + sgDatea[1] + sgDatea[0] + sgDatec[0] + sgDatec[1] ) * 1;
    },
        
    "date-sg-asc": function ( a, b ) {
        return ((a < b) ? -1 : ((a > b) ? 1 : 0));
    },
        
    "date-sg-desc": function ( a, b ) {
        return ((a < b) ? 1 : ((a > b) ? -1 : 0));
    }
});

jQuery(document).ready(function() {
    var table = $('#table_page');
    table.dataTable({
        // Internationalisation. For more info refer to http://datatables.net/manual/i18n
        "language": {
            "aria": {
                "sortAscending": ": activate to sort column ascending",
                "sortDescending": ": activate to sort column descending"
            },
            "emptyTable": "No data available in table",
            "info": "Showing _START_ to _END_ of _TOTAL_ records",
            "infoEmpty": "No records found",
            "infoFiltered": "(filtered1 from _MAX_ total records)",
            "lengthMenu": "Show _MENU_",
            "search": "Search:",
            "zeroRecords": "No matching records found",
            "paginate": {
                "previous":"Prev",
                "next": "Next",
                "last": "Last",
                "first": "First"
            }
        },
        
        buttons: [
            {
                text: 'Approved',
                className: 'btn default',
                action: function ( e, dt, node, config ) {
                    var selectedIds = [];
                    $("input[class=checkboxes]:checked").each(function() {
                        selectedIds.push($(this).val());
                    });
                    if(selectedIds.length > 0) {
                        $.ajax({
                            type: "POST",
                            url: full_url+"/admin/home-loan/set-status",
                            data: {ids: selectedIds, action: 'approved'},
                            dataType: 'json',
                            beforeSend: function() {
                                App.blockUI({boxed: true});
                            },
                            success: function(itemJson) {
                                App.unblockUI();      
                                if(itemJson['success']) {
                                    toastr.success(itemJson.msg);
                                    setTimeout(function(){ window.location.reload(); }, 1500);
                                } else {
                                    toastr.error(itemJson.msg);
                                }
                            },
                            error : function(xhr, status){
                                console.log(status);
                            },
                        });
                    } else {
                        toastr.warning("No row checked in table.");
                    }
                }
            },
            {
                text: 'Cancelled',
                className: 'btn default',
                action: function ( e, dt, node, config ) {
                    var selectedIds = [];
                    $("input[class=checkboxes]:checked").each(function() {
                        selectedIds.push($(this).val());
                    });
                    if(selectedIds.length > 0) {
                        $.ajax({
                            type: "POST",
                            url: full_url+"/admin/home-loan/set-status",
                            data: {ids: selectedIds, action: 'cancelled'},
                            dataType: 'json',
                            beforeSend: function() {
                                App.blockUI({boxed: true});
                            },
                            success: function(itemJson) {
                                App.unblockUI();      
                                if(itemJson['success']) {
                                    toastr.success(itemJson.msg);
                                    setTimeout(function(){ window.location.reload(); }, 1500);
                                } else {
                                    toastr.error(itemJson.msg);
                                }
                            },
                            error : function(xhr, status){
                                console.log(status);
                            },
                        });
                    } else {
                        toastr.warning("No row checked in table.");
                    }
                }
            },
            {
                text: 'Rejected',
                className: 'btn default',
                action: function ( e, dt, node, config ) {
                    var selectedIds = [];
                    $("input[class=checkboxes]:checked").each(function() {
                        selectedIds.push($(this).val());
                    });
                    if(selectedIds.length > 0) {
                        $.ajax({
                            type: "POST",
                            url: full_url+"/admin/home-loan/set-status",
                            data: {ids: selectedIds, action: 'rejected'},
                            dataType: 'json',
                            beforeSend: function() {
                                App.blockUI({boxed: true});
                            },
                            success: function(itemJson) {
                                App.unblockUI();      
                                if(itemJson['success']) {
                                    toastr.success(itemJson.msg);
                                    setTimeout(function(){ window.location.reload(); }, 1500);
                                } else {
                                    toastr.error(itemJson.msg);
                                }
                            },
                            error : function(xhr, status){
                                console.log(status);
                            },
                        });
                    } else {
                        toastr.warning("No row checked in table.");
                    }
                }
            },
            {
                text: 'Reload',
                className: 'btn default',
                action: function ( e, dt, node, config ) {
                    window.location.reload();
                }
            }
        ],
        
        // setup responsive extension: http://datatables.net/extensions/responsive/
        responsive: true,

        "columnDefs": [ {
            "targets": 0,
            "orderable": false,
            "searchable": false
        }],
        
        "lengthMenu": [
            [25, 50, 100, -1],
            [25, 50, 100, "All"] // change per page values here
        ],
        // set the initial value
        "pageLength": 25,            
        "pagingType": "bootstrap_full_number",
        "columnDefs": [
            {"orderable": false,"targets": [0, 5]},
            {"type": "date-sg", "targets": 4 }
        ],
        "order": [
            [4, "desc"]
        ] // set first column as a default sort by asc
    });
    
    var tableWrapper = jQuery('#table_page_wrapper');
    table.find('.group-checkable').change(function () {
        var set = jQuery(this).attr("data-set");
        var checked = jQuery(this).is(":checked");
        jQuery(set).each(function () {
            if (checked) {
                $(this).prop("checked", true);
                $(this).parents('tr').addClass("active");
            } else {
                $(this).prop("checked", false);
                $(this).parents('tr').removeClass("active");
            }
        });
    });
    
    table.on('change', 'tbody tr .checkboxes', function () {
        $(this).parents('tr').toggleClass("active");
    });
    
    // handle datatable custom tools
    $('#table_page_tools > li > a.tool-action').on('click', function() {
        var action = $(this).attr('data-action');
        table.DataTable().button(action).trigger();
    });
});
JS;
$this->inlineScript()->captureEnd();
?>