<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->setting()->company_name)->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge')?>
        <meta content="<?php echo $this->setting()->company_description ?>" name="description" />
        <meta content="<?php echo $this->setting()->owner_name ?>" name="author" />
        
        <?php 
        $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicon.ico')); 
        $offStyle = 1;
        $this->headLink()->offsetSetStylesheet($offStyle++, 'http://fonts.googleapis.com/css?family=Lato:400,300,600,700&subset=all')
                         ->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/font-awesome/css/font-awesome.min.css'))
                         ->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/bootstrap/css/bootstrap.min.css'))
                         ->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/bootstrap-switch/css/bootstrap-switch.min.css'))
                         ->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/bootstrap-toastr/toastr.min.css'));
        // offStype 1 ~ 10
        $offStyle = 21;
        $this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/css/components-md.min.css'))
                         ->offsetSetStylesheet($offStyle++, $this->basePath('assets/css/plugins-md.min.css'))
                         ->offsetSetStylesheet($offStyle++, $this->basePath('assets/css/login.min.css'))
                         ->offsetSetStylesheet($offStyle++, $this->basePath('assets/css/my-style-slider.css'));
        ?>
        <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
        <?php echo $this->headLink();?>
                        
        <!-- Scripts -->
        <?php 
        $offScript = 1;
        $this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/js/respond.min.js', 'text/javascript', ['conditional' => 'lt IE 9']))
                             ->offsetSetFile($offScript++, $this->basePath('assets/js/excanvas.min.js', 'text/javascript', ['conditional' => 'lt IE 9']))
                             ->offsetSetFile($offScript++, $this->basePath('assets/js/jquery.min.js'))
                             ->offsetSetFile($offScript++, $this->basePath('assets/plugins/bootstrap/js/bootstrap.min.js'))
                             ->offsetSetFile($offScript++, $this->basePath('assets/js/js.cookie.min.js'))
                             ->offsetSetFile($offScript++, $this->basePath('assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js'))
                             ->offsetSetFile($offScript++, $this->basePath('assets/js/jquery.blockui.min.js'))
                             ->offsetSetFile($offScript++, $this->basePath('assets/plugins/bootstrap-switch/js/bootstrap-switch.min.js'));
        $offScript = 21;
        $this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/jquery-validation/js/jquery.validate.min.js'))
                             ->offsetSetFile($offScript++, $this->basePath('assets/plugins/jquery-validation/js/additional-methods.min.js'))
                             ->offsetSetFile($offScript++, $this->basePath('assets/plugins/bootstrap-toastr/toastr.min.js'))
                             ->offsetSetFile($offScript++, $this->basePath('assets/plugins/backstretch/jquery.backstretch.min.js'))
                             ->offsetSetFile($offScript++, $this->basePath('assets/js/app.js'))
                             ->offsetSetFile($offScript++, $this->basePath('assets/js/login.js'));?>
        <script type="text/javascript">
        /* <![CDATA[ */
        var server_url = '<?php echo $this->serverUrl() ?>';
        var base_path = '<?php echo $this->basePath() ?>';
        var full_url = '<?php echo $this->serverUrl().$this->basePath() ?>';
        /* ]]> */
        </script>
        <?php echo $this->headScript() ?>
    </head>
    <?php echo $this->content; ?>
</html>
