<?php
$title = $this->translate("Edit Support Information");
$this->headTitle($title);
?>
<!-- BEGIN SIDEBAR -->
<?php echo $this->partial('backend_sidebar', array('view' => 'setting', 'action' => 'company')); ?>
<!-- END SIDEBAR -->
<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
    <div class="page-content">
        <!-- BEGIN PAGE BAR -->
        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <a href="<?php echo $this->url('admin') ?>"><?php echo $this->translate("Dashboard") ?></a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="<?php echo $this->url('admin/setting') ?>"><?php echo $this->translate("Setting") ?></a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <span><?php echo $this->translate("Edit Support Information") ?></span>
                </li>
            </ul>
        </div>
        <!-- END PAGE BAR -->

        <div class="row">
            <div class="col-md-12">
                <div class="portlet light bordered form-fit">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="icon-settings"></i>
                            <span class="caption-subject sbold uppercase"><?php echo $this->translate($title) ?></span>
                        </div>
                    </div>
                    <div class="portlet-body form">
                        <!-- BEGIN FORM-->
                        <form action="<?php echo $this->url("admin/setting", array('action' => 'edit-support-info')) ?>" id="form_setting" class="form-horizontal form-bordered" method="post">
                            <div class="form-body">
                                <div class="alert alert-danger display-hide">
                                    <button class="close" data-close="alert"></button> You have some form errors. Please check below. </div>
                                <div class="alert alert-success display-hide">
                                    <button class="close" data-close="alert"></button> Your form validation is successful! </div>

                                <?php
                                $supporter_array_key = array('supporter_name', 'supporter_email', 'supporter_phone', 'supporter_image');
                                foreach ($this->settings as $key => $setting): ?>
                                    <?php if(in_array($setting->getKey(), $supporter_array_key)): ?>
                                      <div class="form-group">
                                        <label class="control-label col-md-3"><?php echo $this->translate($setting->getName()) ?><?php if($setting->getKey() === 'supporter_name'): ?><span class="required"> * </span><?php endif;?></label>
                                        <div class="col-md-6">
                                          <input type="text" name="<?php echo $setting->getKey(); ?>" class="form-control"<?php if(in_array($setting->getKey(), array('company_phone', 'company_fax'))) echo ' data-country="countries"'; ?> value="<?php echo $setting->getValue(); ?>" />
                                        </div>
                                      </div>
                                    <?php
                                    // var_dump($setting->getKey());
                                    // exit;
                                    if($setting->getKey() === 'supporter_image') {
                                        $supporter_image = $setting->getValue();
                                        ?>
                                        <div class="form-group">
                                            <label class="control-label col-md-3"><?php echo $setting->getName() ?></label>
                                            <div class="col-md-6">
                                                <div class="fileinput fileinput-new" data-provides="fileinput">
                                                    <div class="input-group input-large">
                                                        <div class="form-control uneditable-input input-fixed input-medium" data-trigger="fileinput">
                                                            <i class="fa fa-camera fileinput-exists"></i>&nbsp;
                                                            <span class="fileinput-filename"> </span>
                                                        </div>
                                                        <span class="input-group-addon btn default btn-file">
                                                            <span class="fileinput-new"> <?php echo $this->translate("Select file") ?> </span>
                                                            <span class="fileinput-exists"> <?php echo $this->translate("Change") ?> </span>
                                                            <input type="file" name="photoupload" id="photoupload" />
                                                            <input type="hidden" name="supporter_image" id="logo" value="<?php echo $supporter_image; ?>" />
                                                        </span>
                                                        <a href="javascript:;" class="input-group-addon btn red fileinput-exists" data-dismiss="fileinput"> <?php echo $this->translate("Remove") ?> </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="col-xs-offset-3 col-xs-6">
                                                <?php
                                                    if ($supporter_image) {
                                                        if (!file_exists('data/user/m_'.$supporter_image)) {
                                                            $image_logo = $this->basePath('data/user/'.$supporter_image);
                                                        } else {
                                                            $image_logo = $this->basePath('data/user/m_'.$supporter_image);
                                                        }
                                                    } else {
                                                        $image_logo = $this->basePath('data/user/no-avatar-256.png');
                                                    }
                                                    ?>
                                                <img id="photo" alt="logo" src="<?php echo $image_logo ?>" style="height: 50px; width: 50px;">
                                            </div>
                                        </div>
                                        <?php
                                    }
                                    ?>
                                    <?php endif;?>
                                <?php endforeach;?>
                            </div>
                            <div class="form-actions">
                                <div class="row">
                                    <div class="col-md-offset-3 col-md-9">
                                        <button type="submit" class="btn red-thunderbird"><i class="fa fa-check"></i> <?php echo $this->translate("Submit") ?></button>
                                        <button type="button" class="btn btn-outline" onclick="cancel('admin/setting')"><?php echo $this->translate("Cancel") ?></button>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <!-- END FORM-->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END CONTENT -->
<?php
$offStyle = 12;
$offScript = 10;
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/bootstrap-fileinput/bootstrap-fileinput.css'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/jquery-validation/js/jquery.validate.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/jquery-validation/js/additional-methods.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/bootstrap-fileinput/bootstrap-fileinput.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/bootstrap-formhelpers/js/bootstrap-formhelpers.min.js'));
$this->inlineScript()->offsetSetFile(100, $this->basePath('assets/js/custom_functions.js'));
$this->inlineScript()->captureStart();
echo <<<JS
$('#photoupload').on("change", function(){
    var form = document.getElementById('form_setting');
    var fileInput = document.getElementById('photoupload');
    var file = fileInput.files[0];
    var formData = new FormData();
    formData.append('file', file);
    var xhr = new XMLHttpRequest();
    xhr.onreadystatechange = function() {
        if (xhr.readyState == 4) {
            var result = $.parseJSON(xhr.responseText);
            if(result.success === true) {
                toastr.success("Photo uploaded.");
                $('#photo').attr("src", full_url + result.src);
                $('#logo').val(result.name);
            } else {
                toastr.warning(result.msg);
            }
        }
    }
    // Add any event handlers here...
    xhr.open('POST', full_url + "/admin/setting/change-logo", true);
    xhr.send(formData);
});

var form = $('#form_setting');
form.validate({
    errorElement: 'span', //default input error message container
    errorClass: 'help-block', // default input error message class
    focusInvalid: false, // do not focus the last invalid input
    ignore: "",
    rules: {
        company_name: {
            required: true
        }
    },

    highlight: function(element) { // hightlight error inputs
        $(element)
            .closest('.form-group').addClass('has-error'); // set error class to the control group
    },

    success: function(label) {
        label.closest('.form-group').removeClass('has-error');
        label.remove();
    },

    errorPlacement: function(error, element) {
        error.insertAfter(element);
    },

    submitHandler: function (form) {
        // setup some local variables
        var form = $(form);

        // let's select and cache all the fields
        var inputs = form.find("input, select, button, textarea");

        // serialize the data in the form
        var serializedData = form.serialize();

        // let's disable the inputs for the duration of the ajax request
        inputs.prop("disabled", true);

        // fire off the request to /form.php

        request = $.ajax({
            url: form.attr("action"),
            type: "post",
            data: serializedData
        });

        // Clear Message
        $('.user-form .form-group').removeClass('has-error');
        $('.user-form .help-block, .user-form .alert').remove();

        // callback handler that will be called on success
        request.done(function (response, textStatus, jqXHR) {
            var result = $.parseJSON(response);
            if(result.error) {
                toastr.error("Something error. Please check.");
            } else {
                if(result.success) {
                    toastr.success(result.msg);
                    setTimeout(function(){ window.location.href = full_url+'/admin/setting'; }, 1500);
                } else {
                    toastr.warning(result.msg);
                }
            }
        });

        // callback handler that will be called on failure
        request.fail(function (jqXHR, textStatus, errorThrown) {
            // log the error to the console
            toastr.error("The following error occured: " + textStatus, errorThrown);
        });

        // callback handler that will be called regardless
        // if the request failed or succeeded
        request.always(function () {
            // reenable the inputs
            inputs.prop("disabled", false);
        });
    }
});
JS;
$this->inlineScript()->captureEnd();
?>