<?php
$title = $this->translate("Menus Management");
$this->headTitle($title);
?>
<!-- BEGIN SIDEBAR -->
<?php echo $this->partial('backend_sidebar', array('view' => 'setting', 'action' => 'menu')); ?>
<!-- END SIDEBAR -->
<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
    <div class="page-content">
        <!-- BEGIN PAGE BAR -->
        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <a href="<?php echo $this->url('admin') ?>"><?php echo $this->translate("Dashboard") ?></a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="<?php echo $this->url('admin/setting') ?>"><?php echo $this->translate("Setting") ?></a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <span><?php echo $this->translate("Menu") ?></span>
                </li>
            </ul>
        </div>
        <!-- END PAGE BAR -->
        <div class="row">
            <div class="col-md-12">
                <div class="portlet light">
                    <div class="portlet-body">
                        <ul class="nav nav-tabs">
                            <li class="active">
                                <a href="#tab_menu" data-toggle="tab"> <?php echo $this->translate("Edit Menus"); ?> </a>
                            </li>
                            <li>
                                <a href="#tab_location" data-toggle="tab"> <?php echo $this->translate("Manage Locations"); ?> </a>
                            </li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane fade active in" id="tab_menu">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="portlet light ">
                                            <div class="portlet-title">
                                                <div class="row">
                                                    <div class="col-md-4">
                                                        <div class="input-group">
                                                            <input type="text" name="menu_name" class="form-control" placeholder="<?php echo $this->menu_group->getName() ?>" />
                                                            <span class="input-group-btn">
                                                                <button type="button" onclick="create_menu(this)" class="btn red-thunderbird ladda-button" data-style="expand-left"><?php echo $this->translate("Create Menu") ?> </button>
                                                            </span>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-4">
                                                        <div class="input-group">
                                                            <select name="group_id" class="form-control">
                                                                <option value=""><?php echo $this->translate("[select]") ?></option>
                                                                <?php
                                                                $menu_groups = $this->menu_groups(array("status" => 1));
                                                                if(count($menu_groups) > 0) {
                                                                    foreach ($menu_groups as $row) {
                                                                        ?>
                                                                        <option value="<?php echo $row->getId() ?>"<?php if($this->menu_group->getId() == $row->getId()) echo ' selected'; ?>><?php echo $row->getName() ?></option>
                                                                        <?php
                                                                    }
                                                                }
                                                                ?>
                                                            </select>
                                                            <span class="input-group-btn">
                                                                <button type="button" onclick="select_menu(this)" class="btn red-thunderbird ladda-button" data-style="expand-left"><?php echo $this->translate("Select Menu") ?> </button>
                                                            </span>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-4 text-right">
                                                        <div class="btn-group btn-group-devided" data-toggle="buttons">
                                                            <a class="btn dark" data-toggle="modal" href="#add_menu"><i class="fa fa-plus"></i> <?php echo $this->translate("Add Menu") ?> </a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="portlet-body">
                                                <div class="dd" id="nestable"><?php echo $this->menu_html ?></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="tab_location">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END CONTENT -->
<!-- BEGIN MODAL -->
<div class="modal fade" id="add_menu" tabindex="-1" role="add_menu" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form action="<?php echo $this->url("admin/setting", array("action" => "add-menu")) ?>" method="post" class="form-horizontal" id="form_add_menu">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                    <h4 class="modal-title"><?php echo $this->translate("Add New Menu") ?></h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="title" class="col-md-3 control-label"><?php echo $this->translate("Title") ?></label>
                        <div class="col-md-9">
                            <input type="text" name="title" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="title" class="col-md-3 control-label"><?php echo $this->translate("Label") ?></label>
                        <div class="col-md-9">
                            <input type="text" name="name" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="title" class="col-md-3 control-label"><?php echo $this->translate("Route") ?></label>
                        <div class="col-md-9">
                            <select name="route" class="form-control">
                                <option value=""><?php echo $this->translate("[select]") ?></option>
                                <?php
                                if(count($this->routes) > 0){
                                    foreach($this->routes as $key => $route) {
                                        ?>
                                        <option value="<?php echo $key ?>"><?php echo $key ?></option>
                                        <?php
                                    }
                                }
                                ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="title" class="col-md-3 control-label"><?php echo $this->translate("Action") ?></label>
                        <div class="col-md-9">
                            <select name="action" class="form-control">
                                <option value=""><?php echo $this->translate("[select]") ?></option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="title" class="col-md-3 control-label"><?php echo $this->translate("Value") ?></label>
                        <div class="col-md-9">
                            <input type="text" name="value" class="form-control" />
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="hidden" name="group" value="<?php echo $this->menu_group->getId(); ?>" />
                    <button type="button" class="btn default" data-dismiss="modal"><?php echo $this->translate("Close") ?></button>
                    <button type="submit" class="btn red-thunderbird"><?php echo $this->translate("Submit") ?></button>
                </div>
            </form>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- END MODAL -->
<?php
$offStyle = 12;
$offScript = 10;
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/jquery-nestable/nestable.css'));
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/sweetalert2/sweetalert2.css'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/jquery-nestable/jquery.nestable.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/jquery-validation/js/jquery.validate.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/jquery-validation/js/additional-methods.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/sweetalert2/sweetalert2.min.js'));
$this->inlineScript()->offsetSetFile(100, $this->basePath('assets/js/custom_functions.js'));
$this->inlineScript()->captureStart();
echo <<<JS
$('select[name=route]').on('change', function() {
    var route = $(this).val();
    if(route) {
        $.ajax({
            type: 'POST',
            url: full_url + '/admin/setting/load-action',
            data: {route: route},
            beforeSend: function() {
                App.blockUI({boxed: true});
            },
            success: function(data) {
                App.unblockUI();
                $('select[name=action]').html(data.html);
            },
            error: function(xhr) { // if error occured
                toastr.error("Error occured. Please try again.");
            },
            dataType: 'json'
        });
    }
});

function create_menu(button) {
    var l = Ladda.create(button);
    var name = $('input[name=menu_name]').val();
    if(name) {
        $.ajax({
            type: 'POST',
            url: full_url + '/admin/setting/create-menu',
            data: {name: name},
            beforeSend: function() {
                l.start();
            },
            success: function(data) {
                l.stop();
                if(data.success) toastr.success(data.msg);
                else toastr.error(data.msg);
            },
            error: function(xhr) { // if error occured
                toastr.error("Error occured. Please try again.");
            },
            dataType: 'json'
        });
    }
}

function select_menu(button) {
    var l = Ladda.create(button);
    var group_id = $('select[name=group_id]').val();
    if(group_id > 0) {
        window.location.href = full_url + '/admin/setting/menu/'+group_id;
    }
}

function edit_menu(button, id) {
    var l = Ladda.create(button);
    var menu_id   = id;
    var menu_name = $('#collapse_'+id+' input[name=label_title]').val();
    if(menu_id) {
        $.ajax({
            type: 'POST',
            url: full_url + '/admin/setting/edit-menu',
            data: {menu_id:menu_id, menu_name: menu_name},
            beforeSend: function() {
                l.start();
            },
            success: function(data) {
                l.stop();
                if(data.success) {
                    toastr.success(data.msg);
                    setTimeout(function(){ window.location.reload(); }, 1500);
                } else {
                    toastr.error(data.msg);
                }
            },
            error: function(xhr) { // if error occured
                toastr.error("Error occured. Please try again.");
            },
            dataType: 'json'
        });
    }
}

function remove_menu(button, id) {
    swal({
        title: 'Are you sure?',
        text: 'You will not be able to recover this!',
        type: 'warning',
        showCancelButton: true,
        confirmButtonText: 'Yes, remove it!',
        cancelButtonText: 'No, keep it',
    }).then(function() {
        var l = Ladda.create(button);
        $.ajax({
            type: 'POST',
            url: full_url + '/admin/setting/remove-menu',
            data: {menu_id:id},
            beforeSend: function() {
                l.start();
            },
            success: function(data) {
                l.stop();
                if(data.success) {
                    toastr.success(data.msg);
                    setTimeout(function(){ window.location.reload(); }, 1500);
                } else {
                    toastr.error(data.msg);
                }
            },
            error: function(xhr) { // if error occured
                toastr.error("Error occured. Please try again.");
            },
            dataType: 'json'
        });
    }, function(dismiss) {
		// dismiss can be 'cancel', 'overlay', 'close', 'timer'
		if (dismiss === 'cancel') {
			swal(
				'Cancelled',
				'Your menu is safe :)',
			'error'
			);
		}
	});
}

var form = $('#form_add_menu');
form.validate({
    errorElement: 'span', //default input error message container
    errorClass: 'help-block', // default input error message class
    focusInvalid: false, // do not focus the last invalid input
    ignore: "",
    rules: {
        title: {
            required: true
        },
        name: {
            required: true
        },
        route: {
            required: true
        }
    },

    highlight: function(element) { // hightlight error inputs
        $(element)
            .closest('.form-group').addClass('has-error'); // set error class to the control group
    },

    success: function(label) {
        label.closest('.form-group').removeClass('has-error');
        label.remove();
    },

    errorPlacement: function(error, element) {
        error.insertAfter(element);
    },

    submitHandler: function (form) {
        // setup some local variables
        var form = $(form);

        // let's select and cache all the fields
        var inputs = form.find("input, select, button, textarea");

        // serialize the data in the form
        var serializedData = form.serialize();

        // let's disable the inputs for the duration of the ajax request
        inputs.prop("disabled", true);

        // fire off the request to /form.php

        request = $.ajax({
            url: form.attr("action"),
            type: "post",
            data: serializedData
        });

        // Clear Message
        $('#form_add_menu .form-group').removeClass('has-error');
        $('#form_add_menu .help-block, #form_add_menu .alert').remove();

        // callback handler that will be called on success
        request.done(function (response, textStatus, jqXHR) {
            var result = $.parseJSON(response);
            if(result.success) {
                form.trigger("reset");
                $(".modal").modal('hide');
                toastr.success(result.msg);
                setTimeout(function(){ window.location.reload(); }, 1500);
            } else {
                toastr.error(result.msg);
            }
        });

        // callback handler that will be called on failure
        request.fail(function (jqXHR, textStatus, errorThrown) {
            // log the error to the console
            toastr.error("The following error occured: " + textStatus, errorThrown);
        });

        // callback handler that will be called regardless
        // if the request failed or succeeded
        request.always(function () {
            // reenable the inputs
            inputs.prop("disabled", false);
        });
    }
});

$('.dd').nestable({
    dropCallback: function(details) {
        var order = new Array();
        $("li[data-id='"+details.destId +"']").find('ol:first').children().each(function(index,elem) {
            order[index] = $(elem).attr('data-id');
        });
        if (order.length === 0){
            var rootOrder = new Array();
            $("#nestable > ol > li").each(function(index,elem) {
                rootOrder[index] = $(elem).attr('data-id');
            });
        }
        $.post(full_url+'/admin/setting/menu', {
            source : details.sourceId,
            destination: details.destId,
            order:JSON.stringify(order),
            rootOrder:JSON.stringify(rootOrder)
        }, function(response) {
            var result = $.parseJSON(response);
            if(result.success) toastr.success(result.msg);
        });
    }
});
JS;
$this->inlineScript()->captureEnd();
?>
