<?php
$title = $this->translate("Widget");
$this->headTitle($title);
?>
<!-- BEGIN SIDEBAR -->
<?php echo $this->partial('backend_sidebar', array('view' => 'setting', 'action' => 'widget')); ?>
<!-- END SIDEBAR -->
<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
    <div class="page-content">
        <!-- BEGIN PAGE BAR -->
        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <a href="<?php echo $this->url('admin') ?>"><?php echo $this->translate("Dashboard") ?></a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="<?php echo $this->url('admin/setting') ?>"><?php echo $this->translate("Setting") ?></a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <span><?php echo $this->translate("Widget") ?></span>
                </li>
            </ul>
        </div>
        <!-- END PAGE BAR -->
        
        <div class="row">
            <div class="col-md-12">
                <div class="portlet light bordered form-fit">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="icon-settings"></i>
                            <span class="caption-subject sbold uppercase"><?php echo $this->translate("Brands") ?></span>
                        </div>
                    </div>
                    <div class="portlet-body form">
                        <!-- BEGIN FORM-->
                        <form action="<?php echo $this->url("admin/setting", array('action' => 'widget')) ?>" class="form-horizontal form-bordered" method="POST">
                            <div class="form-body">
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Title") ?></label>
                                    <div class="col-md-9">
                                        <input type="text" name="name" value="<?php echo $widget_1->getName(); ?>" class="form-control" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <div action="<?php echo $this->url("admin/setting", array('action' => 'widget-upload-image')) ?>" class="dropzone dropzone-file-area" id="my-dropzone" style="position: relative !important;">
                                            <h3 class="sbold"><?php echo $this->translate("Drop files here or click to upload") ?></h3>
                                        </div>
                                        <?php 
                                        $product_image = \Zend\Json\Json::decode($widget_1->getContent());
                                        $image_value = "";
                                        if(count($product_image) > 0) {
                                            foreach ($product_image as $image) {
                                                $image_value .= ",".$image;
                                            }
                                        }
                                        ?>
                                        <input type="hidden" name="image" value="<?php echo $image_value ?>" />
                                    </div>
                                </div>
                            </div>
                            <div class="form-actions">
                                <div class="row">
                                    <div class="col-md-12">
                                        <input type="hidden" name="type" value="widget_1" />
                                        <button type="submit" class="btn red-thunderbird"><i class="fa fa-check"></i> <?php echo $this->translate("Submit") ?></button>
                                        <button type="button" class="btn btn-outline" onclick="cancel('admin/setting')"><?php echo $this->translate("Cancel") ?></button>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <!-- END FORM-->
                    </div>
                </div>
                
                <div class="portlet light bordered form-fit">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="icon-settings"></i>
                            <span class="caption-subject sbold uppercase"><?php echo $this->translate("Our Broad Range of Services") ?></span>
                        </div>
                    </div>
                    <div class="portlet-body form">
                        <!-- BEGIN FORM-->
                        <form action="<?php echo $this->url("admin/setting", array('action' => 'widget')) ?>" class="form-horizontal form-bordered" method="POST">
                            <div class="form-body" style="padding: 15px;">
                                <div class="row">
                                    <?php foreach ($widget_2 as $wg) { ?>
                                        <div class="col-md-4">
                                            <div class="form-group margin-bottom-15">
                                                <label><?php echo $this->translate("Title") ?> <?php echo $i; ?></label>
                                                <input type="text" name="widget_2[<?php echo $wg->getId() ?>][name]" value="<?php echo $wg->getName(); ?>" class="form-control">
                                            </div>
                                            <div class="form-group margin-bottom-15">
                                                <label><?php echo $this->translate("Content") ?> <?php echo $i; ?></label>
                                                <textarea name="widget_2[<?php echo $wg->getId() ?>][content]" class="form-control tinymce"><?php echo $wg->getContent(); ?></textarea>
                                            </div>
                                            <div class="form-group margin-bottom-15">
                                                <label><?php echo $this->translate("Link") ?> <?php echo $i; ?></label>
                                                <input type="text" name="widget_2[<?php echo $wg->getId() ?>][link]" value="<?php echo $wg->getLink(); ?>" class="form-control">
                                            </div>
                                            <div class="form-group margin-bottom-15">
                                                <label><?php echo $this->translate("Label Link") ?> <?php echo $i; ?></label>
                                                <input type="text" name="widget_2[<?php echo $wg->getId() ?>][label_link]" value="<?php echo $wg->getLabelLink(); ?>" class="form-control">
                                            </div>
                                        </div>
                                    <?php } ?>
                                </div>
                            </div>
                            <div class="form-actions">
                                <div class="row">
                                    <div class="col-md-12">
                                        <input type="hidden" name="type" value="widget_2" />
                                        <button type="submit" class="btn red-thunderbird"><i class="fa fa-check"></i> <?php echo $this->translate("Submit") ?></button>
                                        <button type="button" class="btn btn-outline" onclick="cancel('admin/setting')"><?php echo $this->translate("Cancel") ?></button>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <!-- END FORM-->
                    </div>
                </div>
                
                <div class="portlet light bordered form-fit">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="icon-settings"></i>
                            <span class="caption-subject sbold uppercase"><?php echo $this->translate("We Have Served Over 406 Business and") ?></span>
                        </div>
                    </div>
                    <div class="portlet-body form">
                        <!-- BEGIN FORM-->
                        <form action="<?php echo $this->url("admin/setting", array('action' => 'widget')) ?>" class="form-horizontal form-bordered" method="POST">
                            <div class="form-body" style="padding: 15px;">
                                <div class="row">
                                    <?php foreach ($widget_3 as $wg) { ?>
                                        <div class="col-md-3">
                                            <div class="form-group margin-bottom-15">
                                                <label><?php echo $this->translate("Title") ?> <?php echo $i; ?></label>
                                                <input type="text" name="widget_3[<?php echo $wg->getId() ?>][name]" value="<?php echo $wg->getName(); ?>" class="form-control">
                                            </div>
                                            <div class="form-group margin-bottom-15">
                                                <label><?php echo $this->translate("Content") ?> <?php echo $i; ?></label>
                                                <textarea name="widget_3[<?php echo $wg->getId() ?>][content]" class="form-control tinymce"><?php echo $wg->getContent(); ?></textarea>
                                            </div>
                                            <div class="form-group margin-bottom-15">
                                                <label><?php echo $this->translate("Count") ?> <?php echo $i; ?></label>
                                                <input type="text" name="widget_3[<?php echo $wg->getId() ?>][label_link]" value="<?php echo $wg->getLabelLink(); ?>" class="form-control">
                                            </div>
                                            <div class="form-group margin-bottom-15">
                                                <label><?php echo $this->translate("Class Icon") ?> <?php echo $i; ?></label>
                                                <input type="text" name="widget_3[<?php echo $wg->getId() ?>][link]" value="<?php echo $wg->getLink(); ?>" class="form-control">
                                            </div>
                                        </div>
                                    <?php } ?>
                                </div>
                            </div>
                            <div class="form-actions">
                                <div class="row">
                                    <div class="col-md-12">
                                        <input type="hidden" name="type" value="widget_3" />
                                        <button type="submit" class="btn red-thunderbird"><i class="fa fa-check"></i> <?php echo $this->translate("Submit") ?></button>
                                        <button type="button" class="btn btn-outline" onclick="cancel('admin/setting')"><?php echo $this->translate("Cancel") ?></button>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <!-- END FORM-->
                    </div>
                </div>
                
                <div class="portlet light bordered form-fit">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="icon-settings"></i>
                            <span class="caption-subject sbold uppercase"><?php echo $this->translate("Why use Money Compare?") ?></span>
                        </div>
                    </div>
                    <div class="portlet-body form">
                        <!-- BEGIN FORM-->
                        <form action="<?php echo $this->url("admin/setting", array('action' => 'widget')) ?>" class="form-horizontal form-bordered" method="POST">
                            <div class="form-body" style="padding: 15px;">
                                <div class="row">
                                    <?php foreach ($widget_4 as $wg) { ?>
                                        <div class="col-md-3">
                                            <div class="form-group margin-bottom-15">
                                                <label><?php echo $this->translate("Title") ?> <?php echo $i; ?></label>
                                                <input type="text" name="widget_4[<?php echo $wg->getId() ?>][name]" value="<?php echo $wg->getName(); ?>" class="form-control">
                                            </div>
                                            <div class="form-group margin-bottom-15">
                                                <label><?php echo $this->translate("Content") ?> <?php echo $i; ?></label>
                                                <textarea name="widget_4[<?php echo $wg->getId() ?>][content]" class="form-control tinymce"><?php echo $wg->getContent(); ?></textarea>
                                            </div>
                                            <div class="form-group margin-bottom-15">
                                                <label><?php echo $this->translate("Link Icon") ?> <?php echo $i; ?></label>
                                                <input type="text" name="widget_4[<?php echo $wg->getId() ?>][link]" value="<?php echo $wg->getLink(); ?>" class="form-control">
                                            </div>
                                        </div>
                                    <?php } ?>
                                </div>
                            </div>
                            <div class="form-actions">
                                <div class="row">
                                    <div class="col-md-12">
                                        <input type="hidden" name="type" value="widget_4" />
                                        <button type="submit" class="btn red-thunderbird"><i class="fa fa-check"></i> <?php echo $this->translate("Submit") ?></button>
                                        <button type="button" class="btn btn-outline" onclick="cancel('admin/setting')"><?php echo $this->translate("Cancel") ?></button>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <!-- END FORM-->
                    </div>
                </div>
            </div>
        </div>
    </div>            
</div>
<!-- END CONTENT -->
<?php
$offStyle = 12;
$offScript = 10;
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/bootstrap-fileinput/bootstrap-fileinput.css'));
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/dropzone/basic.min.css'));
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/dropzone/dropzone.min.css'));
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/css/simplePagination.css'));
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/mlib/css/mlib.css'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/jquery-validation/js/jquery.validate.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/jquery-validation/js/additional-methods.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/bootstrap-fileinput/bootstrap-fileinput.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/bootstrap-formhelpers/js/bootstrap-formhelpers.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/tinymce/js/tinymce/tinymce.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/dropzone/dropzone.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/js/jquery.simplePagination.js'));
$this->inlineScript()->offsetSetFile(33, $this->basePath('assets/plugins/mlib/js/mlib.js'));
$this->inlineScript()->offsetSetFile(43, $this->basePath('assets/plugins/jquery-ui/jquery-ui.min.js'));
$this->inlineScript()->offsetSetFile(100, $this->basePath('assets/js/custom_functions.js'));                        
$this->inlineScript()->captureStart();
echo <<<JS
tinymce.baseURL = "{$this->basePath('assets/plugins/tinymce/js/tinymce')}";
tinymce.PluginManager.add('mce_mlib', function(editor, url) {
	var tinyedit_id = editor.id;
    editor.addButton('mce_mlib', {
        text: 'Insert Media',
        icon: false,
        id: 'mediabtn_'+tinyedit_id,
        icon : 'image',
        onclick: function() {
            var newid = '#mediabtn_'+tinyedit_id;
            if($(newid).attr('mboxmce_init')===undefined){
                $(newid).attr('mboxmce_init', tinyedit_id);
                $(newid).mlibready({allowed:'jpg,png,gif,jpeg,txt,zip,rar,doc,docx,ppt,pptx,xls,xlsx,csv,tar,gz', mcename:tinyedit_id, returnas:'all'});
                $(newid).trigger('click');
			}
        }
    });

    // Adds a menu item
    editor.addMenuItem('mce_mlib', {
        text: 'Insert Media',
        context: 'file',
		icon : 'image',
		id: 'mediabtn_'+tinyedit_id,
        onclick: function() {
			var newid = '#mediabtn_'+tinyedit_id;
			if($(newid).attr('mboxmce_init')===undefined){
			$(newid).attr('mboxmce_init', tinyedit_id);
			$(newid).mlibready({allowed:'jpg,png,gif,jpeg,txt,zip,rar,doc,docx,ppt,pptx,xls,xlsx,csv,tar,gz', mcename:tinyedit_id, returnas:'all'});
			$(newid).trigger('click');
			}
        }
    });
});
tinymce.init({
    selector: '.tinymce',
    height: 300,
    menubar: false,
    statusbar: false,
    //plugins: 'mce_mlib advlist table link textcolor code',
    //toolbar: 'mce_mlib | advlist | table | link | styleselect | bold italic | alignment | alignmentv2 | fontsizeselect | forecolor | backcolor | code',
    plugins: [
        'advlist autolink lists link image charmap print preview hr anchor pagebreak',
        'searchreplace wordcount visualblocks visualchars code fullscreen',
        'insertdatetime media nonbreaking save table contextmenu directionality',
        'emoticons template paste textcolor colorpicker textpattern imagetools codesample'
    ],
    toolbar1: 'undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
    toolbar2: 'print preview media | forecolor backcolor emoticons | codesample help | code',
    image_advtab: true,
    fontsize_formats: '8px 10px 12px 14px 18px 24px 36px',
    setup: function (editor) {
        editor.on('change', function () {
            editor.save();
        });
    }
});

var FormDropzone = function () {
    return {
        //main function to initiate the module
        init: function () {  
            Dropzone.options.myDropzone = {
                dictDefaultMessage: "",
                init: function() {
                    //Populate any existing thumbnails
                    var thisDropzone = this;
                    $.get(full_url + '/admin/setting/widget-load-image','',function(data){
                        var files = JSON.parse(data);
                        for (var i = 0; i < files.length; i++) {
                            var img_src = full_url +  files[i].url;
                            var mockFile = {
                                url: img_src,
                                size: files[i].size,
                                name: files[i].name,
                                status: Dropzone.ADDED,
                                accepted: true
                            };
                            thisDropzone.emit("addedfile", mockFile); //here I get the error
                            thisDropzone.emit("thumbnail", mockFile, img_src);
                            thisDropzone.emit("complete", mockFile); 
                            thisDropzone.files.push(mockFile);
                            
                            //var existingFileCount = 1; // The number of files already uploaded
                            //this.options.maxFiles = thisDropzone.options.maxFiles - existingFileCount;
                        
                            $(".dz-preview:last-child").attr('data-imagename', files[i].name);
                        }
                    });
                    this.on("addedfile", function(file) {
                        // Create the remove button
                        var removeButton = Dropzone.createElement("<a href='javascript:;' class='btn red btn-sm btn-block'>Remove</a>");
                        
                        // Capture the Dropzone instance as closure.
                        var _this = this;

                        // Listen to the click event
                        removeButton.addEventListener("click", function(e) {
                            // Make sure the button click doesn't submit the form:
                            e.preventDefault();
                            e.stopPropagation();

                            // If you want to the delete the file on the server as well,
                            // you can do the AJAX request here.
                            var name = $(this).parent().attr('data-imagename');
                            $.ajax({
                                type: 'POST',
                                url: full_url + '/admin/setting/widget-delete-image',
                                data: {name:name}, 
                                success: function(data) {
                                    if(data.success) {
                                        // Remove the file preview.
                                        _this.removeFile(file);
                                        
                                        var curent='';  
                                        $('#my-dropzone .dz-preview').each(function(){
                                            curent=curent+','+$(this).attr('data-imagename'); 
                                        });
                                        $('input[name=image]').val(curent); 
                                    } 
                                },
                                error: function(xhr) { // if error occured
                                    toastr.error("Error occured. Please try again.");
                                },
                                dataType: 'json'  
                            });
                        });

                        // Add the button to the file preview element.
                        file.previewElement.appendChild(removeButton);
                    });
                    
                    this.on("success", function(file, response) {
                        var response = JSON.parse(response);
                        if(response.success) {
                            var all_name = $('input[name=image]').val();
                            all_name = all_name+","+response.name;
                            $('input[name=image]').val(all_name);
                            
                            file.serverId = response.name;
                            $(".dz-preview:last-child").attr('data-imagename', file.serverId);
                            
                            // Update again
                            var name_arr = all_name.split(',');
                            $('.dz-preview').each(function(index){
                                var i = index + 1;
                                $(this).attr('data-imagename', name_arr[i]);
                            });
                            
                            toastr.success(response.msg);
                        } else {
                            toastr.error(response.msg);
                        }
                    });
                }            
            }
        }
    };
}();

FormDropzone.init();
$("#my-dropzone").sortable({
    items:'.dz-preview',
    cursor: 'move',
    opacity: 0.5,
    containment: "parent",
    distance: 20,
    tolerance: 'pointer',
    update: function(e, ui){
        var all_id, new_id;
        all_id = "";
        $( "#my-dropzone .dz-preview" ).each(function(){
            new_id = $(this).attr('data-imagename'); 
            if (typeof new_id != 'undefined') {
                all_id=all_id+","+new_id; 
            }
        });
        $('input[name=image]').val(all_id);
    }
});
JS;
$this->inlineScript()->captureEnd();
?>