<?php
$title = $this->translate("Edit User");
$this->headTitle($title);
?>
<!-- BEGIN SIDEBAR -->
<?php echo $this->partial('backend_sidebar', array('view' => 'user', 'action' => 'index')); ?>
<!-- END SIDEBAR -->
<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
    <div class="page-content">
        <!-- BEGIN PAGE BAR -->
        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <a href="<?php echo $this->url('admin') ?>"><?php echo $this->translate("Dashboard") ?></a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="<?php echo $this->url('admin/user') ?>"><?php echo $this->translate("User") ?></a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <span><?php echo $this->translate("Edit") ?></span>
                </li>
            </ul>
        </div>
        <!-- END PAGE BAR -->
        <div class="row">
            <div class="col-md-12">
                <div class="portlet light bordered form-fit">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="icon-user"></i>
                            <span class="caption-subject sbold uppercase"><?php echo $this->translate("Edit User") ?> <?php echo $this->user->getDisplayname() ?></span>
                        </div>
                    </div>
                    <div class="portlet-body form">
                        <!-- BEGIN FORM-->
                        <form action="<?php echo $this->url("admin/user", array("action" => "edit", "id" => $this->user->getId())) ?>" id="form_user" class="form-horizontal form-bordered">
                            <div class="form-body">
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("First Name") ?><span class="required"> * </span></label>
                                    <div class="col-md-6">
                                        <input type="text" name="firstname" class="form-control" value="<?php echo $this->user->getFirstName() ?>" /> 
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Last Name") ?><span class="required"> * </span></label>
                                    <div class="col-md-6">
                                        <input type="text" name="lastname" class="form-control" value="<?php echo $this->user->getLastName() ?>" /> 
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Email") ?><span class="required"> * </span></label>
                                    <div class="col-md-6">
                                        <input type="text" name="email" data-required="1" class="form-control" value="<?php echo $this->user->getEmail() ?>" readonly="true" /> 
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Phone") ?><span class="required"> * </span></label>
                                    <div class="col-md-6">
                                        <input type="text" name="phone" data-required="1" class="form-control" value="<?php echo $this->user->getPhone() ?>" readonly="true" /> 
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Role") ?><span class="required"> * </span></label>
                                    <div class="col-md-6">
                                        <select name="role_id" class="form-control">
                                            <option value=""><?php echo $this->translate("[select]") ?></option>
                                            <?php
                                            foreach ($this->roles(array("status" => 1)) as $role) {
                                                ?>
                                                <option value="<?php echo $role->getId() ?>"<?php if($role->getId() == $this->user->getRoleId()) echo ' selected'; ?>><?php echo $role->getName() ?></option>
                                                <?php
                                            }
                                            ?>
                                        </select>
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Date of Birth") ?></label>
                                    <div class="col-md-6">
                                        <input type="text" name="date_of_birth" class="form-control date date-picker" data-date-format="dd-MM-yyyy" value="<?php echo date("d-M-Y", strtotime($this->user->getDateOfBirth())) ?>" /> 
                                    </div>
                                </div>
                                                                
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Gender") ?></label>
                                    <div class="col-md-6">
                                        <div class="input-group">
                                            <div class="icheck-inline">
                                                <label><input type="radio" name="gender" value="1"<?php if($this->user->getGender() == 1) echo ' checked'; ?> class="icheck" data-radio="iradio_flat-blue"> <?php echo $this->translate("Male") ?> </label>
                                                <label><input type="radio" name="gender" value="2"<?php if($this->user->getGender() == 2) echo ' checked'; ?> class="icheck" data-radio="iradio_flat-blue"> <?php echo $this->translate("Female") ?> </label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                                                
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Company name") ?></label>
                                    <div class="col-md-6">
                                        <input type="text" name="company_name" class="form-control" value="<?php echo $this->user->getCompanyName() ?>" /> 
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Status") ?></label>
                                    <div class="col-md-6">
                                        <select class="form-control" name="status">
                                            <option value="1"<?php if($this->user->getStatus() == 1) echo ' selected'; ?>><?php echo $this->translate("Active") ?></option>
                                            <option value="0"<?php if($this->user->getStatus() == 0) echo ' selected'; ?>><?php echo $this->translate("Deactive") ?></option>
                                            <option value="2"<?php if($this->user->getStatus() == 2) echo ' selected'; ?>><?php echo $this->translate("Pending") ?></option>
                                            <option value="3"<?php if($this->user->getStatus() == 3) echo ' selected'; ?>><?php echo $this->translate("Suspend") ?></option>
                                            <option value="4"<?php if($this->user->getStatus() == 4) echo ' selected'; ?>><?php echo $this->translate("Trash") ?></option>
                                        </select>
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Newsletter") ?></label>
                                    <div class="col-md-6">
                                        <div class="mt-radio-inline">
                                            <input type="checkbox" name="newsletter" class="icheck" data-checkbox="icheckbox_flat-blue"<?php if($this->user->getNewsletter() == 1) echo ' checked'; ?> value="1" />
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="form-group hide">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Select Avatar") ?></label>
                                    <div class="col-md-6">
                                        <div class="fileinput fileinput-new" data-provides="fileinput">
                                            <div class="input-group input-large">
                                                <div class="form-control uneditable-input input-fixed input-medium" data-trigger="fileinput">
                                                    <i class="fa fa-camera fileinput-exists"></i>&nbsp;
                                                    <span class="fileinput-filename"> </span>
                                                </div>
                                                <span class="input-group-addon btn default btn-file">
                                                    <span class="fileinput-new"> <?php echo $this->translate("Select file") ?> </span>
                                                    <span class="fileinput-exists"> <?php echo $this->translate("Change") ?> </span>
                                                    <input type="file" name="photoupload" id="photoupload" />
                                                    <input type="hidden" name="logo" id="logo" value="<?php echo $this->user->getAvatar() ?>" />
                                                </span>
                                                <a href="javascript:;" class="input-group-addon btn red fileinput-exists" data-dismiss="fileinput"> <?php echo $this->translate("Remove") ?> </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group hide">
                                    <div class="col-xs-offset-3 col-xs-6">
                                        <?php
                                            if ($this->user->getAvatar()) {
                                                $user_logo = $this->user->getAvatar();
                                                if (!file_exists('data/user/'.$this->user->getId().'/logo/m_'.$user_logo)) {
                                                    $image_logo = $this->basePath('data/user/'.$this->user->getId().'/'.$user_logo);
                                                } else {
                                                    $image_logo = $this->basePath('data/user/'.$this->user->getId().'/m_'.$user_logo);
                                                }
                                            } else {
                                                $image_logo = $this->basePath('data/user/no-avatar-128.png');
                                            }
                                            ?>
                                        <img id="photo" alt="logo" class="img-circle" src="<?php echo $image_logo ?>">
                                    </div>
                                </div>
                            </div>
                            <div class="form-actions">
                                <div class="row">
                                    <div class="col-md-offset-3 col-md-9">
                                        <button type="submit" class="btn red-thunderbird"><i class="fa fa-check"></i> <?php echo $this->translate("Submit") ?></button>
                                        <button type="button" class="btn btn-outline" onclick="cancel('admin/user')"><?php echo $this->translate("Cancel") ?></button>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <!-- END FORM-->
                    </div>
                </div>
            </div>
        </div>
    </div>            
</div>
<!-- END CONTENT -->
<?php
$offStyle = 12;
$offScript = 10;
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css'));
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/bootstrap-fileinput/bootstrap-fileinput.css'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/bootstrap-fileinput/bootstrap-fileinput.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/js/moment.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/jquery-validation/js/jquery.validate.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/jquery-validation/js/additional-methods.min.js'));
$this->inlineScript()->offsetSetFile(100, $this->basePath('assets/js/custom_functions.js'));
$this->inlineScript()->captureStart();
echo <<<JS

$('#photoupload').on("change", function(){
    var form = document.getElementById('form_user');
    var fileInput = document.getElementById('photoupload');
    var file = fileInput.files[0];
    var formData = new FormData();
    formData.append('file', file);
    var xhr = new XMLHttpRequest();
    xhr.onreadystatechange = function() {
        if (xhr.readyState == 4) {
            var result = $.parseJSON(xhr.responseText);
            if(result.success === true) {
                toastr.success(result.msg);
                $('#photo').attr("src", full_url + result.src);
                $('#logo').val(result.name);
            } else {
                toastr.warning(result.msg);
            } 
        }
    }
    // Add any event handlers here...
    xhr.open('POST', full_url + "/admin/user/change-logo", true);
    xhr.send(formData);
});

var form = $('#form_user');
form.validate({
    errorElement: 'span', //default input error message container
    errorClass: 'help-block', // default input error message class
    focusInvalid: false, // do not focus the last invalid input
    ignore: "",
    rules: {
        role_id: {
            required: true
        },
        firstname: {
            required: true,
            minlength: 2
        },
        lastname: {
            required: true,
            minlength: 2
        },
        email: {
            required: true,
            email: true
        },
        phone: {
            required: true,
            number: true
        }
    },
    
    highlight: function(element) { // hightlight error inputs
        $(element)
            .closest('.form-group').addClass('has-error'); // set error class to the control group
    },

    success: function(label) {
        label.closest('.form-group').removeClass('has-error');
        label.remove();
    },

    errorPlacement: function(error, element) {
        error.insertAfter(element);
    },

    submitHandler: function (form) {
        // setup some local variables
        var form = $(form);
        
        // let's select and cache all the fields
        var inputs = form.find("input, select, button, textarea");
        
        // serialize the data in the form
        var serializedData = form.serialize();
    
        // let's disable the inputs for the duration of the ajax request
        inputs.prop("disabled", true);
        
        // fire off the request to /form.php

        request = $.ajax({
            url: form.attr("action"),
            type: "post",
            data: serializedData
        });
        
        // Clear Message
        $('#form_user .form-group').removeClass('has-error');
        $('#form_user .help-block, #form_user .alert').remove();
        
        // callback handler that will be called on success
        request.done(function (response, textStatus, jqXHR) {
            var result = $.parseJSON(response);
            if(result.error) {
                toastr.error("Something Error. Please check.");
            } else {
                if(result.success) {
                    toastr.success(result.msg);
                    setTimeout(function(){ window.location.href = full_url+'/admin/user'; }, 1500);
                } else {
                    toastr.warning(result.msg);
                }
            }
        });
        
        // callback handler that will be called on failure
        request.fail(function (jqXHR, textStatus, errorThrown) {
            // log the error to the console
            toastr.error("The following error occured: " + textStatus, errorThrown);
        });
        
        // callback handler that will be called regardless
        // if the request failed or succeeded
        request.always(function () {
            // reenable the inputs
            inputs.prop("disabled", false);
        });
    }
});
JS;
$this->inlineScript()->captureEnd();
?>