<?php
$title = $this->translate("Add New Property Loan");
$this->headTitle($title);
?>
<!-- BEGIN SIDEBAR -->
<?php echo $this->partial('backend_sidebar', array('view' => 'bank', 'action' => 'property-loan')); ?>
<!-- END SIDEBAR -->
<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
    <div class="page-content">
        <!-- BEGIN PAGE BAR -->
        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <a href="<?php echo $this->url('admin') ?>"><?php echo $this->translate("Dashboard") ?></a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="<?php echo $this->url('admin/bank') ?>"><?php echo $this->translate("Banks") ?></a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <span><?php echo $this->translate("Add Property Loan") ?></span>
                </li>
            </ul>
        </div>
        <!-- END PAGE BAR -->
        
        <div class="row">
            <div class="col-md-12">
                <div class="portlet light bordered form-fit">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="icon-bank"></i>
                            <span class="caption-subject sbold uppercase"><?php echo $this->translate($title) ?></span>
                        </div>
                    </div>
                    <div class="portlet-body form">
                        <!-- BEGIN FORM-->
                        <form action="<?php echo $this->url("admin/bank", array("action" => "add-property-loan")) ?>" id="form_bank" class="form-horizontal form-bordered">
                            <div class="form-body">
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Type") ?><span class="required"> * </span></label>
                                    <div class="col-md-6">
                                        <select name="type" class="form-control">
                                            <option value=""><?php echo $this->translate("[select]") ?></option>
                                            <option value="home_loan"><?php echo $this->translate("Home Loan") ?></option>
                                            <option value="refinancing"><?php echo $this->translate("Refinancing") ?></option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Bank") ?><span class="required"> * </span></label>
                                    <div class="col-md-6">
                                        <select name="bank_id" class="form-control">
                                            <option value=""><?php echo $this->translate("[select]") ?></option>
                                            <?php
                                            $banks = $this->banks(array("status" => 1));
                                            if(count($banks) > 0) {
                                                foreach ($banks as $bank) {
                                                    ?>
                                                    <option value="<?php echo $bank->getId() ?>"><?php echo $bank->getName() ?></option>
                                                    <?php
                                                }
                                            }
                                            ?>
                                        </select>
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Loan title") ?><span class="required"> * </span></label>
                                    <div class="col-md-6">
                                        <input type="text" name="loan_title" data-required="1" class="form-control" value="" /> 
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Promotions title") ?></label>
                                    <div class="col-md-6">
                                        <textarea name="promotions" class="form-control" rows="2"></textarea>
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Benefit title") ?></label>
                                    <div class="col-md-9">
                                        <textarea name="benefit" class="form-control editor"></textarea>
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Max Tenor (Years)") ?></label>
                                    <div class="col-md-6">
                                        <input type="text" name="max_tenor" class="form-control" /> 
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Max Loan Amount") ?></label>
                                    <div class="col-md-6">
                                        <input type="text" name="max_loan_amount" class="form-control" /> 
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Lock In Period") ?></label>
                                    <div class="col-md-6">
                                        <input type="text" name="lock_in_period" class="form-control" /> 
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Status") ?></label>
                                    <div class="col-md-6">
                                        <select class="form-control" name="status">
                                            <option value="1"><?php echo $this->translate("Active") ?></option>
                                            <option value="0"><?php echo $this->translate("Deactive") ?></option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="form-actions">
                                <div class="row">
                                    <div class="col-md-offset-3 col-md-9">
                                        <button type="submit" class="btn red-thunderbird"><i class="fa fa-check"></i> <?php echo $this->translate("Submit") ?></button>
                                        <button type="button" class="btn btn-outline" onclick="cancel('admin/bank/view-property-loan')"><?php echo $this->translate("Cancel") ?></button>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <!-- END FORM-->
                    </div>
                </div>
            </div>
        </div>
    </div>            
</div>
<!-- END CONTENT -->
<?php
$offStyle = 12;
$offScript = 10;
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/jquery-validation/js/jquery.validate.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/jquery-validation/js/additional-methods.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/tinymce/js/tinymce/tinymce.min.js'));
$this->inlineScript()->offsetSetFile(100, $this->basePath('assets/js/custom_functions.js'));
$this->inlineScript()->captureStart();
echo <<<JS
tinymce.init({
    selector: '.editor',
    height: 300,
    plugins: [
        'advlist autolink lists link image charmap print preview anchor',
        'searchreplace visualblocks code fullscreen',
        'insertdatetime media table contextmenu paste code'
    ],
    toolbar: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
    content_css: full_url+'/assets/css/codepen.min.css',
    setup: function (editor) {
        editor.on('change', function () {
            editor.save();
        });
    }
});

var form = $('#form_bank');
form.validate({
    errorElement: 'span', //default input error message container
    errorClass: 'help-block', // default input error message class
    focusInvalid: false, // do not focus the last invalid input
    ignore: "",
    rules: {
        type: {
            required: true
        },
        bank_id: {
            required: true
        },
        loan_title: {
            required: true
        }
    },
    
    highlight: function(element) { // hightlight error inputs
        $(element)
            .closest('.form-group').addClass('has-error'); // set error class to the control group
    },

    success: function(label) {
        label.closest('.form-group').removeClass('has-error');
        label.remove();
    },

    errorPlacement: function(error, element) {
        error.insertAfter(element);
    },

    submitHandler: function (form) {
        // setup some local variables
        var form = $(form);
        
        // let's select and cache all the fields
        var inputs = form.find("input, select, button, textarea");
        
        // serialize the data in the form
        var serializedData = form.serialize();
    
        // let's disable the inputs for the duration of the ajax request
        inputs.prop("disabled", true);
        
        // fire off the request to /form.php

        request = $.ajax({
            url: form.attr("action"),
            type: "post",
            data: serializedData
        });
        
        // Clear Message
        $('#form_bank .form-group').removeClass('has-error');
        $('#form_bank .help-block, #form_bank .alert').remove();
        
        // callback handler that will be called on success
        request.done(function (response, textStatus, jqXHR) {
            var result = $.parseJSON(response);
            if(result.error) {
                toastr.error("Something error. Please check");
            } else {
                if(result.success) {
                    toastr.success(result.msg);
                    setTimeout(function(){ window.location.href = full_url+'/admin/bank/view-property-loan'; }, 1500);
                } else {
                    toastr.warning(result.msg);
                }
            }
        });
        
        // callback handler that will be called on failure
        request.fail(function (jqXHR, textStatus, errorThrown) {
            // log the error to the console
            toastr.error("The following error occured: " + textStatus, errorThrown);
        });
        
        // callback handler that will be called regardless
        // if the request failed or succeeded
        request.always(function () {
            // reenable the inputs
            inputs.prop("disabled", false);
        });
    }
});
JS;
$this->inlineScript()->captureEnd();
?>