<?php
$title = $this->translate("Update Interest Rate");
$this->headTitle($title);
?>
<!-- BEGIN SIDEBAR -->
<?php echo $this->partial('backend_sidebar', array('view' => 'bank', 'action' => 'interest-rate')); ?>
<!-- END SIDEBAR -->
<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
    <div class="page-content">
        <!-- BEGIN PAGE BAR -->
        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <a href="<?php echo $this->url('admin') ?>"><?php echo $this->translate("Dashboard") ?></a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="<?php echo $this->url('admin/bank') ?>"><?php echo $this->translate("Banks") ?></a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="<?php echo $this->url('admin/bank', array('action' => 'view-interest-rate')) ?>"><?php echo $this->translate("Interest Rate") ?></a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <span><?php echo $this->translate("Update") ?></span>
                </li>
            </ul>
        </div>
        <!-- END PAGE BAR -->
        
        <div class="row">
            <div class="col-md-12">
                <div class="portlet light bordered form-fit">
                    <div class="portlet-title">
                        <div class="caption font-dark">
                            <i class="fa fa-bank font-dark"></i>
                            <span class="caption-subject bold uppercase"> <?php echo $title ?></span>
                        </div>
                    </div>
                    <div class="portlet-body form">
                        <form class="form-horizontal form-bordered" action="<?php echo $this->url("admin/bank", array("action" => "update-interest-rate", "id" => $this->bank->getId())) ?>" method="post" id="form_page">
                            <div class="form-body">
                                <div class="form-group">
                                    <label class="col-md-3 control-label"><?php echo $this->translate("Name"); ?></label>
                                    <div class="col-md-9">
                                        <p class="form-control-static">
                                        <?php 
                                        $bank = $this->bank(array("id" => $this->bank->getBankId()));
                                        echo $bank->getName(); 
                                        ?>
                                        </p>  
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-3 control-label"><?php echo $this->translate("Loan title"); ?></label>
                                    <div class="col-md-9">
                                        <p class="form-control-static"><?php echo $this->bank->getLoanTitle(); ?></p>  
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-3 control-label"><?php echo $this->translate("Promotions"); ?></label>
                                    <div class="col-md-9">
                                        <p class="form-control-static"><?php echo $this->bank->getPromotions(); ?></p>  
                                    </div>
                                </div>
                                <div class="form-group mt-repeater">
                                    <div data-repeater-list="interest-rate" style="border-left: 0;">
                                        <?php
                                        $interest_rate = \Zend\Json\Json::decode($this->bank->getInterestRate());
                                        $max_loan_tenure = $this->setting()->max_loan_tenure;
                                        $max_loan_tenure = $max_loan_tenure ? $max_loan_tenure : 10;
                                        if(count($interest_rate) > 0) {
                                            foreach ($interest_rate as $key => $value) {
                                                $year = $value->year;
                                                ?>
                                                <div data-repeater-item class="mt-repeater-item">
                                                    <div class="row mt-repeater-row">
                                                        <div class="col-md-3">
                                                            <label class="control-label"><?php echo $this->translate("Condition") ?></label>
                                                            <input type="text" name="condition" class="form-control" value="<?php echo $value->condition ?>" /> 
                                                        </div>
                                                    </div>
                                                    <div class="row mt-repeater-row">
                                                        <div class="col-md-12">
                                                            <label class="control-label"><?php echo $this->translate("Year") ?></label>
                                                            <table class="table table-bordered table-striped table-condensed flip-content">
                                                                <thead class="flip-content">
                                                                    <tr>
                                                                        <?php for($i=1; $i<=$max_loan_tenure; $i++): ?>
                                                                        <th> <?php echo $i ?> <?php echo $this->translate("Year") ?></th>
                                                                        <?php endfor; ?>
                                                                    </tr>
                                                                </thead>
                                                                <tbody>
                                                                    <tr>
                                                                        <?php for($i=1; $i<=$max_loan_tenure; $i++): ?>
                                                                        <td> <input type="text" name="<?php echo $i ?>" class="form-control" value="<?php echo $year->{$i} ?>" /></td>
                                                                        <?php endfor; ?>
                                                                    </tr>
                                                                </tbody>
                                                            </table>
                                                        </div>
                                                    </div>
                                                    <div class="row mt-repeater-row">
                                                        <div class="col-md-1" style="padding-top: 20px;">
                                                            <a href="javascript:;" data-repeater-delete class="btn btn-danger mt-repeater-delete">
                                                                <i class="fa fa-close"></i> <?php echo $this->translate("Remove Interest Rate row") ?></a>
                                                            </a>
                                                        </div>
                                                    </div>
                                                </div>
                                                <?php    
                                            }
                                        } else {
                                            ?>
                                            <div data-repeater-item class="mt-repeater-item">
                                                <div class="row mt-repeater-row">
                                                    <div class="col-md-3">
                                                        <label class="control-label"><?php echo $this->translate("Condition") ?></label>
                                                        <input type="text" name="condition" class="form-control" /> 
                                                    </div>
                                                </div>
                                                <div class="row mt-repeater-row">
                                                    <div class="col-md-12">
                                                        <label class="control-label"><?php echo $this->translate("Year") ?></label>
                                                        <table class="table table-bordered table-striped table-condensed flip-content">
                                                            <thead class="flip-content">
                                                                <tr>
                                                                    <?php for($i=1; $i<=$max_loan_tenure; $i++): ?>
                                                                    <th> <?php echo $i ?> <?php echo $this->translate("Year") ?></th>
                                                                    <?php endfor; ?>
                                                                </tr>
                                                            </thead>
                                                            <tbody>
                                                                <tr>
                                                                    <?php for($i=1; $i<=$max_loan_tenure; $i++): ?>
                                                                    <td> <input type="text" name="<?php echo $i ?>" class="form-control" /></td>
                                                                    <?php endfor; ?>
                                                                </tr>
                                                            </tbody>
                                                        </table>
                                                    </div>
                                                </div>
                                                <div class="row mt-repeater-row">
                                                    <div class="col-md-1" style="padding-top: 20px;">
                                                        <a href="javascript:;" data-repeater-delete class="btn btn-danger mt-repeater-delete">
                                                            <i class="fa fa-close"></i> <?php echo $this->translate("Remove Interest Rate row") ?></a>
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        <?php } ?>
                                    </div>
                                    <div style="border-left: 0;">
                                        <a href="javascript:;" data-repeater-create class="btn btn-info mt-repeater-add">
                                            <i class="fa fa-plus"></i> <?php echo $this->translate("Add Interest Rate") ?></a>
                                    </div>
                                </div>
                            </div>
                            <div class="form-actions">
                                <div class="row">
                                    <div class="col-md-offset-3 col-md-9">
                                        <input type="hidden" name="id" value="<?php echo $this->bank->getId(); ?>" />
                                        <button type="submit" class="btn red-thunderbird"><i class="fa fa-check"></i> <?php echo $this->translate("Submit") ?></button>
                                        <button type="button" class="btn btn-outline" onclick="cancel('admin/bank/view-interest-rate')"><?php echo $this->translate("Cancel") ?></button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>            
</div>
<!-- END CONTENT -->
<?php
$offStyle = 12;
$offScript = 10;
//$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/datatables/datatables.min.css'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/jquery-repeater/jquery.repeater.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/jquery-validation/js/jquery.validate.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/jquery-validation/js/additional-methods.min.js'));
$this->inlineScript()->offsetSetFile(100, $this->basePath('assets/js/custom_functions.js'));
$this->inlineScript()->captureStart();
echo <<<JS
$('.mt-repeater').each(function(){
    $(this).repeater({
        show: function () {
       	    $(this).slideDown();
        },
        hide: function (deleteElement) {
            if(confirm('Are you sure you want to delete this element?')) {
                $(this).slideUp(deleteElement);
            }
        },
        ready: function (setIndexes) {
            
        }
    });
});

var form = $('#form_page');
form.validate({
    errorElement: 'span', //default input error message container
    errorClass: 'help-block', // default input error message class
    focusInvalid: false, // do not focus the last invalid input
    ignore: "",
    rules: {
        id: {
            required: true
        }
    },
    
    highlight: function(element) { // hightlight error inputs
        $(element)
            .closest('.form-group').addClass('has-error'); // set error class to the control group
    },

    success: function(label) {
        label.closest('.form-group').removeClass('has-error');
        label.remove();
    },

    errorPlacement: function(error, element) {
        error.insertAfter(element);
    },

    submitHandler: function (form) {
        // setup some local variables
        var form = $(form);
        
        // let's select and cache all the fields
        var inputs = form.find("input, select, button, textarea");
        
        // serialize the data in the form
        var serializedData = form.serialize();
    
        // let's disable the inputs for the duration of the ajax request
        inputs.prop("disabled", true);
        
        // fire off the request to /form.php

        request = $.ajax({
            url: form.attr("action"),
            type: "post",
            data: serializedData
        });
        
        // Clear Message
        $('#form_page .form-group').removeClass('has-error');
        $('#form_page .help-block, #form_page .alert').remove();
        
        // callback handler that will be called on success
        request.done(function (response, textStatus, jqXHR) {
            var result = $.parseJSON(response);
            if(result.error) {
                toastr.error("Something error. Please check");
            } else {
                if(result.success) {
                    toastr.success(result.msg);
                } else {
                    toastr.warning(result.msg);
                }
            }
        });
        
        // callback handler that will be called on failure
        request.fail(function (jqXHR, textStatus, errorThrown) {
            // log the error to the console
            toastr.error("The following error occured: " + textStatus, errorThrown);
        });
        
        // callback handler that will be called regardless
        // if the request failed or succeeded
        request.always(function () {
            // reenable the inputs
            inputs.prop("disabled", false);
        });
    }
});
JS;
$this->inlineScript()->captureEnd();
?>