<?php
$title = $this->translate("Referral Summary Management");
$this->headTitle($title);
?>
<!-- BEGIN SIDEBAR -->
<?php echo $this->partial('backend_sidebar', array('view' => 'bank', 'action' => 'referral-summary')); ?>
<!-- END SIDEBAR -->
<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
    <div class="page-content">
        <!-- BEGIN PAGE BAR -->
        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <a href="<?php echo $this->url('admin') ?>"><?php echo $this->translate("Dashboard") ?></a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="<?php echo $this->url('admin/bank') ?>"><?php echo $this->translate("Banks") ?></a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <span><?php echo $this->translate("Referral Summary") ?></span>
                </li>
            </ul>
        </div>
        <!-- END PAGE BAR -->
        
        <div class="row">
            <div class="col-md-12">
                <div class="portlet light portlet-fit portlet-datatable bordered">
                    <div class="portlet-title">
                        <div class="caption font-dark">
                            <i class="fa fa-money font-dark"></i>
                            <span class="caption-subject bold uppercase"> <?php echo $title ?></span>
                        </div>
                        <div class="actions">
                            <div class="btn-group btn-group-devided" data-toggle="buttons">
                                <a href="javascript:;" onclick="window.history.back()" class="btn btn-transparent grey-salsa btn-outline btn-circle btn-sm"> <?php echo $this->translate("Back") ?>
                                    <i class="fa fa-history"></i>
                                </a>
                            </div>
                            <div class="btn-group hide">
                                <a class="btn red btn-outline btn-circle" href="javascript:;" data-toggle="dropdown">
                                    <i class="fa fa-share"></i>
                                    <span class="hidden-xs"> <?php echo $this->translate("Tools") ?> </span>
                                    <i class="fa fa-angle-down"></i>
                                </a>
                                <ul class="dropdown-menu pull-right" id="table_page_tools">
                                    <li>
                                        <a href="javascript:;" data-action="0" class="tool-action">
                                            <i class="icon-check"></i> <?php echo $this->translate("Paid") ?></a>
                                    </li>
                                    <li class="divider"> </li>
                                    <li>
                                        <a href="javascript:;" data-action="1" class="tool-action">
                                            <i class="icon-refresh"></i> <?php echo $this->translate("Reload") ?></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <table class="table table-striped table-bordered table-hover table-checkable" id="table_page">
                            <thead>
                                <tr>
                                    <th>
                                        <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                            <input type="checkbox" class="group-checkable" data-set="#table_page .checkboxes" />
                                            <span></span>
                                        </label>
                                    </th>
                                    <th> <?php echo $this->translate("Referrer") ?> </th>
                                    <th> <?php echo $this->translate("Referree") ?> </th>
                                    <th> <?php echo $this->translate("Bank Apply") ?> </th>
                                    <th> <?php echo $this->translate("Loan Type") ?> </th>
                                    <th> <?php echo $this->translate("Amt") ?> </th>
                                    <th> <?php echo $this->translate("Date") ?> </th>
                                    <th> <?php echo $this->translate("Referrer Amt") ?> </th>
                                    <th> <?php echo $this->translate("Actions") ?> </th>
                                    <th> <?php echo $this->translate("Status") ?> </th>
                                </tr>
                            </thead>
                            <tbody>
                            <?php if(count($this->referrals) > 0): ?>
                            <?php foreach($this->referrals as $referral): 
                            $user = $this->user(array("id" => $referral->getUserId()));
                            switch ($referral->getType()) {
                                case 'business_loan':
                                    $business_loan = $this->business_loan(array("id" => $referral->getApplication()));
                                    switch ($business_loan->getType()) {
                                        case "business_term_loan":
                                            $type = "Business Term Loan";
                                        break;
                                        
                                        default:
                                            $type = "Business Term Loan";
                                        break;
                                    }
                                    $business_loan_package = $this->business_loan_package(array("id" => $business_loan->getLoanId()));
                                    $bank_id = $business_loan_package->getBankId();
                                    $referree = $this->user(array("id" => $business_loan->getUserId())); 
                                break;
                                
                                case 'property_loan':
                                    $property_loan = $this->property_loan(array("id" => $referral->getApplication()));
                                    switch ($property_loan->getType()) {
                                        case "home_loan":
                                            $type = "Home Loan";
                                        break;
                                        
                                        default:
                                            $type = "Home Loan";
                                        break;
                                    }
                                break;
                            }
                            $bank = $this->bank(array("id" => $bank_id));
                            ?>
                                <tr>
                                    <td>
                                        <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                            <input type="checkbox" class="checkboxes" value="<?php echo $referral->getId() ?>" />
                                            <span></span>
                                        </label>
                                    </td>
                                    <td><?php echo $user->getDisplayName(); ?></td>
                                    <td><?php echo $referree->getDisplayName(); ?></td>
                                    <td><?php echo $bank->getName(); ?></td>
                                    <td><?php echo $type; ?></td>
                                    <td><?php echo number_format($business_loan->getLoanAmount()); ?></td>
                                    <td><?php echo date("d-m-Y H:i", strtotime($referral->getDateAdded())); ?></td>
                                    <td><?php echo $referral->getCredit(); ?></td>
                                    <td>
                                        <?php if($referral->getStatus() != 4): ?>
                                        <a href="<?php echo $this->url("admin/bank", array("action" => "edit-referral", "id" => $referral->getId())) ?>" class="btn btn-xs red-thunderbird"><i class="fa fa-money"></i> <?php echo $this->translate("Paid") ?></a>
                                        <?php endif; ?>
                                    </td>
                                    <td>
                                    <?php
                                    switch ($referral->getStatus()) {
                                        case 4:
                                            echo $this->translate("Paid");
                                        break;
                                        
                                        default:
                                            echo $this->translate("Pending Transfer");
                                        break;
                                    }
                                    ?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            <?php endif;?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>            
</div>
<!-- END CONTENT -->
<?php
$offStyle = 12;
$offScript = 10;
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/datatables/datatables.min.css'));
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css'));
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/js/datatable.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/datatables/datatables.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js'));
$this->inlineScript()->offsetSetFile(100, $this->basePath('assets/js/custom_functions.js'));
$this->inlineScript()->captureStart();
echo <<<JS
// handle set status
function set_status(button, status) {
    var id = $(button).data("id");
    var ids = [id];
    switch(status) {
        case 1:
            action = "approved";
        break;
        
        case 2:
            action = "cancelled";
        break;
        
        case 3:
            action = "rejected";
        break;
        
        case 4:
            action = "paid";
        break;
        
        default:
            action = "pending";
    }
    $.ajax({
        type: "POST",
        url: full_url+"/admin/bank/set-status-referral",
        data: {ids: ids, action: action},
        dataType: 'json',
        beforeSend: function() {
            App.blockUI({boxed: true});
        },
        success: function(itemJson) {
            App.unblockUI();      
            if(itemJson['success']) {
                toastr.success(itemJson.msg);
                setTimeout(function(){ window.location.reload(); }, 1500);
            } else {
                toastr.error(itemJson.msg);
            }
        },
        error : function(xhr, status){
            console.log(status);
        },
    });         
}

jQuery.extend( jQuery.fn.dataTableExt.oSort, {
    "date-sg-pre": function ( a ) {
        var sgDatea = a.split('-');
        var sgDateb = sgDatea[2].split(' ');
        var sgDatec = sgDateb[1].split(':');
        return (sgDateb[0] + sgDatea[1] + sgDatea[0] + sgDatec[0] + sgDatec[1] ) * 1;
    },
        
    "date-sg-asc": function ( a, b ) {
        return ((a < b) ? -1 : ((a > b) ? 1 : 0));
    },
        
    "date-sg-desc": function ( a, b ) {
        return ((a < b) ? 1 : ((a > b) ? -1 : 0));
    }
});

jQuery(document).ready(function() {
    var table = $('#table_page');
    table.dataTable({
        // Internationalisation. For more info refer to http://datatables.net/manual/i18n
        "language": {
            "aria": {
                "sortAscending": ": activate to sort column ascending",
                "sortDescending": ": activate to sort column descending"
            },
            "emptyTable": "No data available in table",
            "info": "Showing _START_ to _END_ of _TOTAL_ records",
            "infoEmpty": "No records found",
            "infoFiltered": "(filtered1 from _MAX_ total records)",
            "lengthMenu": "Show _MENU_",
            "search": "Search:",
            "zeroRecords": "No matching records found",
            "paginate": {
                "previous":"Prev",
                "next": "Next",
                "last": "Last",
                "first": "First"
            }
        },
        
        buttons: [
            {
                text: 'Paid',
                className: 'btn default',
                action: function ( e, dt, node, config ) {
                    var selectedIds = [];
                    $("input[class=checkboxes]:checked").each(function() {
                        selectedIds.push($(this).val());
                    });
                    if(selectedIds.length > 0) {
                        $.ajax({
                            type: "POST",
                            url: full_url+"/admin/bank/set-status-referral",
                            data: {ids: selectedIds, action: 'paid'},
                            dataType: 'json',
                            beforeSend: function() {
                                App.blockUI({boxed: true});
                            },
                            success: function(itemJson) {
                                App.unblockUI();      
                                if(itemJson['success']) {
                                    toastr.success(itemJson.msg);
                                    setTimeout(function(){ window.location.reload(); }, 1500);
                                } else {
                                    toastr.error(itemJson.msg);
                                }
                            },
                            error : function(xhr, status){
                                console.log(status);
                            },
                        });
                    } else {
                        toastr.warning("No row checked in table.");
                    }
                }
            },
            {
                text: 'Reload',
                className: 'btn default',
                action: function ( e, dt, node, config ) {
                    window.location.reload();
                }
            }
        ],
        
        // setup responsive extension: http://datatables.net/extensions/responsive/
        responsive: true,

        "columnDefs": [ {
            "targets": 0,
            "orderable": false,
            "searchable": false
        }],
        
        "lengthMenu": [
            [25, 50, 100, -1],
            [25, 50, 100, "All"] // change per page values here
        ],
        // set the initial value
        "pageLength": 25,            
        "pagingType": "bootstrap_full_number",
        "columnDefs": [
            {"orderable": false,"targets": [0,8,9]},
            {"type": "date-sg", "targets": 6 }
        ],
        "order": [
            [6, "desc"]
        ] // set first column as a default sort by asc
    });
    
    var tableWrapper = jQuery('#table_page_wrapper');
    table.find('.group-checkable').change(function () {
        var set = jQuery(this).attr("data-set");
        var checked = jQuery(this).is(":checked");
        jQuery(set).each(function () {
            if (checked) {
                $(this).prop("checked", true);
                $(this).parents('tr').addClass("active");
            } else {
                $(this).prop("checked", false);
                $(this).parents('tr').removeClass("active");
            }
        });
    });
    
    table.on('change', 'tbody tr .checkboxes', function () {
        $(this).parents('tr').toggleClass("active");
    });
    
    // handle datatable custom tools
    $('#table_page_tools > li > a.tool-action').on('click', function() {
        var action = $(this).attr('data-action');
        table.DataTable().button(action).trigger();
    });
});
JS;
$this->inlineScript()->captureEnd();
?>