<?php
$title = $this->translate("Successfully fail");
$this->headTitle($title);
?>
<div class="main">
    <div class="container">
        <div class="row margin-bottom-40">
            <div class="col-md-12 text-center">
                <div class="content-page">
                    <h1><?php echo $title ?></h1>
                    <img src="<?php echo $this->basePath('assets/img/check-false.png');?>" title="<?php echo $title ?>" alt="<?php echo $title ?>" />
    				<h3><?php echo $this->translate("Thanks you for your application") ?></h3>
    				<p><?php echo $this->translate("You can register again") ?></p>
                </div>
            </div>
        </div>
    </div>
</div>