<?php
$title = $this->translate("Edit Page");
$this->headTitle($title);
?>
<!-- BEGIN SIDEBAR -->
<?php echo $this->partial('backend_sidebar', array('view' => 'page', 'action' => 'page')); ?>
<!-- END SIDEBAR -->
<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
    <div class="page-content">
        <!-- BEGIN PAGE BAR -->
        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <a href="<?php echo $this->url('admin') ?>"><?php echo $this->translate("Dashboard") ?></a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="<?php echo $this->url('admin/admin_page') ?>"><?php echo $this->translate("Pages") ?></a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <span><?php echo $this->translate("Edit Page") ?></span>
                </li>
            </ul>
        </div>
        <!-- END PAGE BAR -->
        <div class="row">
            <div class="col-md-12">
                <div class="portlet light bordered form-fit">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="icon-pin"></i>
                            <span class="caption-subject sbold uppercase"><?php echo $this->translate($title) ?></span>
                        </div>
                    </div>
                    <div class="portlet-body form">
                        <!-- BEGIN FORM-->
                        <form action="<?php echo $this->url("admin/admin_page", array('action' => "edit", "id" => $this->post->getId())) ?>" id="form_post" class="form-horizontal form-bordered">
                            <div class="form-body">
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Title") ?><span class="required"> * </span></label>
                                    <div class="col-md-6">
                                        <input type="text" name="post_title" data-required="1" class="form-control" value="<?php echo $this->post->getPostTitle() ?>" /> 
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Seo") ?><span class="required"> * </span></label>
                                    <div class="col-md-6">
                                        <input type="text" name="seo" class="form-control" value="<?php echo $this->post->getSeo() ?>" /> 
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Date") ?></label>
                                    <div class="col-md-6">
                                        <input type="text" name="post_date" class="form-control date-picker" data-date-format="dd/mm/yyyy" value="<?php echo date("d/m/Y", strtotime($this->post->getPostDate())) ?>" /> 
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Excerpt") ?></label>
                                    <div class="col-md-9">
                                        <textarea name="post_excerpt" class="form-control" rows="4"><?php echo $this->post->getPostExcerpt() ?></textarea>
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Content") ?></label>
                                    <div class="col-md-9">
                                        <textarea name="post_content" class="form-control tinymce"><?php echo $this->post->getPostContent() ?></textarea>
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Featured Image") ?></label>
                                    <div class="col-md-6">
                                        <div class="fileinput fileinput-new" data-provides="fileinput">
                                            <div class="input-group">
                                                <div class="form-control uneditable-input input-fixed" data-trigger="fileinput">
                                                    <i class="fa fa-camera fileinput-exists"></i>&nbsp;
                                                    <span class="fileinput-filename"> </span>
                                                </div>
                                                <span class="input-group-addon btn default btn-file">
                                                    <span class="fileinput-new"> <?php echo $this->translate("Select file") ?> </span>
                                                    <span class="fileinput-exists"> <?php echo $this->translate("Change") ?> </span>
                                                    <input type="file" name="photoupload" id="photoupload" />
                                                    <input type="hidden" name="featured_image" id="featured_image" value="<?php echo $this->post->getFeaturedImage() ?>" />
                                                </span>
                                                <a href="javascript:;" class="input-group-addon btn red fileinput-exists" data-dismiss="fileinput"> <?php echo $this->translate("Remove") ?> </a>
                                            </div>
                                        </div>
                                        <?php
                                        if ($this->post->getFeaturedImage()) {
                                            $post_image = $this->post->getFeaturedImage();
                                            if (!file_exists('data/image/m_'.$post_image)) {
                                                $image_src = 'data/image/'.$post_image;
                                            } else {
                                                $image_src = 'data/image/m_'.$post_image;
                                            }
                                        } else {
                                            $image_src = 'data/image/no-image-128.png';
                                        }
                                        ?>
                                        <img id="photo" alt="featured image" src="<?php echo $this->basePath($image_src) ?>" width="128" height="128" />
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Featured") ?></label>
                                    <div class="col-md-6">
                                        <select name="featured" class="form-control">
                                            <option value="0"<?php if($this->post->getFeatured() == 0) echo ' selected'; ?>><?php echo $this->translate("No") ?></option>
                                            <option value="1"<?php if($this->post->getFeatured() == 1) echo ' selected'; ?>><?php echo $this->translate("Yes") ?></option>
                                        </select>
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="control-label col-md-3"><?php echo $this->translate("Attachment") ?></label>
                                    <div class="col-md-6">
                                        <div class="fileinput fileinput-new" data-provides="fileinput">
                                            <div class="input-group">
                                                <div class="form-control uneditable-input input-fixed" data-trigger="fileinput">
                                                    <i class="fa fa-files fileinput-exists"></i>&nbsp;
                                                    <span class="fileinput-filename"> </span>
                                                </div>
                                                <span class="input-group-addon btn default btn-file">
                                                    <span class="fileinput-new"> <?php echo $this->translate("Select file") ?> </span>
                                                    <span class="fileinput-exists"> <?php echo $this->translate("Change") ?> </span>
                                                    <input type="file" name="attachment_upload" id="attachment_upload" />
                                                </span>
                                            </div>
                                        </div>
                                        <ul id="attachment_files">
                                            <?php
                                            $attachmens = \Zend\Json\Json::decode ( $this->post->getAttachment() );
                                            $attachmen_value = "";
                                            if(count($attachmens) > 0) {
                                                foreach ($attachmens as $attachment) {
                                                    $attachmen_value .= $attachment.",";
                                                ?>
                                                <li data-filename="<?php echo $attachment; ?>"><?php echo $attachment; ?><a href="javascript:;" onclick="delete_attachment(this)"><i class="fa fa-remove font-red"></i></a></li>
                                                <?php
                                                }
                                            }
                                            ?>
                                        </ul>
                                        <input type="hidden" name="attachment" id="attachment" value="<?php echo $attachmen_value; ?>" />
                                    </div>
                                </div>
                            </div>
                            <div class="form-actions">
                                <div class="row">
                                    <div class="col-md-offset-3 col-md-9">
                                        <button type="submit" class="btn red-thunderbird"><i class="fa fa-check"></i> <?php echo $this->translate("Submit") ?></button>
                                        <button type="button" class="btn btn-outline" onclick="cancel('admin/post')"> <?php echo $this->translate("Cancel") ?></button>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <!-- END FORM-->
                    </div>
                </div>
            </div>
        </div>
    </div>            
</div>
<!-- END CONTENT -->
<?php
$offStyle = 12;
$offScript = 12;
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/bootstrap-fileinput/bootstrap-fileinput.css'));
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css'));
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/sweetalert2/sweetalert2.css'));
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/dropzone/basic.min.css'));
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/dropzone/dropzone.min.css'));
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/css/simplePagination.css'));
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/mlib/css/mlib.css'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/bootstrap-fileinput/bootstrap-fileinput.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/tinymce/js/tinymce/tinymce.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/dropzone/dropzone.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/js/jquery.simplePagination.js'));
$this->inlineScript()->offsetSetFile(30, $this->basePath('assets/plugins/jquery-validation/js/jquery.validate.min.js'));
$this->inlineScript()->offsetSetFile(31, $this->basePath('assets/plugins/jquery-validation/js/additional-methods.min.js'));
$this->inlineScript()->offsetSetFile(32, $this->basePath('assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js'));
$this->inlineScript()->offsetSetFile(33, $this->basePath('assets/plugins/mlib/js/mlib.js'));
$this->inlineScript()->offsetSetFile(34, $this->basePath('assets/plugins/sweetalert2/sweetalert2.min.js'));
$this->inlineScript()->offsetSetFile(100, $this->basePath('assets/js/custom_functions.js'));
$this->inlineScript()->captureStart();
echo <<<JS
$('#photoupload').on("change", function(){
    var form = document.getElementById('form_post');
    var fileInput = document.getElementById('photoupload');
    var file = fileInput.files[0];
    var formData = new FormData();
    formData.append('file', file);
    var xhr = new XMLHttpRequest();
    xhr.onreadystatechange = function() {
        if (xhr.readyState == 4) {
            var result = $.parseJSON(xhr.responseText);
            if(result.success === true) {
                toastr.success("Photo uploaded.");
                $('#photo').attr("src", full_url + result.src);
                $('#featured_image').val(result.name);
            } else {
                toastr.warning(result.msg);
            } 
        }
    }
    // Add any event handlers here...
    xhr.open('POST', full_url + "/admin/page/change-image", true);
    xhr.send(formData);
});

$('#attachment_upload').on("change", function(){
    var fileInput = document.getElementById('attachment_upload');
    var file = fileInput.files[0];
    var formData = new FormData();
    formData.append('file', file);
    var xhr = new XMLHttpRequest();
    xhr.onreadystatechange = function() {
        if (xhr.readyState == 4) {
            var result = $.parseJSON(xhr.responseText);
            if(result.success === true) {
                var all_name = $('input[name=attachment]').val();
                all_name = all_name+","+result.name;
                $('input[name=attachment]').val(all_name);
                
                $("#attachment_files").append('<li data-filename="'+result.name+'">'+result.name+'<a href="javascript:;" onclick="delete_attachment(this)"><i class="fa fa-remove font-red"></i></a></li>');
                toastr.success("File uploaded.");
            } else {
                toastr.warning(result.msg);
            } 
        }
    }
    // Add any event handlers here...
    xhr.open('POST', full_url + "/admin/page/upload-attachment", true);
    xhr.send(formData);
});

function delete_attachment(button) {
    var name = $(button).parent().attr('data-filename');
    if(name) {
        $.ajax({
            type: 'POST',
            url: full_url + '/admin/page/delete-attachment',
            data: {name:name}, 
            success: function(data) {
                if(data.success) {
                    $(button).parent().remove();
                    var curent='';  
                    $('#attachment_files > li').each(function(){
                        curent = curent+','+$(this).attr('data-filename'); 
                    });
                    $('input[name=attachment]').val(curent); 
                } 
            },
            error: function(xhr) { // if error occured
                toastr.error("Error occured. Please try again.");
            },
            dataType: 'json'  
        });
    }
}
        
tinymce.baseURL = "{$this->basePath('assets/plugins/tinymce/js/tinymce')}";
tinymce.PluginManager.add('mce_mlib', function(editor, url) {
	var tinyedit_id = editor.id;
    editor.addButton('mce_mlib', {
        text: 'Insert Media',
        icon: false,
        id: 'mediabtn_'+tinyedit_id,
        icon : 'image',
        onclick: function() {
            var newid = '#mediabtn_'+tinyedit_id;
            if($(newid).attr('mboxmce_init')===undefined){
                $(newid).attr('mboxmce_init', tinyedit_id);
                $(newid).mlibready({allowed:'jpg,png,gif,jpeg,txt,zip,rar,doc,docx,ppt,pptx,xls,xlsx,csv,tar,gz', mcename:tinyedit_id, returnas:'all'});
                $(newid).trigger('click');
			}
        }
    });

    // Adds a menu item
    editor.addMenuItem('mce_mlib', {
        text: 'Insert Media',
        context: 'file',
		icon : 'image',
		id: 'mediabtn_'+tinyedit_id,
        onclick: function() {
			var newid = '#mediabtn_'+tinyedit_id;
			if($(newid).attr('mboxmce_init')===undefined){
			$(newid).attr('mboxmce_init', tinyedit_id);
			$(newid).mlibready({allowed:'jpg,png,gif,jpeg,txt,zip,rar,doc,docx,ppt,pptx,xls,xlsx,csv,tar,gz', mcename:tinyedit_id, returnas:'all'});
			$(newid).trigger('click');
			}
        }
    });
});
tinymce.init({
    selector: '.tinymce',
    height: 300,
    menubar: false,
    statusbar: false,
    plugins: 'mce_mlib advlist table link textcolor code',
    toolbar: 'mce_mlib | advlist | table | link | styleselect | bold italic | alignment | alignmentv2 | fontsizeselect | forecolor | backcolor | code',
    fontsize_formats: '8px 10px 12px 14px 18px 24px 36px',
    setup: function (editor) {
        editor.on('change', function () {
            editor.save();
        });
    }
});

$('input[name=seo]').on('focus blur', function() {
    var string              = $(this).val() ? $(this).val() : $('input[name=post_title]').val();
    var strReplaceAll       = make_friendly_seo(string);
    var intIndexOfMatch     = strReplaceAll.indexOf(' ');
    while(intIndexOfMatch != -1){
        strReplaceAll       = strReplaceAll.replace(' ', '-');
        intIndexOfMatch     = strReplaceAll.indexOf(' ');
    }
    string = strReplaceAll;
    for(var i = 0, output = '', valid='-0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'; i < string.length; i++) {
        if(valid.indexOf(string.charAt(i)) != -1) {
            output += string.charAt(i);
        }
    }
    $(this).val(output.toLowerCase());
});

var form = $('#form_post');
form.validate({
    errorElement: 'span', //default input error message container
    errorClass: 'help-block', // default input error message class
    focusInvalid: false, // do not focus the last invalid input
    ignore: "",
    rules: {
        post_title: {
            required: true
        },
        seo: {
            required: true
        }
    },
    
    highlight: function(element) { // hightlight error inputs
        $(element)
            .closest('.form-group').addClass('has-error'); // set error class to the control group
    },

    success: function(label) {
        label.closest('.form-group').removeClass('has-error');
        label.remove();
    },

    errorPlacement: function(error, element) {
        error.insertAfter(element);
    },

    submitHandler: function (form) {
        // setup some local variables
        var form = $(form);
        
        // let's select and cache all the fields
        var inputs = form.find("input, select, button, textarea");
        
        // serialize the data in the form
        var serializedData = form.serialize();
        
        // let's disable the inputs for the duration of the ajax request
        inputs.prop("disabled", true);
        
        // fire off the request to /form.php

        request = $.ajax({
            url: form.attr("action"),
            type: "post",
            data: serializedData
        });
        
        // Clear Message
        $('#form_post .form-group').removeClass('has-error');
        $('#form_post .help-block, #form_post .alert').remove();
        
        // callback handler that will be called on success
        request.done(function (response, textStatus, jqXHR) {
            var result = $.parseJSON(response);
            if(result.error) {
                toastr.error("Something error. Please check.");
                if(result.error.seo){
                    $('#form_post input[name=seo]').parent().addClass('has-error');
                    $('#form_post input[name=seo]').after('<span id="seo-error" class="help-block">' + result.error.seo + '</span>');
                }
            } else {
                if(result.success) {
                    toastr.success(result.msg);
                    setTimeout(function(){ window.location.href = full_url+'/admin/page'; }, 1500);
                } else {
                    toastr.warning(result.msg);
                }
            }
        });
        
        // callback handler that will be called on failure
        request.fail(function (jqXHR, textStatus, errorThrown) {
            // log the error to the console
            toastr.error("The following error occured: " + textStatus, errorThrown);
        });
        
        // callback handler that will be called regardless
        // if the request failed or succeeded
        request.always(function () {
            // reenable the inputs
            inputs.prop("disabled", false);
        });
    }
});
JS;
$this->inlineScript()->captureEnd();
?>