<?php
$tooltip=$this->tooltip_for_property(array('id'=>2));
$tooltip=json_decode($tooltip->getValue());
$slider_loan_tenture = '$slider_loan_tenture';
$slider_loan_percent = '$slider_loan_percent';
$total_interest_for_years = $this->total_interest_for_years ? $this->total_interest_for_years : 2;
?>
<div class="container">
  <div class="row">
      <div id="column-left" class="col-md-3 col-xs-12">
          <div class="loan-sidebar box-featured-bank">
              <div class="portlet light loan-sidebar-portlet featured-bank lowest-interest">
                  <div class="loan-title-portlet">
                  <h3><?php echo $this->translate("Filter"); ?></h3></div>
                  <div class="loan-filter">
                    <p><?php echo $this->translate("Click the Refresh button below after you make any changes") ?>.</p>
                  </div>
                  <div class="loan-filter">
                      <label><?php echo $this->translate("Loan Type") ?> <a href="javascript:;" class="tooltip-icon popovers pull-right" data-trigger="hover" data-placement="right" data-container="body" data-content="<?php echo $tooltip->loan_type?>"><i class="fa fa-question-circle"></i></a></label>
                      <select name="preferred_rate_package" class="form-control">
                          <option value="Fixed"<?php if($this->preferred_rate_package === 'Fixed') echo " selected" ?>><?php echo $this->translate("Fixed") ?></option>
                          <option value="Floating"<?php if($this->preferred_rate_package === 'Floating') echo " selected" ?>><?php echo $this->translate("Floating") ?></option>
                      </select>
                  </div>
                  <div class="loan-filter">
                      <label><?php echo $this->translate("Based on total interest for") ?> <a href="javascript:;" class="tooltip-icon popovers pull-right" data-trigger="hover" data-placement="right" data-container="body" data-content="<?php echo $tooltip->total_interest?>"><i class="fa fa-question-circle"></i></a></label>
                      <select name="total_interest_for_years" class="form-control">
                          <option value="1"<?php if($this->$total_interest_for_years == 1) echo ' selected'; ?>><?php echo $this->translate("1 year") ?></option>
                          <option value="2"<?php if($this->$total_interest_for_years == 2) echo ' selected'; ?>><?php echo $this->translate("2 years") ?></option>
                          <option value="3"<?php if($this->$total_interest_for_years == 3) echo ' selected'; ?>><?php echo $this->translate("3 years") ?></option>
                          <option value="4"<?php if($this->$total_interest_for_years == 4) echo ' selected'; ?>><?php echo $this->translate("4 years") ?></option>
                          <option value="5"<?php if($this->$total_interest_for_years == 5) echo ' selected'; ?>><?php echo $this->translate("5 years") ?></option>
                          <option value="10"<?php if($this->$total_interest_for_years == 10) echo ' selected'; ?>><?php echo $this->translate("10 years") ?></option>
                      </select>
                  </div>
                  <div class="loan-filter">
                      <div class="md-checkbox-list">
                          <div class="md-checkbox">
                              <input type="checkbox" name="no_lock_in_only" id="checkbox_no_lock_in_only" class="md-check" value="1"<?php if($this->no_lock_in_only == 1) echo ' checked'; ?>>
                              <label for="checkbox_no_lock_in_only">
                                  <span></span>
                                  <span class="check"></span>
                                  <span class="box"></span> <?php echo $this->translate("No Lock-in Loans Only") ?>
                              </label>
                              <a href="javascript:;" class="tooltip-icon popovers pull-right" data-trigger="hover" data-placement="right" data-container="body" data-content='<?php echo $tooltip->lock_in?>'><i class="fa fa-question-circle"></i></a>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div class="box-featured-bank">
              <div class="loan-filter">
                  <label><?php echo $this->translate("Loan Amount") ?> <a href="javascript:;" class="tooltip-icon popovers pull-right" data-trigger="hover" data-placement="right" data-container="body" data-content="<?php echo $tooltip->loan_amount?>"><i class="fa fa-question-circle"></i></a></label>
                  <div class="amount">$<span id="loan-amount-label"><?php echo number_format($this->loan_amount) ?></span></div>
                  <div class="percentage"><span class="loan-percentage-label"></span><?php echo $this->translate("% of purchase price") ?></div>
              </div>
              <div class="loan-filter">
                  <label><?php echo $this->translate("Purchase Price") ?></label>
                  <div class="input-group">
                      <span class="input-group-addon">
                          <i><?php echo $this->translate("Purchase Price ($)") ?></i>
                      </span>
                      <input type="text" name="purchase_price" class="form-control" value="<?php echo $this->purchase_price ?>">
                  </div>
              </div>
              <div class="loan-filter">
                  <label>
                      <?php echo $this->translate("Loan %") ?>
                      <span class="pull-right"><span class="loan-percentage-label"><?php echo $this->loan_percent ?></span>%</span>
                  </label>
                  <div class="slider-loan-amount" data-min="10" data-max="80" data-value="<?php echo $this->loan_percent ?>" data-soft-cap="80"></div>
              </div>
              <div class="loan-filter">
                  <label>
                      <?php echo $this->translate("Loan Tenure") ?>
                      <span class="pull-right"><span class="loan-tenure-label"><?php echo $this->loan_tenure ?></span> years</span>
                  </label>
                  <div class="slider-loan-tenure" data-min="5" data-max="35" data-value="<?php echo $this->loan_tenure ?>" data-soft-cap="30"></div>
              </div>
              <div class="loan-filter">
                  <input type="hidden" name="loan_amount" value="<?php echo $this->loan_amount ?>" />
                  <input type="hidden" name="loan_tenure" value="<?php echo $this->loan_tenure ?>" />
                  <input type="hidden" name="loan_percent" value="<?php echo $this->loan_percent ?>" />
                  <button type="button" class="btn blue btn-block btn-lg ladda-button refresh-btn" onclick="Loan.filter_loan(this)" data-style="expand-left"><i class="fa fa-refresh"></i> <?php echo $this->translate("Refresh Results") ?></button>
              </div>
          </div>
      </div>
      <div class="loan-content col-md-9 col-xs-12">
        <div class="portlet light loan-content-portlet">
          <div class="loan-title-portlet form-wizard"><h4><?php echo $this->translate("Top Floating Rates"); ?></h4></div>
          <p><?php echo $this->translate("Home loans displayed below are ranked according to interest rates. You can click on the product box to view more details or modify your search criteria on the left"); ?></p>

          <div class="filter-table-head hidden-sm hidden-xs">
            <ul>
              <li>
                  <aside class="head-title">
                      <div class="name"><?php echo $this->translate("Bank") ?></div>
                  </aside>
              </li><!--
              --><li>
                  <aside class="head-title">
                      <div class="name"><?php echo $this->translate("Interest") ?></div>
                      <div class="explain"><a href="javascript:;" class="tooltip-icon2 popovers" data-trigger="hover" data-container="body" data-content="<?php echo $this->setting()->interest_property_loan ?>" data-html="true"><i class="fa fa-question-circle"></i></a></div>
                      <div class="sort" data-field="interest"><a href="javascript:;" onclick="Loan.sort(this)"><i class="fa fa-long-arrow-down"></i></a></div>
                  </li><!--
              --><li>
                  <aside class="head-title">
                      <div class="name"><?php echo $this->translate("Monthly Repayment") ?><span></span></div>
                      <div class="explain"><a href="javascript:;" class="tooltip-icon2 popovers" data-trigger="hover" data-container="body" data-content="<?php echo $this->setting()->monthly_repayment ?>" data-html="true"><i class="fa fa-question-circle"></i></a></div>
                      <div class="sort" data-field="monthly_repayment"><a href="javascript:;" onclick="Loan.sort(this)"><i class="fa fa-long-arrow-down"></i></a></div>
                  </aside>
                  </li><!--
              --><li>
                  <aside class="head-title">
                      <div class="name"><?php echo $this->translate("Total Interest Payable") ?></div>
                      <div class="explain"><a href="javascript:;" class="tooltip-icon2 popovers" data-trigger="hover" data-container="body" data-content="<?php echo $this->setting()->total_interest_payable ?>" data-html="true"><i class="fa fa-question-circle"></i></a></div>
                      <div class="sort" data-field="total_interest_payable"><a href="javascript:;" onclick="Loan.sort(this)"><i class="fa fa-long-arrow-down"></i></a></div>
                  </aside>
                 </li><!--
              --><li>
                  <aside class="head-title">
                      <div class="name"><?php echo $this->translate("Type") ?></div>
                      <div class="explain"><a href="javascript:;" class="tooltip-icon2 popovers" data-trigger="hover" data-container="body" data-content="<?php echo $this->setting()->type_property_loan ?>" data-html="true"><i class="fa fa-question-circle"></i></a></div>
                      <div class="sort" data-field="type"><a href="javascript:;" onclick="Loan.sort(this)"><i class="fa fa-long-arrow-down"></i></a></div>
                  </aside>
              </li>
            </ul>
          </div>

          <div class="results-container filters-table-container" id="results">
              <?php if(count($this->loans) > 0): ?>
                <div class="filters-table-body filters-table-property">
                  <?php foreach ($this->loans as $key => $loan): ?>
                    <?php
                    $bank = $this->bank(array("id" => $loan->getBankId()));
                    $bank_color = $bank->getColor() ? $bank->getColor() : "#FFFFFF";
                    ?>
                    <div class="portlet mt-element-ribbon light portlet-fit no-shadow filters-content not-sponsored">
                      <div class="row-header" style="background-color: <?php echo $bank_color;?>;">
                        <h4 class="bank-title" style="background-color: <?php echo $bank_color; ?>">
                          <a href="#"><?php echo $loan->getTitle(); ?> <?php echo $loan->getPromotions(); ?></a>
                        </h4>
                      </div>
                      <div class="filters-content not-sponsored">
                        <?php
                        $total_interest_for_years = $this->total_interest_for_years ? $this->total_interest_for_years : 2;
                        $loan_amount = $this->loan_amount;
                        $int_rates = $loan->getIntYear2();

                        // Monthly payment = [ r + r / ( (1+r) ^ months -1) ] x principal loan amount
                        // Where: r = decimal rate / 12.
                        $r = ($int_rates / 100) / 12;
                        $monthly_payment = ($r + $r / (pow(1 + $r, ($total_interest_for_years * 12)) -1 ) ) * $loan_amount;
                        ?>
                        <div class="row loan-info row-content row-content-1">
                          <div class="col-md-2">
                            <div class="bank-logo">
                                <?php
                                $dir_logo = 'data/bank/'.$loan->getBankId().'/m_'.$bank->getLogo();
                                if(!file_exists($dir_logo)) {
                                    $dir_logo = 'data/image/no-image-64.png';
                                }
                                ?>
                                <img src="<?php echo $this->basePath($dir_logo); ?>" />
                            </div>
                          </div>
                          <div class="col-md-3">
                            <div class="box__interest">
                              <span class="interest"><b><?php echo $int_rates ?>%</b>
                              <?php echo $this->translate("Avg Interest Rate") ?>
                              <div class="sub-info"><?php echo $total_interest_for_years ?><?php echo $this->translate(" Year Average") ?></div></span>
                            </div>
                          </div>
                          <div class="col-md-3">
                            <div class="box__interest">
                              <span class="interest">
                                <b>$<?php echo number_format($monthly_payment); ?></b>
                                <?php echo $this->translate("Monthly Instalments") ?>
                                <div class="sub-info"><?php echo $total_interest_for_years ?><?php echo $this->translate(" Year Average") ?></div>
                              </span>
                            </div>
                          </div>
                          <div class="col-md-2">
                              <div class="lockin-period box__interest">
                                <span class="interest"><b>
                                  <?php
                                  $lock_in_year = $loan->getLockInYear();
                                  if($lock_in_year > 0) {
                                      echo $lock_in_year.' '.$this->translate("Year");
                                  } else {
                                      echo $this->translate("No Lock-in");
                                  }
                                  ?></b>
                                  <?php echo $this->translate("Lock-In Period") ?></span>
                              </div>
                          </div>
                          <div class="col-md-2">
                              <div class="rate-type box__interest">
                                <span class="interest"><b>
                                  <?php
                                  switch ($loan->getFloatingType()) {
                                      case 'SIBOR':
                                          echo $this->translate("SIBOR");
                                      break;

                                      case 'Variable':
                                          echo $this->translate("Variable");
                                      break;

                                      case 'SOR':
                                          echo $this->translate("SOR");
                                      break;

                                      default:
                                          echo $this->translate("Fixed");
                                      break;
                                  }
                                  ?></b>
                                  <?php echo $this->translate("Rate Type") ?></span>
                              </div>
                          </div>
                        </div>

                        <!-- More information -->
                        <div class="row row-footer">
                          <div class="more-info col-md-12" style="overflow: hidden; display: none;">
                            <h3 class='title'><?php echo $this->translate("Rates & Payments") ?></h3>
                              <div class="row">
                                <!-- Rates & Payments -->
                                <div class="col-rates content-row-footer">
                                  <ul>
                                    <li>
                                      <div class="col-row-footer-3 text-center padding-left-30"><?php echo $this->translate("Period") ?></div>
                                      <div class="col-row-footer-3"><?php echo $this->translate("Rate") ?></div>
                                      <div class="col-row-footer-3 text-center"><?php echo $this->translate("Payment") ?></div>
                                      <div class="col-row-footer-1">
                                        <a data-target="#content-row-footer1" data-toggle="collapse" aria-expanded="true">
                                          <i class="fa fa-minus-circle" aria-hidden="true"></i>
                                          <i class="fa fa-plus-circle" aria-hidden="true"></i>
                                        </a>
                                      </div>
                                      <div id="content-row-footer1" class="content-row-collapse collapse in">
                                        <ul>
                                          <?php
                                          if($loan->getIntYear1() > 0) {
                                              $int_rates1 = $loan->getIntYear1();
                                              $r = ($int_rates1 / 100) / 12;
                                              $monthly_payment1 = ($r + $r / (pow(1 + $r, ($total_interest_for_years * 12)) -1 ) ) * $loan_amount;
                                              ?>
                                              <li>
                                                  <div class="col-row-footer-3"><?php echo $this->translate("Year") ?> 1</div>
                                                  <div class="col-row-footer-3"><?php echo $int_rates1 ?>%</div>
                                                  <div class="col-row-footer-3" style="color: #3498db;"><?php echo round($monthly_payment1, 3) ?>/mth</div>
                                              </li>
                                              <?php
                                          }
                                          if($loan->getIntYear2() > 0) {
                                              $int_rates2 = $loan->getIntYear2();
                                              $r = ($int_rates2 / 100) / 12;
                                              $monthly_payment2 = ($r + $r / (pow(1 + $r, ($total_interest_for_years * 12)) -1 ) ) * $loan_amount;
                                              ?>
                                              <li>
                                                  <div class="col-row-footer-3"><?php echo $this->translate("Year") ?> 2</div>
                                                  <div class="col-row-footer-3"><?php echo $int_rates2 ?>%</div>
                                                  <div class="col-row-footer-3" style="color: #3498db;"><?php echo round($monthly_payment2, 3) ?>/mth</div>
                                              </li>
                                              <?php
                                          }
                                          if($loan->getIntYear3() > 0) {
                                              $int_rates3 = $loan->getIntYear3();
                                              $r = ($int_rates3 / 100) / 12;
                                              $monthly_payment3 = ($r + $r / (pow(1 + $r, ($total_interest_for_years * 12)) -1 ) ) * $loan_amount;
                                              ?>
                                              <li>
                                                  <div class="col-row-footer-3"><?php echo $this->translate("Year") ?> 3</div>
                                                  <div class="col-row-footer-3"><?php echo $int_rates3 ?>%</div>
                                                  <div class="col-row-footer-3" style="color: #3498db;"><?php echo round($monthly_payment3, 3) ?>/mth</div>
                                              </li>
                                              <?php
                                          }
                                          if($loan->getIntYear4() > 0) {
                                              $int_rates4 = $loan->getIntYear4();
                                              $r = ($int_rates4 / 100) / 12;
                                              $monthly_payment4 = ($r + $r / (pow(1 + $r, ($total_interest_for_years * 12)) -1 ) ) * $loan_amount;
                                              ?>
                                              <li>
                                                  <div class="col-row-footer-3"><?php echo $this->translate("Year") ?> 4</div>
                                                  <div class="col-row-footer-3"><?php echo $int_rates4 ?>%</div>
                                                  <div class="col-row-footer-3" style="color: #3498db;"><?php echo round($monthly_payment4, 3) ?>/mth</div>
                                              </li>
                                              <?php
                                          }
                                          ?>

                                        </ul>
                                      </div>
                                    </li>
                                  </ul>
                                </div>
                                <!-- Feature -->
                                <h3 class="title"><?php echo $this->translate("Features") ?></h3>
                                <div class="row margin-bottom-20 feature-content">
                                  <?php echo $loan->getRemark(); ?>
                                </div>
                              </div>
                          </div>
                        </div>
                        <!-- Footer -->
                        <div class="col-md-12 more-detail footer">
                          <div class="col-md-9 col-sm-8 col-xs-12 button-gr button-gr-s">
                              <a href="javascript:void(0)" class="btn btn-more-detail"><?php echo $this->translate("Details"); ?> <i class="fa fa-angle-down"></i></a>
                              <a href="javascript:void(0)" class="btn btn-less-detail" style="display: none;"><?php echo $this->translate("Close")?> <i class="fa fa-angle-up"></i></a>
                          </div>
                          <?php
                          $class = '';
                          if(count($select) > 0) {
                              if(in_array($loan->getId(), $select)) $class = ' active';
                          }
                          ?>

                          <div class="col-md-3 col-sm-4 col-xs-12 box__apply button-gr button-gr-s1">
                            <button type="button" onclick="Loan.select(this)" data-id="<?php echo $loan->getId(); ?>" class="btn yellow-gold btn-lg btn-block ladda-button" data-style="slide-up" title="<?php echo $this->translate("Select Package"); ?>"><i class="fa fa-check-square-o"></i> <?php echo $this->translate("Select Package"); ?></button>
                          </div>
                        </div>
                      </div>
                    </div>
                  <?php endforeach;?>
                </div>
              <?php endif;?>
          </div>
        </div>
      </div>
  </div>
</div>
<?php
$offStyle = 12;
$offScript = 30;
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/jquery-ui/jquery-ui.min.css'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/jquery-ui/jquery-ui.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/jquery-easypiechart/jquery.easypiechart.min.js'));
$this->inlineScript()->offsetSetFile(100, $this->basePath('assets/js/custom3.js'));
$this->inlineScript()->captureStart();
echo <<<JS
// Handle number
Loan.integer();
Loan.sticky_footer();
Loan.load_select();

$('input[name=purchase_price]').on('blur', function(){
    $(this).parent().removeClass('focus');
}).on('focus', function(){
    $(this).parent().addClass('focus');
});

$("input[name=purchase_price]").on("keydown", function(evt) {
    var charCode = charCode = (evt.which) ? evt.which : event.keyCode;
    if(charCode == 8 || charCode == 46 ){
        return true;
    }
    return isEnterNumber(charCode);
});

$("input[name=purchase_price]").on("keyup", function() {
    var val = $(this).val();
    val = Number(val.replace(/,/g, ""));
    $(this).val(formatNumber(val, ""));
    updateLoanAmount();
});

var {$slider_loan_percent} = $(".slider-loan-amount").slider({
    value: $(".slider-loan-amount").data("value"),
    min: $(".slider-loan-amount").data("min"),
    max: $(".slider-loan-amount").data("max"),
    orientation: "horizontal",
    animate: !0,
    range: "min",
    slide: function(event, ui) {
        $(".loan-percentage-label").html(ui.value);
        $("input[name=loan_percent]").val(ui.value);
    },
    change: function(event, ui) {
        updateLoanAmount();
    }
});

var {$slider_loan_tenture} = $(".slider-loan-tenure").slider({
    value: $(".slider-loan-tenure").data("value"),
    min: $(".slider-loan-tenure").data("min"),
    max: $(".slider-loan-tenure").data("max"),
    orientation: "horizontal",
    animate: !0,
    range: "min",
    slide: function(event, ui) {
        if ("" != $(".slider-loan-tenure").attr("data-soft-cap")) {
            var o = parseInt($(".slider-loan-tenure").attr("data-soft-cap"));
            if (ui.value > o) return !1
        }
        $(".loan-tenure-label").html(ui.value);
        $("input[name=loan_tenure]").val(ui.value);
    },
    change: function(event, ui) {
        updateSlider();
        updateLoanAmount();
    }
});

$(".btn-less-detail").hide();
$(".btn-more-detail").on('click', function(){
    $(this).closest(".filters-content").find(".more-info").slideDown();
    $(this).hide();
    $(this).next().show();
});

$(".btn-less-detail").on('click', function(){
    $(this).closest(".filters-content").find(".more-info").slideUp();
    $(this).hide();
    $(this).prev().show();
});
JS;
$this->inlineScript()->captureEnd();
?>