<?php
$slider_loan_tenture = '$slider_loan_tenture';
$slider_loan_percent = '$slider_loan_percent';
?>
<form class="form-horizontal form-home-loan-wizard form-wizard" action="<?php echo $this->url("home_loan", array("action" => "step", "id" => 2)) ?>" method="POST">
    <div class="form-body">
        <div class="form-group">
            <div class="row existing_home_loans form-wizard-title">
                <h3>3. <?php echo $this->translate("How many existing home loan do you have") ?>?</h3>
                <a href="javascript:;" class="tooltip-icon popovers pull-right" data-trigger="hover" data-placement="left" data-container="body" data-content="<p>This will determine the maximum loan % you are eligible for:<ul><li>80% (if this is your first home loan)</li><li>50%(if this is your second home loan)</li><li>40% (if this is your 3rd home loan and above)</li></ul></p>" data-html="true" data-original-title="<span><?php echo $this->translate("Existing Home Loans") ?></span>"><i class="fa fa-question-circle"></i></a>
            </div>
            <div class="row indented">
                <div class="col-md-12">
                    <span><?php //echo $this->translate("HDB buyers cannot have any other outstanding home loans"); ?></span>
                    <div class="property-type">
                        <a href="javascript:;" onclick="Loan.set_exist(this)" data-value="0" class="property-type-box circle active">
                            <i class="icon-check hide"></i>
                            <span class="number"><?php echo $this->translate("0") ?></span>
                        </a>
                        <a href="javascript:;" onclick="Loan.set_exist(this)" data-value="1" class="property-type-box circle<?php if($this->property_type === 'HDB Flat') echo ' disabled'; ?>">
                            <i class="icon-check hide"></i>
                            <span class="number"><?php echo $this->translate("1") ?></span>
                        </a>
                        <a href="javascript:;" onclick="Loan.set_exist(this)" data-value="2+" class="property-type-box circle<?php if($this->property_type === 'HDB Flat') echo ' disabled'; ?>">
                            <i class="icon-check hide"></i>
                            <span class="number"><?php echo $this->translate("2+") ?></span>
                        </a>
                    </div>
                    <input type="hidden" name="existing_home_loans" value="0" />
                </div>
            </div>
        </div>
        <div class="form-group with-pie purchase_price">
            <div class="row form-wizard-title">
                <h3>4. <?php echo $this->translate("What is the purchase price of the property") ?>?</h3>
                <a href="javascript:;" class="tooltip-icon popovers pull-right" data-trigger="hover" data-placement="left" data-container="body" data-content="<p>Banks will calculate your home loan based on the property's market valuation or purchase price, whichever is lower.</p><p>If you know that the market valuation of your property is less than the purchase price, please key in the market valuation. If you're unsure of the market valuation, just indicate its purchase price.</p>" data-html="true" data-original-title="<span><?php echo $this->translate("Purchase Price / Market Valuation") ?></span>"><i class="fa fa-question-circle"></i></a>
            </div>
            <div class="row indented">
                <div class="col-md-6">
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i><?php echo $this->translate("Purchase Price ($)") ?></i>
                        </span>
                        <input type="text" name="purchase_price" class="form-control" placeholder="<?php echo $this->translate("e.g. 500000, 500k, 1.2m") ?>">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="indented form-wizard-subtitle">
                        <h4 class="font-blue"><?php echo $this->translate("How long do you want your tenure to be") ?>?</h4>
                        <a href="javascript:;" class="tooltip-icon popovers pull-right" data-trigger="hover" data-placement="left" data-container="body" data-content="<p>Your loan tenure is the full duration of your loan repayment period. A shorter tenure means you pay less interest but higher monthly instalments, while a longer tenure means you pay more interest, but lower monthly instalments.</p><p>The maximum loan tenure is 35 years (for private properties and ECs) and 30 years (for HDB flats).</p>" data-html="true" data-original-title="<span><?php echo $this->translate("Loan Tenure") ?></span>"><i class="fa fa-question-circle"></i></a>
                    </div>
                    <div class="indented">
                        <div class="col-md-9">
                            <div class="slider-container">
                                <div class="slider-loan-tenure" data-min="5" data-max="30" data-value="20" data-soft-cap="30"></div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="slider-value">
                                <span class="current info" id="loan_tenure-label">20</span>
                                <span class="unit">Years</span>
                            </div>
                        </div>
                    </div>
                    <div class="indented form-wizard-subtitle">
                        <h4 class="font-blue"><?php echo $this->translate("What % of the price would you like to loan") ?>?</h4>
                        <a href="javascript:;" class="tooltip-icon popovers pull-right" data-trigger="hover" data-placement="left" data-container="body" data-content="<p>You can borrow up to 80% for your 1st home loan; 50% for your 2nd; or 40% if it's your 3rd and beyond.</p><p>To qualify for the maximum loan %, your loan tenure cannot exceed 30 years (for private properties and ECs) and 25 years (for HDB flats). The borrower's age also cannot cross 65 at the end of the loan tenure.</p><p>Violating any of these conditions will result in a 20% reduction in your loan %.</p><p><strong style='color: #CC6055'>A MoneyCompare Mortgage Specialist will be able to advise you further on this, after you proceed to Step 5.</strong></p>" data-html="true" data-original-title="<span><?php echo $this->translate("Loan Tenure") ?></span>"><i class="fa fa-question-circle"></i></a>
                    </div>
                    <div class="indented">
                        <div class="col-md-9">
                            <div class="slider-container">
                                <div class="slider-loan-amount" data-min="10" data-max="80" data-value="80" data-soft-cap="80"></div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="slider-value">
                                <span class="current info" id="loan_amount-label">80</span>
                                <span class="unit">Percent</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 indented easy-pie-chart">
                <div class="number loans" data-percent="80"><span>80%</span></div>
                <div class="pie-chart-info">
                    <div style="display: inline-block; margin: 15px 10px;">
                        <div class="info-heading"><?php echo $this->translate("Loan Amount") ?>
                            <em><span class="main-percentage">(80%)</span></em>
                        </div>
                        <div class="info-amount">
                            $<span class="loan-amount" id="loan-amount-label">-</span>
                        </div>
                    </div>
                    <div style="display: inline-block; margin: 15px 10px;">
                        <div class="info-heading minor"><?php echo $this->translate("Downpayment") ?>
                            <em><span class="minor-percentage">(20%)</span></em>
                        </div>
                        <div class="info-amount minor">
                            $<span class="downpayment" id="downpayment-label">-</span>
                        </div>
                    </div>
                </div>
                <input type="hidden" name="loan_amount" value="0" />
                <input type="hidden" name="loan_tenure" value="20" />
                <input type="hidden" name="loan_percent" value="80" />
                <div class="clearfix"></div>
                <div class="">
                    <h4 class="font-blue inline-block"><?php echo $this->translate("Keen to know your expected Total Costs Outlay") ?></h4>
                    <a href="javascript:void(0);" id="expected-total-costs-outlay">
                        <i class="fa fa-plus" aria-hidden="true"></i>
                    </a>

                    <div class="collapse" id="total-costs-outlay">
                          <div class="row col-md-12 form-inline clearfix mx-auto">
                            <h3 class="control-label">1. Residency</h3>
                            <div class="input-group mx-auto">
                                <div class="property-type">
                                    <a href="javascript:;" onclick="Loan.set_residency(this)" data-value="Singaporean" class="property-type-box active">
                                        <i class="icon-check"></i>
                                        <span class="number"><?php echo $this->translate("Singaporean") ?></span>
                                    </a>
                                    <a href="javascript:;" onclick="Loan.set_residency(this)" data-value="Singapore PR" class="property-type-box">
                                        <i class="icon-check"></i>
                                        <span class="number"><?php echo $this->translate("Singapore PR") ?></span>
                                    </a>
                                    <a href="javascript:;" onclick="Loan.set_residency(this)" data-value="Foreigner" class="property-type-box">
                                        <i class="icon-check"></i>
                                        <span class="number"><?php echo $this->translate("Foreigner") ?></span>
                                    </a>
                                </div>
                                <input type="hidden" name="residency" value="Singaporean" />
                            </div>
                          </div>
                          <div class="row col-md-12 form-inline mx-auto clearfix">
                            <h3 class="control-label">2. How many property do you have in Singapore?</h3>
                            <div class="input-group">
                                <div class="property-type">
                                    <a href="javascript:;" onclick="Loan.set_property(this)" data-value="0" class="property-type-box active">
                                        <i class="icon-check"></i>
                                        <span class="number"><?php echo $this->translate("0") ?></span>
                                    </a>
                                    <a href="javascript:;" onclick="Loan.set_property(this)" data-value="1" class="property-type-box">
                                        <i class="icon-check"></i>
                                        <span class="number"><?php echo $this->translate("1") ?></span>
                                    </a>
                                    <a href="javascript:;" onclick="Loan.set_property(this)" data-value="2+" class="property-type-box">
                                        <i class="icon-check"></i>
                                        <span class="number"><?php echo $this->translate("2+") ?></span>
                                    </a>
                                </div>
                                <input type="hidden" name="existing_property" value="0" />
                            </div>
                          </div>
                          <div class="row col-md-12 mx-auto mg-top-sm">
                            <h3 class="mg-bottom-xs"><?php echo $this->translate("Based on loan amount, below is your expected Total Cost Layout") ?></h3>
                            <table class="table table-bordered table-striped table-condensed flip-content" id="complete-total-costs">
                                <tbody class="flip-content">
                                    <tr>
                                        <td><label><?php echo $this->translate("Stamp Duty Fee") ?></label></td>
                                        <td class="text-right"><strong id="stamp-duty-fee">$0</strong></td>
                                    </tr>
                                    <tr>
                                        <td><label><?php echo $this->translate("Mortgage Stamp Duty"); ?></label></td>
                                        <td class="text-right"><strong>$500</strong></td>
                                    </tr>
                                    <tr>
                                        <td><label><?php echo $this->translate("Valuation Fee"); ?></label></td>
                                        <td class="text-right"><strong>$300</strong></td>
                                    </tr>
                                    <tr>
                                        <td><label><?php echo $this->translate("Legal Fee"); ?></label></td>
                                        <td class="text-right"><strong>$2,000</strong></td>
                                    </tr>
                                    <tr>
                                        <td><label><?php echo $this->translate("Fire Insurance"); ?></label></td>
                                        <td class="text-right"><strong>$250</strong></td>
                                    </tr>
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <td>
                                            <h3 class="inline-block"><?php echo $this->translate("Total Cost Outlay"); ?></h3>
                                            <a href="javascript:;" class="tooltip-icon popovers inline-block" data-trigger="hover" data-placement="right" data-container="body" data-content="<p>Can be partially paid by Cash + CPF</p>" data-html="true"><i class="fa fa-question-circle"></i></a>
                                        </td>
                                        <td>
                                            <strong id="total-costs-outlay-amount" class="text-right" ></strong>
                                        </td>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                </div>
            </div>
            </div>
        </div>
        
    </div>
    <div class="form-actions">
        <input type="hidden" name="property_type" value="<?php echo $this->property_type ?>" />
        <div class="row">
            <div class="col-md-3 col-sm-6 col-xs-12">
                <a class="btn grey-mint btn-lg btn-fullwidth" href="<?php echo $this->url("home_loan", array("action" => "step", "id" => 1)) ?>"><?php echo $this->translate("Back") ?></a>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12">
                <button type="submit" class="btn btn-lg blue"><?php echo $this->translate("Next Step") ?> <i class="fa fa-caret-right"></i></button>
            </div>
        </div>
    </div>
</form>
<?php
$offStyle = 12;
$offScript = 30;
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/jquery-ui/jquery-ui.min.css'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/jquery-ui/jquery-ui.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/jquery-easypiechart/jquery.easypiechart.min.js'));
$this->inlineScript()->offsetSetFile(100, $this->basePath('assets/js/custom3.js'));
$this->inlineScript()->offsetSetFile(101, $this->basePath('assets/js/residential-loan-refinancing.js'));
?>