<div id="brand-home">
<div class="container">
<div class="brand-desc">
<p>We Compare Singapore&rsquo;s most reputable <strong>Financial Institutions &amp; Lenders</strong></p>
</div>
<div class="brand">
<div class="item"><img src="../../data/brand/0.png" /></div>
<div class="item"><img src="../../data/brand/1.png" /></div>
<div class="item"><img src="../../data/brand/2.png" /></div>
<div class="item"><img src="../../data/brand/3.png" /></div>
<div class="item"><img src="../../data/brand/4.png" /></div>
<div class="item"><img src="../../data/brand/5.png" /></div>
<div class="item"><img src="../../data/brand/6.png" /></div>
<div class="item"><img src="../../data/brand/7.png" /></div>
<div class="item"><img src="../../data/brand/8.png" /></div>
<div class="item"><img src="../../data/brand/9.png" /></div>
<div class="item"><img src="../../data/brand/10.png" /></div>
<div class="item"><img src="../../data/brand/11.png" /></div>
<div class="item"><img src="../../data/brand/12.png" /></div>
<div class="item"><img src="../../data/brand/13.png" /></div>
<div class="item"><img src="../../data/brand/14.png" /></div>
<div class="item"><img src="../../data/brand/15.png" /></div>
<div class="item"><img src="../../data/brand/16.png" /></div>
<div class="item"><img src="../../data/brand/17.png" /></div>
<div class="item"><img src="../../data/brand/18.png" /></div>
</div>
</div>
</div>
<div id="services-home">
<div class="services-desc">
<div class="container">
<p>Our <strong>Broad Range</strong> of Services</p>
<ul>
<li>Save Money &amp; Time</li>
<li>Get the Best Deal Within 20 Secs</li>
<li>100% Independent</li>
</ul>
</div>
</div>
<div class="services-content">
<div class="box-services">
<div class="row">
<div class="item_services">
<div class="item">
<div class="image"><img src="../../assets/img/floating_1.jpg" /></div>
<div class="caption">
<h3 class="name"><a>Business Term Loan</a></h3>
<div class="desc">
<ul>
<li>● Boost your Working Capital With Collateral- Free Loan</li>
<li>● Up to 5 years Repayment</li>
<li>● Lowest Interest Rates Online</li>
<li>● Get Response within 24 hrs</li>
</ul>
</div>
<div class="group-btn"><a class="btn white-custom btn-block btn-lg margin-top-20" href="../../business-term-loan">Apply Now</a></div>
</div>
</div>
</div>
<div class="item_services">
<div class="item">
<div class="image"><img src="../../assets/img/floating_2.jpg" /></div>
<div class="caption">
<h3 class="name"><a>Property Loan</a></h3>
<div class="desc">
<ul>
<li>● Up to 120% Financing For Business Property</li>
<li>● Legal and Valuation Subsidy</li>
<li>● TDSR/ Affordability/ Stamp Duty Fee Calculators</li>
<li>● Zero Fees/ Fuss Free/ Easy Submission using our Mortgage Specialist</li>
<li>● Calculate Total Interest Savings When Refinancing</li>
</ul>
</div>
<div class="group-btn"><a class="btn white-custom btn-block btn-lg margin-top-20" href="../../business-term-loan">Apply Now</a></div>
</div>
</div>
</div>
<div class="item_services">
<div class="item">
<div class="image"><img src="../../assets/img/floating_3.jpg" /></div>
<div class="caption">
<h3 class="name"><a>Corporate Bank Account</a></h3>
<div class="desc">
<ul>
<li>● Free Business Internet Banking</li>
<li>● $0 Min Balance Fee</li>
<li>● No Annual Fee</li>
<li>● Apply Online In 5 Mins</li>
</ul>
</div>
<div class="group-btn"><a class="btn white-custom btn-block btn-lg margin-top-20" href="../../business-term-loan">Apply Now</a></div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<div id="total">
<div class="container">
<div class="total-content">
<h3 class="heading-total">We Have Served Over 406 Business and</h3>
<div class="total-group">
<div class="row">
<div class="col-sm-6 col-xs-12">
<div class="total-item">
<i class="fa fa-users" aria-hidden="true"></i>
<div class="caption-total">
<span data-counter="counterup" data-value="406">0</span> 
<span>Businesses Served</span>
<p>SMEs have used our comparison tools for their business banking needs</p>
</div>
</div>
</div>
<div class="col-sm-6 col-xs-12">
<div class="total-item">
<i class="fa fa-money" aria-hidden="true"></i>
<div class="caption-total"><span data-counter="counterup" data-value="13,000,000">$0</span> 
<span>Loan Approved</span>
<p>Simplified comparison and easy to understand guideline have allowed SMEs to make more informed decision when applying for business banking products</p>
</div>
</div>
</div>
<div class="col-sm-6 col-xs-12">
<div class="total-item">
<i class="fa fa-check" aria-hidden="true"></i>
<div class="caption-total"><span data-counter="counterup" data-value="4,500,000">$0</span> 
<span>Refinancing Savings</span>
<p>We have help SMEs and Individual to save million of dollars savings when they refinanced their businesses or individual mortgages</p>
</div>
</div>
</div>
<div class="col-sm-6 col-xs-12">
<div class="total-item">
<i class="fa fa-life-ring" aria-hidden="true"></i>
<div class="caption-total"><span data-counter="counterup" data-value="18,000,000">$0</span> 
<span>Mortgage Loan Approved</span>
<p>Through us, you will definitely buy or refinance your property at the best interest rates</p>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<div id="why-use" class="text-center font-white">
<div class="container">
<div class="row">
<h3 class="margin-bottom-40">Why use Money Compare?</h3>
<div class="col-md-3 col-sm-6 col-xs-12"><img src="http://moneycompare.websgdemo.com/assets/img/why_1.png" />
<h4>We are <strong>#1 in Singapore</strong></h4>
<div class="line-why">&nbsp;</div>
<p>The #1 business(SMEs) focused financial comparison site in Singapore. Thousands of businesses have trusted us with their financial decisions. We are non-biased, we make sure you will always get the best deal every time</p>
</div>
<div class="col-md-3 col-sm-6 col-xs-12"><img src="http://moneycompare.websgdemo.com/assets/img/why_2.png" />
<h4>We are <strong>the experts</strong></h4>
<div class="line-why">&nbsp;</div>
<p>We do all the homeworks so that you can find the best business banking facilities, home loan, business property loans, peer to peer lending and more with our easy to use interface</p>
</div>
<div class="col-md-3 col-sm-6 col-xs-12"><img src="http://moneycompare.websgdemo.com/assets/img/why_3.png" />
<h4>We are <strong>Fast &amp; Hassle-Free</strong></h4>
<div class="line-why">&nbsp;</div>
<p>We know business owners are busy, let our friendly product specialist assist* in your application and complete the application in the comfort of your office
*success fee chargeable for Business Term Loan
</p>
</div>
<div class="col-md-3 col-sm-6 col-xs-12"><img src="http://moneycompare.websgdemo.com/assets/img/why_4.png" />
<h4>Member Get <strong>Member Programme (MGM)</strong></h4>
<div class="line-why">&nbsp;</div>
<p>We are the 1st comparison site to introduce MGM program cos we know everyone likes a good deal, so why not share with your business partners and associate and get rewarded! Click (insert link to MGM FAQ here) to find out more</p>
</div>
</div>
</div>
</div>
<div id="subscribe">
<div class="container">
<div class="row">
<div class="col-md-6 col-xs-12">
<div class="subscribe"><form id="form_subscribe" class="form-horizontal" action="http://moneycompare.websgdemo.com/user/add-subscribe" method="post"><img class="img-responsive" src="http://moneycompare.websgdemo.com/assets/img/homesubrice.png" />
<div class="caption-sub">
<div class="box-sub">
<h4>Get Business Money Saving Tips Every Week</h4>
Subscribe to get updated rates and promotion!</div>
<input class="form-control input-lg" name="subscribe_email" type="text" placeholder="Enter your email here" /> <button class="btn btn-lg green-custom btn-block margin-top-10" type="submit">Subscribe</button></div>
</form></div>
</div>
<div class="col-md-3 col-sm-6 col-xs-6">
<div class="box-lastet-loan">
<div class="title-last-loan">Latest Business Loan Rates From As Low As</div>
<div class="content-action">
<ul>
<li>
<div class="rate">
<div><span data-counter="counterup" data-value="6.75">0</span>%</div>
<div>Interest Rate</div>
</div>
<div class="image"><img class="img-responsive" src="http://moneycompare.websgdemo.com/data/bank/8/m_8.png" /></div>
</li>
<li>
<div class="rate">
<div><span data-counter="counterup" data-value="8.88">0</span>%</div>
<div>Interest Rate</div>
</div>
<div class="image"><img src="http://moneycompare.websgdemo.com/data/bank/7/m_1500449618.jpg" /></div>
</li>
</ul>
<a class="btn-viewall-loan" href="#">View All Business Loan</a></div>
</div>
</div>
<div class="col-md-3 col-sm-6 col-xs-6">
<div class="box-lastet-loan">
<div class="title-last-loan">Latest Residential Loan Rates From As Low As</div>
<div class="content-action">
<ul>
<li>
<div class="rate">
<div><span data-counter="counterup" data-value="1.27">0</span>%</div>
<div>Interest Rate</div>
</div>
<div class="image"><img class="img-responsive" src="http://moneycompare.websgdemo.com/data/bank/6/m_6.png" /></div>
</li>
<li>
<div class="rate">
<div><span data-counter="counterup" data-value="1.3">0</span>%</div>
<div>Interest Rate</div>
</div>
<div class="image"><img src="http://moneycompare.websgdemo.com/data/bank/7/m_1500449618.jpg" /></div>
</li>
</ul>
<a class="btn-viewall-loan" href="#">View All Business Loan</a></div>
</div>
</div>
</div>
</div>
</div>