<form class="form-horizontal form-wizard form-refinancing" action="<?php echo $this->url("refinancing", array("action" => "step", "id" => 1)) ?>" method="POST">
    <div class="form-body">
        <div class="form-group">
            <div class="row property_type form-wizard-title">
                <h3>1. <?php echo $this->translate("What is the property type you be refinancing") ?>?</h3>
                <a href="javascript:;" class="tooltip-icon popovers pull-right" data-trigger="hover" data-placement="left" data-container="body" data-content="<p>Loan packages differ depending on property type.</p>" data-html="true" data-original-title="<span><?php echo $this->translate("Property Type") ?></span>"><i class="fa fa-question-circle"></i></a>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="property-type">
                        <a href="javascript:;" onclick="Loan.set_type(this)" data-value="HDB Flat" class="property-type-box active">
                            <i class="icon-check"></i>
                            <img src="<?php echo $this->basePath("/assets/img/hdb-flat.png") ?>" />
                            <span><?php echo $this->translate("HDB Flat") ?></span>
                        </a>
                        <a href="javascript:;" onclick="Loan.set_type(this)" data-value="Executive Condo" class="property-type-box">
                            <i class="icon-check"></i>
                            <img src="<?php echo $this->basePath("/assets/img/executive.png") ?>" />
                            <span><?php echo $this->translate("Executive Condo") ?></span>
                        </a>
                        <a href="javascript:;" onclick="Loan.set_type(this)" data-value="Condo / Apartment" class="property-type-box">
                            <i class="icon-check"></i>
                            <img src="<?php echo $this->basePath("/assets/img/condo-apt.png") ?>" />
                            <span><?php echo $this->translate("Condo / Apartment") ?></span>
                        </a>
                        <a href="javascript:;" onclick="Loan.set_type(this)" data-value="Landed Property" class="property-type-box">
                            <i class="icon-check"></i>
                            <img src="<?php echo $this->basePath("/assets/img/landed.png") ?>" />
                            <span><?php echo $this->translate("Landed Property") ?></span>
                        </a>
                    </div>
                    <input type="hidden" name="property_type" value="HDB Flat" />
                </div>
            </div>

            <div class="row property form-wizard-title">
                <h3>2. <?php echo $this->translate("Your property is currently with which Financial Institution/ Banks") ?>?</h3>
                <a href="javascript:;" class="tooltip-icon popovers pull-right" data-trigger="hover" data-placement="left" data-container="body" data-content="<p>If you are refinancing your mortgage, we will redirect you to the refinancing wizard.</p>" data-html="true" data-original-title="<span><?php echo $this->translate("New Home / Refinancing") ?></span>"><i class="fa fa-question-circle"></i></a>
            </div>
            <div class="row">
                <div class="row col-md-12">
                    <div class="col-md-3">
                        <select class="form-control nobtngrp floatrate" id="current_bank_name" name="current_bank_name">
                        <?php
                            foreach ($this->banks() as $key => $value)
                        {                             
                        ?>
                            <option value="<?php echo $value->getId()?>"><?php echo $value->getName()?></option>
                        <?php
                        }
                        ?>
                        </select>
                    </div>
                </div>
            </div>
            <div class="row property_status form-wizard-title">
                <h3>3. <?php echo $this->translate("What is your outstanding loan amount") ?>?</h3>
                <a href="javascript:;" class="tooltip-icon popovers pull-right" data-trigger="hover" data-placement="left" data-container="body" data-content="<p><p>Minimum loan amount to be eligible for refinancing is at least S$100,000.</p></p>" data-html="true" data-original-title="<span><?php echo $this->translate("Outstanding Loan Amount") ?></span>"><i class="fa fa-question-circle"></i></a>
            </div>

            <div class="row">
                <div class="row col-md-12">
                    <div class="col-md-3">
                        <div class="input-group">
                            <span class="input-group-addon">
                                <i><?php echo $this->translate("$") ?></i>
                            </span>
                            <input type="text" name="remaining_loan_amount" class="form-control" placeholder="<?php echo $this->translate("e.g. 500000, 500k, 1.2m") ?>">
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group option_fee">
            <div class="row form-wizard-title">
                <h3>4. <?php echo $this->translate("What is your current interest rate") ?>?</h3>
                <a href="javascript:;" class="tooltip-icon popovers pull-right" data-trigger="hover" data-placement="left" data-container="body" data-content="<p>The higher the interest rate, the more savings you will enjoy! If unsure, input an estimate. This will allows us to calculate the total interest savings if you refinance.</p>" data-html="true" data-original-title="<span><?php echo $this->translate("Current Interest Rate") ?></span>"><i class="fa fa-question-circle"></i></a>
            </div>

            <div class="row">
                <div class="row col-md-12">
                    <div class="col-md-3">
                        <div class="input-group">
                            <input type="text" name="current_interest_rate" class="form-control" placeholder="<?php echo $this->translate("Interest Rate") ?>">
                            <span class="input-group-addon">
                                <i><?php echo $this->translate("%") ?></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group option_fee">
            <div class="row form-wizard-title">
                <h3>5. <?php echo $this->translate("What is your remaining tenor") ?>?</h3>
                <a href="javascript:;" class="tooltip-icon popovers pull-right" data-trigger="hover" data-placement="left" data-container="body" data-content="<p>Input remaining tenor for us to calculate the total interest savings you will enjoy for refinancing.</p>" data-html="true" data-original-title="<span><?php echo $this->translate("Remaining Tenor") ?></span>"><i class="fa fa-question-circle"></i></a>
            </div>

            <div class="row">
                <input type="hidden" name="loan_tenure" value="20" />
                <div class="row col-md-12">
                    <div class="col-md-3">
                        <div class="slider-container">
                            <div class="slider-loan-tenure" data-min="5" data-max="35" data-value="5" data-soft-cap="35"></div>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="slider-value">
                            <span class="current info" id="loan_tenure-label">5</span>
                            <span class="unit">Years</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row property form-wizard-title">
            <h3>6. <?php echo $this->translate("Are you still under locked-in period") ?>?</h3>
            <a href="javascript:;" class="tooltip-icon popovers pull-right" data-trigger="hover" data-placement="left" data-container="body" data-content="<p>If you are refinancing your mortgage, we will redirect you to the refinancing wizard.</p>" data-html="true" data-original-title="<span><?php echo $this->translate("New Home / Refinancing") ?></span>"><i class="fa fa-question-circle"></i></a>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="md-radio-list">
                    <div class="md-radio">
                        <input type="radio" id="locked_in_no" name="locked_in" value="No" data-value="home_loan" class="md-radiobtn"<?php if($this->property === 'home_loan' || !$this->property) echo ' checked="checked"'; ?>>
                        <label for="locked_in_no">
                            <span></span>
                            <span class="check"></span>
                            <span class="box"></span> <?php echo $this->translate("No, i’m out of locked-in period") ?>
                        </label>
                    </div>
                    <div class="md-radio">
                        <input type="radio" id="locked_in_yes" name="locked_in" value="Yes" data-value="Yes" class="md-radiobtn"<?php if($this->property === 'refinancing') echo ' checked="checked"'; ?>>
                        <label for="locked_in_yes">
                            <span></span>
                            <span class="check"></span>
                            <span class="box"></span> <?php echo $this->translate("Still under locked-in period") ?>
                        </label>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="form-actions">
        <div class="row">
            <div class="col-md-12 text-right">
                <button type="submit" class="btn btn-lg blue"><?php echo $this->translate("Next Step") ?> <i class="fa fa-caret-right"></i></button>
            </div>
        </div>
    </div>
</form>
<?php
$offStyle = 12;
$offScript = 30;
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/jquery-ui/jquery-ui.min.css'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/jquery-ui/jquery-ui.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/jquery-easypiechart/jquery.easypiechart.min.js'));
$this->inlineScript()->offsetSetFile(100, $this->basePath('assets/js/custom3.js'));
$this->inlineScript()->offsetSetFile(101, $this->basePath('assets/js/residential-loan-refinancing.js'));
?>