<?php
$title = $this->category->getName();
$this->headTitle($title);
$min_loan_amount = $this->setting()->min_loan_amount;
$max_loan_amount = $this->setting()->max_loan_amount;
$max_loan_tenure = $this->setting()->max_loan_tenure;
?>
<div class="title-property">
    <div class="container">
        <h2><?php echo $title ?></h2>
        <div class="portlet-head">
            <div class="row">
                <div class="col-md-12">
                    <div class="stepproperty">
                        <div class="stepproperty-row">
                            <div class="stepproperty-step<?php if($title === 'Current Account (SGD)') echo ' active'; ?>">
                                <div class="stepproperty-circle">S$</div>
                                <p>Current Account (SGD)</p>
                            </div>
                            <div class="line-stepproperty line-stepproperty1"></div>
                            <div class="stepproperty-step<?php if($title === 'Current Account (USD)') echo ' active'; ?>">
                                <div class="stepproperty-circle">$</div>
                                <p>Current Account (USD)</p>
                            </div>
                            <div class="line-stepproperty line-stepproperty2"></div>
                            <div class="stepproperty-step<?php if($title === 'Fixed Deposit') echo ' active'; ?>">
                                <div class="stepproperty-circle">%</div>
                                <p>Fixed Deposit</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>    
        </div>
    </div>
</div>

<section class="search-bank-fixed">
    <div class="container">
        <div class="search-bank">
            <form method="post" action="<?php echo $this->url("loan_application", array("action" => "bank-account")) ?>" id="form_loan">
                <div class="col-md-9">
                    <div class="row">
                        <div class="col-md-7 col-xs-12 line-search">
                            <div class="row">
                                <b class="col-md-5 col-sm-4  col-xs-12 lb-loan"><?php echo $this->translate("I want to borrow") ?></b>
                                <div class="col-md-7 col-sm-8 col-xs-12">
                                    <div class="input-group">
                                        <input type="text" name="loan_amount" value="50000" id="loan_amount" class="form-control" placeholder="50000" />
                                        <span class="input-group-addon"><i class="fa fa-usd"></i></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-5 col-xs-12 line-search">
                            <div class="row">
                                <b class="col-md-3 col-sm-4 col-xs-12 lb-loan"><?php echo $this->translate("over") ?></b>
                                <div class="col-md-9 col-sm-8 col-xs-12">
                                    <div class="input-group">
                                        <select name="loan_tenure" class="form-control">
                                            <option value="3"><?php echo $this->translate("3 months") ?></option>
                                            <option value="6"><?php echo $this->translate("6 months") ?></option>
                                            <option value="12"><?php echo $this->translate("12 months") ?></option>
                                            <option value="13"><?php echo $this->translate("13 months") ?></option>
                                            <option value="18"><?php echo $this->translate("18 months") ?></option>
                                            <option value="24"><?php echo $this->translate("24 months") ?></option>
                                            <option value="30"><?php echo $this->translate("30 months") ?></option>
                                        </select>
                                        <span class="input-group-addon"><i class="fa-year"><?php echo $this->translate("months") ?></i></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 col-xs-12">
                    <input type="hidden" name="category_id" value="<?php echo $this->category->getId(); ?>" />
                    <button type="button" id="submit-search" class="btn_calculate"><?php echo $this->translate("Calculate My Results") ?></button>
                </div>
            </form>
        </div>
    </div>
</section>

<div class="container">
    <div class="page-content-inner">
        <div class="row">
            <div class="col-md-12">
                <div class="filters-table-container" id="results"></div>
                <input type="hidden" name="category_id" value="<?php echo $this->category->getId(); ?>" />
            </div>
        </div>
    </div>
</div>

<section class="shortlist" style="overflow: hidden; display: none;"> 
    <div class="container" id="shortlisted-holder">
        <div class="row">
            <div class="col-xs-4">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="shortlist-info-container">
                            <div class="shortlist-info" id="compare-title"><span>0</span> <?php echo $this->translate("Shortlisted Business Term Loan") ?></div>
                            <p><?php echo $this->translate("Select up to 3 banks for comparison") ?></p>
                            <a class="clear-shortlist" href="javascript:;" onclick="Loan.clear_compare(this)"><i class="fa fa-times-circle"></i> <?php echo $this->translate("Clear Shortlist") ?></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-6" id="compare-holder"></div>
            <div class="col-xs-2">
                <div class="row">
                    <a class="btn blue btn-lg text-uppercase fancybox-button" href="#compare" onclick="Loan.popup()"><?php echo $this->translate("Compare Now") ?></a>
                </div>
            </div>
        </div>
    </div>
</section>

<?php
echo $this->partial('compare');

$offStyle = 12;
$offScript = 10;
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/jquery-validation/js/jquery.validate.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/jquery-validation/js/additional-methods.min.js'));
$this->inlineScript()->offsetSetFile(100, $this->basePath('assets/js/custom4.js')); 
$this->inlineScript()->captureStart();
echo <<<JS
$(document).ready(function() {
    Loan.load_compare();
    $('.btn_calculate').on('click', function() {
        var category_id = $("input[name=category_id]").val();
        
        var loan_amount = formatIntNumber($("input[name=loan_amount]").val());
        var loan_tenure = $("select[name=loan_tenure]").val();

        if(loan_amount > 0 && loan_tenure > 0) {
            $.ajax({
                type: "POST",
                url: $("#form_loan").attr("action"),
                data: {category_id: category_id, loan_amount: loan_amount, loan_tenure: loan_tenure},
                dataType: 'json',
                beforeSend: function() {
                    App.blockUI({boxed: true});
                },
                success: function(itemJson) {
                    App.unblockUI();
                    $('#results').html(itemJson.html);
                    $(".summary-details").hide();
                    $(".btn-less-detail").hide();
                    $(".btn-more-detail").on('click', function(){
                        $(this).closest(".row-footer").find(".summary-details").slideDown();
                        $(this).hide();
                        $(this).next().show();
                    });

                    $(".btn-less-detail").on('click', function(){
                        $("p").slideDown();
                        $(this).closest(".row-footer").find(".summary-details").slideUp();
                        $(this).hide();
                        $(this).prev().show();
                    });
                },

                error : function(xhr, status){
                    console.log(status);
                },
            });
        }
    });
    $("#loan_amount").on("keyup", function() {
        var val = $(this).val();
        val = Number(val.replace(/,/g, ""));
        $(this).val(formatNumber(val, ""));
    });
    
    // Trigger
    $( "#loan_amount" ).trigger( "change" );
    $( ".btn_calculate" ).trigger( "click" );
});
JS;
$this->inlineScript()->captureEnd();

?>