<?php
$title = $this->translate("Edit Credit Card");
$this->headTitle($title);
?>
<!-- BEGIN SIDEBAR -->
<?php echo $this->partial('backend_sidebar', array('view' => 'credit_card_provider', 'action' => 'index')); ?>
<!-- END SIDEBAR -->
<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
  <div class="page-content">
    <!-- BEGIN PAGE BAR -->
    <div class="page-bar">
      <ul class="page-breadcrumb">
        <li>
          <a href="<?php echo $this->url('admin') ?>"><?php echo $this->translate("Dashboard") ?></a>
          <i class="fa fa-angle-right"></i>
        </li>
        <li>
          <a href="<?php echo $this->url('admin/credit_card_provider') ?>"><?php echo $this->translate("Credit Cards") ?></a>
          <i class="fa fa-angle-right"></i>
        </li>
        <li>
          <span><?php echo $this->translate("Edit") ?></span>
        </li>
      </ul>
    </div>
    <!-- END PAGE BAR -->

    <div class="row">
      <div class="col-md-12">
        <div class="portlet light bordered form-fit">
          <div class="portlet-title">
            <div class="caption">
              <i class="icon-credit-card"></i>
              <span class="caption-subject sbold uppercase"><?php echo $this->translate($title) ?></span>
            </div>
          </div>
          <div class="portlet-body form">
            <!-- BEGIN FORM-->
            <form action="<?php echo $this->url("admin/credit_card_provider", array("action" => "edit", "id" => $this->provider->getId())) ?>" id="form_credit_card" class="form-horizontal form-bordered">
              <div class="form-body">
                <div class="form-group">
                  <label class="control-label col-md-3"><?php echo $this->translate("Name") ?><span class="required"> * </span></label>
                  <div class="col-md-9">
                    <input type="text" name="name" data-required="1" class="form-control" value="<?php echo $this->provider->getName() ?>" />
                  </div>
                </div>

                <div class="form-group">
                  <label class="control-label col-md-3"><?php echo $this->translate("Status") ?></label>
                  <div class="col-md-9">
                    <select class="form-control" name="status">
                      <option value="1" <?php if($this->provider->getStatus() == 1) echo ' selected="selected"'; ?> ><?php echo $this->translate("Active") ?></option>
                      <option value="0" <?php if($this->provider->getStatus() == 0) echo ' selected="selected"'; ?>><?php echo $this->translate("Deactive") ?></option>
                    </select>
                  </div>
                </div>

                <div class="form-group">
                  <label class="control-label col-md-3"><?php echo $this->translate("Select Logo") ?></label>
                  <div class="col-md-9">
                    <div class="fileinput fileinput-new" data-provides="fileinput">
                      <div class="input-group input-large">
                        <div class="form-control uneditable-input input-fixed input-medium" data-trigger="fileinput">
                          <i class="fa fa-camera fileinput-exists"></i>&nbsp;
                          <span class="fileinput-filename"> </span>
                        </div>
                        <span class="input-group-addon btn default btn-file">
                          <span class="fileinput-new"> <?php echo $this->translate("Select file") ?> </span>
                          <span class="fileinput-exists"> <?php echo $this->translate("Change") ?> </span>
                          <input type="file" name="photoupload" id="photoupload" />
                          <input type="hidden" name="logo" id="logo" value="<?php echo $this->provider->getLogo() ?>" />
                        </span>
                        <a href="javascript:;" class="input-group-addon btn red fileinput-exists" data-dismiss="fileinput"> <?php echo $this->translate("Remove") ?> </a>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-xs-offset-3 col-xs-6">

                    <?php
                      if ($this->provider->getLogo()) {
                          $logo = $this->provider->getLogo();
                          if (!file_exists('data/providers/'.$this->provider->getId().'/logo/m_'.$logo)) {
                              $image_logo = $this->basePath('data/providers/'.$this->provider->getId().'/'.$logo);
                          } else {
                              $image_logo = $this->basePath('data/providers/'.$this->provider->getId().'/m_'.$logo);
                          }
                      } else {
                          $image_logo = $this->basePath('data/image/no-image-128.png');
                      }
                      ?>
                  <img id="photo" alt="logo" class="img-responsive" src="<?php echo $image_logo ?>">
                  </div>
                </div>
              </div>
              <div class="form-actions">
                <div class="row">
                  <div class="col-md-offset-3 col-md-9">
                    <button type="submit" class="btn red-thunderbird"><i class="fa fa-check"></i> <?php echo $this->translate("Submit") ?></button>
                    <button type="button" class="btn btn-outline" onclick="cancel('admin/bank')"><?php echo $this->translate("Cancel") ?></button>
                  </div>
                </div>
              </div>
            </form>
            <!-- END FORM-->
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- END CONTENT -->
<?php
$offStyle = 12;
$offScript = 10;
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/bootstrap-fileinput/bootstrap-fileinput.css'));
$this->headLink()->offsetSetStylesheet($offStyle++, $this->basePath('assets/plugins/jquery-minicolors/jquery.minicolors.css'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/bootstrap-fileinput/bootstrap-fileinput.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/jquery-minicolors/jquery.minicolors.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/jquery-validation/js/jquery.validate.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/jquery-validation/js/additional-methods.min.js'));
$this->inlineScript()->offsetSetFile($offScript++, $this->basePath('assets/plugins/tinymce/js/tinymce/tinymce.min.js'));
$this->inlineScript()->offsetSetFile(100, $this->basePath('assets/js/custom_functions.js'));
$this->inlineScript()->offsetSetFile(101, $this->basePath('assets/js/credit_card_provider_backend.js'));
?>